### ISSUE TITLE
Question: What is "dotnet5.4" target framework moniker in project.json

### ISSUE THREAD

**Issue by Tasteful** [aspnet/Home#1047]
I have seen that repositorys (ex DependencyInjection) now contains the TFM (target framework moniker) "dotnet5.4" instead of "dnx451". Is that a rename of the "dnx451" TFM and exists it some more information about this change?

**Comment by Tasteful** [comment]
I found this issue https://github.com/aspnet/dnx/issues/2724 but it missing a lot of information.

**Comment by Eilon** [comment]
There's a bit more info here now: https://github.com/aspnet/Announcements/issues/98

**Comment by paulirwin** [comment]
Can someone explain where the number 5.4 comes from? .NET Core is still pre-release, correct? That would imply that the number should be 5.0 when it is released. What are 5.1, 5.2, and 5.3? Will it jump to 5.5 once released since 5.4 is RC? The NuGet packages are at version 4.x, further adding to the confusion. I would expect .NET Core RTM to be dotnet5.0 and the framework NuGet packages to be 5.0.x.

**Comment by JauernigIT** [comment]
I can hardly see that "dotnet5.4" is a reasonable choice here. It's confusing, nothing more or less.

**Comment by Eilon** [comment]
@paulirwin yes .NET Core is still in pre-release, but the versions of .NET Core are independent of the "platform level" that it supports. Various components support different platform levels. For example, consider a hypothetical package Banana that has version 1.0 that supports .NET 4.5 and .NET 4.5.1, and a version 2.0-beta that supports .NET 4.5.1 and .NET 4.6. The "level" of .NET that is supported by the package is what the `dotnet5.4` thing is about. The idea of this is that instead of having to figure out exactly which levels of various .NET flavors to target (e.g. .NET Framework, .NET Core, Universal Apps, and others), you can just pick the "level" of .NET the library needs to target and it'll work wherever that "level" of .NET is supported.

@JauernigIT so that's why .NET 5.0, 5.1, 5.2, 5.3, 5.4, and 5.5 exist all of a sudden, all at once: there already exist multiple "levels" of .NET that need to be described in this new uniform way.

To read the *full* story about this, check out this far more detailed spec: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md

**Comment by davidfowl** [comment]
The monikers are changing to be a bit more clear in RC2

**Comment by JauernigIT** [comment]
@Eilon: I understand why it perhaps makes sense for uniqueness of stuff, but look at it from another view: most devs out there don't have their hands on this stuff until now. Perhaps they've heard of .NET Core and .NET 5, but they don't know the bits&bytes. Now when they see project.json and a dotnet5.4 framework in there, how could they not be confused? They just think "Well, why are we on .NET 5.4 yet? What have I missed?". This stuff has to be clear, at latest on RTM. But there's hope, as @davidfowl notes ;-)

**Comment by paulirwin** [comment]
@Eilon Thanks, but I did read that spec and it is clear as mud. No where in there does it mention 5.4, dotnet54, or how 5.4 is different from 5.0-5.3. So are you saying that 5.x can represent some level of targeting .NET Framework 4.6? I thought that dotnet54 meant that you were only targeting .NET Core, while net46 or net451 was how you targeted the .NET Framework.

**Comment by paulirwin** [comment]
@Eilon @davidfowl I just saw that this document has been updated to reflect the netstandard moniker. Does that mean that dotnet54 will become netstandard14?

Also, any particular reason why the monikers are not in a semver-like format, i.e. netstandard-1.4?

**Comment by TJSoftware** [comment]
@davidfowl [The ASP.Net 5 roadmap ](https://github.com/aspnet/Home/wiki/Roadmap) does not contain RC2 on it.  I thought it did before, but I could be mistaken.  Do you know when RC2 is expected?

**Comment by Eilon** [comment]
@paulirwin yeah there are some renames that will happen, which we hope will reduce some of the confusion. Too many things are called ".NET" these days, and we agree that's a problem, and we think we can improve that.

**Comment by Eilon** [comment]
@TJSoftware we're working on buttoning that down, but we haven't internally even chosen an exact date yet :smile:

**Comment by paulirwin** [comment]
@Eilon Awesome. Another question: how does the .NET Platform Standard versioning impact IL changes? Say C# 7 comes out that requires some new IL instruction (i.e. explicit SIMD support, perhaps with some C# keywords), even if all of the library contracts stay the same. Would that also bump the .NET Platform Standard version, like a major number bump to 2.0? I'm thinking along the lines of Generics in .NET 2.0 which required new IL to support it.

**Comment by davidfowl** [comment]
The Platform Standard (today) is purely about API changes, not so much IL changes or compiler changes, so no.

**Comment by paulirwin** [comment]
@davidfowl There's nothing wrong with a "we'll cross that bridge when we get there" approach for that, because you can always bump the version number. But I'd imagine IL changes would have to necessitate a version bump, because if new keyword x comes out that uses new IL instruction y and you create a library targeting netstandard-1.4, it will crash on any of the platforms that haven't been updated to support the new instruction (.NET 4.6, UWP, etc.). But then again, I don't even know if new IL instructions are even on the radar...

**Comment by TJSoftware** [comment]
@Eilon No worries, thanks for the info.  RC1 is doing good for me now :+1:

**Comment by nguyenm100** [comment]
Agree making this easy to consume is critical, else everyone will just cast the widest net (no pun intended), do a '*'. and call it a day.  Can the name also convey whether it's platform specific or xplat?  I realize .NET Framework is already embedded in everyone's brain from the years gone by but it's really just for Windows and caling it .NET Core (CoreCLR) w/it being xplat is simply confusing when sitting side by side with .NET Framework (not to mention net46 is .NET Framework and NOT.NET Core).

Hopefully, I got that right..

**Comment by joeaudette** [comment]
for anyone who wants a better understanding of this, @davidfowl and @DamianEdwards gave a great presentation about it in this video which just came through my rss stream yesterday.

https://channel9.msdn.com/Events/ASPNET-Events/ASPNET-Fall-Sessions/Class-Libraries

**Comment by paulirwin** [comment]
@joeaudette That video helped a ton in my understanding. Thanks!

**Comment by TJSoftware** [comment]
After reading the linked posts and watching the video I have a few questions.  It looks like the .net platform standard numbers have be renumbered to start at 1.0 [per this](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md#mapping-the-net-platform-standard-to-platforms).  With how we need to set the platform/framework in the project.json [this announcement](https://github.com/aspnet/Announcements/issues/98) shows that `dotnet5.4` replaces `dnxcore50`.  

If I am correct that the numbers have been renumbered to 1.0, does that mean that if I want to include the 5.1 platform I need to set (in the framework name value pair) `dotnet1.0` or will this still be `dotnet5.1`?

Even if the numbers are not reset to 1.0, is it appropriate to set the `dotnet5.4` in the framework name value pair of project.json or would it make more sense to set that in a (new) platform name value pair?  I think I can see why the platform numbers were starting at 5.1 now because all the generations support dnxcore 5.0 and if the numbers for the platform were/are reverted to 1.0 it can be even more confusing with the 1.0 .net framework that came out in 2002 (not that I am using it anymore :smile:).

**Comment by davidfowl** [comment]
@TJSoftware I'm not sure what you mean. The current target frameworks are dotnet5.1 - 5.5. In RC2 we're making a change to make it netstandard1.0 - 1.4.

There's a simplifying way to think about things. Ignore platforms and target the latest platform standard. If after testing you realize that it doesn't work all the places you want it to work then start targeting older versions until you hit something you need that isn't supported (some missing API for example) and stop. 

It's just like .NET Framework in that sense. The second dimension that tries to tell you how platforms map is so that you can understand (if you want to) where certain platform standards exist.

**Comment by TJSoftware** [comment]
@davidfowl Here are two snips from what the project.json files might look like from RC1 to RC2.

##### RC1
```
//...
  "frameworks": {
    "dotnet5.5": { 
       //deps here
     }
  },
//...
```

##### Is this correct for RC2 for a 1 to 1 comparison to RC1 dotnet5.5?
```
//...
  "frameworks": {
    "netstandard1.4": { 
       //deps here
     }
  },
//...
```

As for the second part of my post, instead of putting the platform under frameworks, place it in platform like ...

##### RC2 platform project.json proposal
```
//...
  "platform": {
    "dotnet5.4": { 
       //deps here
    }
  },
//...
```

**Comment by davidfowl** [comment]
> Is this correct for RC2 for a 1 to 1 comparison to RC1 dotnet5.5?

Yes.

> As for the second part of my post, instead of putting the platform under frameworks, place it in platform like ...

Nope. That's not changing.

**Comment by TJSoftware** [comment]
@davidfowl Thank you for the confirmation.

**Comment by nguyenm100** [comment]
I'll speak a bit candid and say the video just reinforced that this is indeed a confusing approach.  I don't mean to disparage because this is a difficult problem but saying "Nope.  That's not changing." is not constructive.  I am one data point but I don't want to have to look up in a chart to figure out which generation/version I need to target.  It seems backwards.  To @TJSoftware point, and I'll take a few liberties, it seems we're trying to optimize prematurely with the syntax.  I think there is some value in considering "plain speak" for us mortals.

When I'm picking a wine, I simply cannot be expected to remember all the estates, regions, years, varietals, etc.  I just know I like red, a bit on the dry side, and a taste of oak.  How about we try and model it around what people want to do, even if it means it's a little more verbose (now), and optimize the syntax later?

Desktop : yes
Mobile : No
OS : Microsoft, AIX, Sun, Redhat

Not saying this should be the precise syntax, more pointing out this is how I think.  Currently, I want to write some software that runs on Windows and Linux Servers.  What does dotnet5.4 and net46 have to do with it (and how would I even know these terms exist)?  And why do we think introducing "netstandard" in rc2 will help anything?

I get there will be growing pains.  But we are early adopters eager to work through things so when enough of us are saying it's a bit confusing, there is probably some merit there.

**Comment by mattnischan** [comment]
I'm a bit confused.

`netstandard1.0` claims to support the most platforms, but fewest APIs. `netstandard1.4` claims to support the fewest platforms, but with the most APIs. I don't see how that can be the case; DNX Core has by far the smallest API surface of all of those that came before it.

**Comment by pootow** [comment]
@mattnischan I think your understanding is right, but as [this](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md) states, platform API surface and "standard library" isn't the same. DNX Core's standard library is far less than net45.

**Comment by davidfowl** [comment]
@pootow is correct.

> netstandard1.0 claims to support the most platforms, but fewest APIs. netstandard1.4 claims to support the fewest platforms, but with the most APIs. I don't see how that can be the case; DNX Core has by far the smallest API surface of all of those that came before it.

It's not based on the .NET Framework API. It's based on the standard platform surface area

**Comment by marcogrcr** [comment]
@davidfowl: After reading the [standard-platform.md](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md) document and watching [this video](https://channel9.msdn.com/Events/ASPNET-Events/ASPNET-Fall-Sessions/Class-Libraries), there's something that I still don't understand. Assume the following scenario:

**/global.json**
```json
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-rc1-update1"
  }
}
```

**/src/DotNet54Package/package.json**
```json
{
  "frameworks": {
    "dotnet5.4": {
      "dependencies": {
        "System.Runtime": "4.0.21-beta-23516"
      }
    }
  }
}
```
**/src/Net46Package/package.json**
```json
{
  "frameworks": {
    "net46": { }
  }
}
```

**/src/PackageWithDeps/package.json**
```json
{
  "dependencies": {
    "DotNet54Package": "1.0.0-*",
    "Net46Package": "1.0.0-*"
  },
  "frameworks": {
    "net46": { }
  }
}
```

**> dnu restore**
```
Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-16231

  CACHE https://api.nuget.org/v3/index.json
Restoring packages for C:\Test\src\DotNet54Package\project.json
Writing lock file C:\Test\src\DotNet54Package\project.lock.json
Restore complete, 180ms elapsed
Restoring packages for C:\Test\src\Net46Package\project.json
Writing lock file C:\Test\src\Net46Package\project.lock.json
Restore complete, 2ms elapsed
Restoring packages for C:\Test\src\PackageWithDeps\project.json
Writing lock file C:\Test\src\PackageWithDeps\project.lock.json
Restore complete, 9ms elapsed
Total time 280ms

NuGet Config files used:
    C:\Users\<user>\AppData\Roaming\NuGet\nuget.config

Feeds used:
    https://api.nuget.org/v3-flatcontainer/
```

**> dnx build src\DotNet54Package**
```
Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-16231


Building DotNet54Package for .NETPlatform,Version=v5.4
  Using Project dependency DotNet54Package 1.0.0
    Source: C:\Test\src\DotNet54Package\project.json

  Using Package dependency System.Runtime 4.0.21-beta-23516
    Source: C:\Users\<user>\.dnx\packages\System.Runtime\4.0.21-beta-23516
    File: ref\dotnet5.4\System.Runtime.dll


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.2261272
Total build time elapsed: 00:00:00.2302128
Total projects built: 1
```

**> dnu build src\Net46Package**
```
Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-16231


Building Net46Package for .NETFramework,Version=v4.6
  Using Project dependency Net46Package 1.0.0
    Source: C:\Test\src\Net46Package\project.json

  Using Assembly dependency fx/mscorlib 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\mscorlib.dll

  Using Assembly dependency fx/System 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.dll

  Using Assembly dependency fx/System.Core 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.Core.dll

  Using Assembly dependency fx/Microsoft.CSharp 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Microsoft.CSharp.dll


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.2507674
Total build time elapsed: 00:00:00.2549392
Total projects built: 1
```

**> dnu build src\PackageWithDeps**
```
Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-16231


Building PackageWithDeps for .NETFramework,Version=v4.6
  Using Project dependency PackageWithDeps 1.0.0
    Source: C:\Test\src\PackageWithDeps\project.json

  Using Project dependency DotNet54Package 1.0.0
    Source: C:\Test\src\DotNet54Package\project.json

  Using Project dependency Net46Package 1.0.0
    Source: C:\Test\src\Net46Package\project.json

  Using Package dependency System.Runtime 4.0.21-beta-23516
    Source: C:\Users\<user>\.dnx\packages\System.Runtime\4.0.21-beta-23516
    File: ref\dotnet5.4\System.Runtime.dll

  Using Assembly dependency fx/mscorlib 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\mscorlib.dll

  Using Assembly dependency fx/System 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.dll

  Using Assembly dependency fx/System.Core 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.Core.dll

  Using Assembly dependency fx/Microsoft.CSharp 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Microsoft.CSharp.dll

ApplyProjectInfo.cs(1,29): .NETFramework,Version=v4.6 error CS0433: The type 'AssemblyFileVersionAttribute' exists in both 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System.Runtime, Version=4.0.21.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
ApplyProjectInfo.cs(2,29): .NETFramework,Version=v4.6 error CS0433: The type 'AssemblyVersionAttribute' exists in both 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System.Runtime, Version=4.0.21.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
ApplyProjectInfo.cs(3,29): .NETFramework,Version=v4.6 error CS0433: The type 'AssemblyInformationalVersionAttribute' exists in both 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System.Runtime, Version=4.0.21.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
ApplyProjectInfo.cs(1,58): .NETFramework,Version=v4.6 error CS0518: Predefined type 'System.String' is not defined or imported
ApplyProjectInfo.cs(2,54): .NETFramework,Version=v4.6 error CS0518: Predefined type 'System.String' is not defined or imported
ApplyProjectInfo.cs(3,67): .NETFramework,Version=v4.6 error CS0518: Predefined type 'System.String' is not defined or imported
error CS0518: Predefined type 'System.Void' is not defined or imported
error CS0518: Predefined type 'System.Void' is not defined or imported
error CS0518: Predefined type 'System.Boolean' is not defined or imported
warning CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.
warning CS1685: The predefined type 'CompilationRelaxationsAttribute' is defined in multiple assemblies in the global alias; using definition from 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
warning CS1685: The predefined type 'RuntimeCompatibilityAttribute' is defined in multiple assemblies in the global alias; using definition from 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Build failed.
    3 Warning(s)
    9 Error(s)

Time elapsed 00:00:00.2299112
Total build time elapsed: 00:00:00.2382183
Total projects built: 1
```

If I modify the **/src/DotNet54Package/package.json** file as follows, the compilation errors go away:
```json
{
  "frameworks": {
    "dotnet5.4": {
      "dependencies": {
        "System.Runtime": "4.0.21-beta-23516"
      }
    },
    "net46": { }
  }
}
```

I thought the whole point of having the `dotnet5.4` (or `netstandard1.3` in future versions) was to create a truly portable library without having to multi-target. Is there a problem with the tooling, or what am I missing?
