### ISSUE TITLE
Error referencing local library on another path

### ISSUE THREAD

**Issue by ThomasHoest** [aspnet/Home#1058]
I have a setup that looks like this

ServiceA\src\aspnetproject
ServiceB\src\aspnetproject
SharedComponents\src\sharedcomponent

Each service has it's own solution file that also includes some of the shared components. The shared components are classic .Net assemblies. The wrap project.json files are located in SharedComponents\src\wrap\sharedcomponent. I can add the reference to the sharedcomponent from the aspnetproject without issues, but using it fails to build. This works fine when the projects are all in the same folder. Any ideas?

**Comment by Quantumplation** [comment]
I believe I am experiencing the same issue, and was able to narrow it down some.  In my case, the auto-generated wrap project.json files were looking for the the assembly in "..\..\Shared\obj\Debug\xyz.dll" rather than "..\..\Shared\bin\Debug\xyz.dll".  once I corrected it, it built correctly.  However, occasionally it will regenerate the wrap files and use the obj folder again.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
