### ISSUE TITLE
Windows10 IoT core - DNX

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Home#1065]
PowerShell script fails to work when running on a Raspberry PI Windows10 Core IoT

**Comment by muratg** [comment]
Which powershell script? DNVM?

**Comment by grahamehorner** [comment]
@muratg Yes, the DVNM install script shown on the aspnet/home fails; it's my understanding this should work for Windows10 IoT core on the RaspberryPI allowing the installation of the CoreCLR for arm processors ?

PS C:\Windows\system32> Set-Item WSMan:\localhost\Client\TrustedHosts -Value "minwinpc"

PS C:\Windows\system32>   Enter-PSSession -ComputerName minwinpc -Credential minwinpc\Administrator


[minwinpc]: PS C:\Data\Users\Administrator\Documents> &{$Branch='dev';$wc=New-Object System.Net.WebClient;$wc.Proxy=[System.Net.WebRequest]::DefaultWebProxy;$wc.Proxy.Credentials=[System.Net.CredentialCache]::DefaultNetworkCredentials;Invoke-Expression ($wc.DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}

New-Object : Cannot find type [System.Net.WebClient]: verify that the assembly 
containing this type is loaded.
At line:1 char:21
+ &{$Branch='dev';$wc=New-Object System.Net.WebClient;$wc.Proxy=[System ...
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentExcepti 
   on
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewOb 
   jectCommand
 
The property 'Proxy' cannot be found on this object. Verify that the property 
exists and can be set.
At line:1 char:53
+ ... t.WebClient;$wc.Proxy=[System.Net.WebRequest]::DefaultWebProxy;$wc.Pr ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
The property 'Credentials' cannot be found on this object. Verify that the 
property exists and can be set.
At line:1 char:104
+ ... ultWebProxy;$wc.Proxy.Credentials=[System.Net.CredentialCache]::Defau ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
You cannot call a method on a null-valued expression.
At line:1 char:182
+ ... Credentials;Invoke-Expression ($wc.DownloadString('https://raw.github ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 

[minwinpc]: PS C:\Data\Users\Administrator\Documents>

**Comment by sandersaares** [comment]
Confirm same issue on Windows Nano Server 2016 Preview.

**Comment by matizk144** [comment]
Hi. I resolved problem manually coping downloaded runtime (dnx-coreclr-win-arm.1.0.0-rc2-16177) from desktop to Windows IOT (in my situation to RP2) to path:
\\10.0.1.61\c$\Users\Administrator\.dnx\runtimes.
Additionaly if you want to restore packages (also build, publish) on iot, you must download missing clrcompression.dll. Unfortunatelly you must use full path to dnx, becuase you haven't installed path to environemnt variable PATH.

I know, this's temp fix :)

**Comment by grahamehorner** [comment]
Thanks for your comment @matizk144 I can confirm a manual download works, and the issue is with the PowerShell scripts for install dnvm and the dnvm itself. These scripts look to be using features not available in Windows10 IoT

**Comment by muratg** [comment]
@victorhurdugaci any ideas if this should work without the workaround?

**Comment by victorhurdugaci** [comment]
We don't have official guidelines for running on these limited systems (Nano, IoT, etc.) but I don't recommend doing the full development acquisition on the device. You should use the device just a server and not compile on it.

For the best experience, I recommend building & publishing locally and then just copying the publish output to Nano/IoT:

```
dnu publish --runtime active --no-source
```

That will produce a package that contains the app, its dependecies, and the runtime.

The pros for doing this:

1. No Powershell dependency
2. No compilation (this is important for small devices because they are not very powerful)
3. No need for internet/network access to get dependencies
4. (related to 2) Fast startup
5. Consistent results - if the published app runs locally, it should run on the device too because all dependencies are self-contained

**Comment by grahamehorner** [comment]
This us inconsistent with the same hardware running Ubuntu, performance is reasonable and we are able to install the coreclr as directed. 

Please review and/or address the window10 iot/nano server storey

**Comment by muratg** [comment]
@grahamehorner Where's the directions to install it on CoreCLR? I assume you're not installing dnx with it.

Also, what's the perf difference?

**Comment by grahamehorner** [comment]
@muratg I followed instructions to install dnx on Ubuntu on the Raspberry PI copied over a kestrel website and did a package restore and ran the site, I've not compared performance but I personally didn't think performance was too bad. This was demonstrated by the team in Oslo i believe.  I understand you wouldn't do this for production but the storey seems inconsistent across the windows platforms namely nanoserver and windows 10 iot

**Comment by sandersaares** [comment]
Until this discussion, I did not even realize there was a difference between a development install and a runtime install - perhaps the Getting Started documentation should emphasize that it is meant for development, not for the actual published environment.

I mean, Developing on Windows Nano Server is not of interest to me but because the "Getting Started" instructions failed to even work on Nano Server, I assumed ASP.NET 5 and .NET Core do not even work on Nano Server. I take it this is not true - the instructions should then really state what the setup of a runtime environment is.

**Comment by muratg** [comment]
@sandersaares There's not an official distinction between development and runtime installation currently. However, as we get closer to V1, we hope to have better documentation in this area.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
