### ISSUE TITLE
Environment Variables have multiple places to set and do not always sync

### ISSUE THREAD

**Issue by TJSoftware** [aspnet/Home#1071]
### Description

I am attempting to use the environment variables in the project properties.  When I change a key or value the launchSettings.json is updated and visa versa from .json to properties.  I first noticed that I did not have the ability to delete a profile in the properties, the delete button is disabled (see screenshot).  I removed the profile from the json file, but the profile remained in the properties.  

I also tried to run IIS vs DNX.  With IIS I was able to update the properties/json settings and the page displayed `Hello DEBUG CODE!` or `Hello LIVE CODE!` appropriately.  However, when I ran from the command line `dnx web` I was always in `Production`.  When running web via Visual Studio I saw the correct results.  In the command line I can execute `set ASPNET_ENV=Development` and the command line is correctly running the development code. The problem with this is it does not update the launchSettings.json or the project properties.

### What I Expect

If I modify the ASPNET_ENV in any one of the three (Project Properties, Command line, launchSettings.json) that the other two are correctly synced. 

## Code
https://github.com/TJSoftware/CompilationSymbolTesting

            if (env.IsDevelopment()){
                app.Run(async (context) =>
                {
                    await context.Response.WriteAsync("Hello DEBUG CODE!");
                });
            }
            else
            {
                app.Run(async (context) =>
                {
                    await context.Response.WriteAsync("Hello LIVE CODE!");
                });
            }

### Screenshot
![image](https://cloud.githubusercontent.com/assets/4823412/11129564/3ed693d6-893d-11e5-9222-bafa49790506.png)

### Tech Details
.NET Version Manager v1.0.0-rc2-15539

```
Active Version     Runtime Architecture OperatingSystem Alias
------ -------     ------- ------------ --------------- -----
  *    1.0.0-beta8 clr     x86          win             default
```

**Comment by Eilon** [comment]
@barrytang ?

**Comment by barrytang** [comment]
@phenning?

**Comment by TJSoftware** [comment]
### Updates
Update on the delete profile.  If I create a new profile I am allowed to delete that.  The `IIS Express` and `web` are not allowed to be deleted.  I would guess this is designed functionality.  I still see the issue of the environment variables not syncing.

### More examples
I may be misunderstanding the environment variables in the system as being the same as the environment variables that are in VS and the console, but when I set the global system variables (see screenshot 1 below) the Visual Studio settings are used.  I.E. I have the system variable set to `Production` and both `IIS Express` and `web` in Visual Studio set do `Development` and my response is `Hello DEBUG CODE!`.  However, without changing any settings and running web from the console my response is `Hello LIVE CODE!`.

For screenshot 3 below I have two sessions that I compared in the command line.  In the first I executed `set ASPNET_ENV=Development` in the command prompt to set the local session environment for circle 1.  For circle 2 I just ran `dnx web`.  You will notice in circle 3 that my system variable is currently set to `TJProdTest`.

Thanks for looking into this an passing it on to others for more research.

### Screenshot 1
![image](https://cloud.githubusercontent.com/assets/4823412/11215973/09fc3b1c-8d06-11e5-8e24-ee65d109a000.png)

### Screenshot 2
![image](https://cloud.githubusercontent.com/assets/4823412/11216155/02d122e8-8d07-11e5-852d-8fc57a5cd356.png)

### Screenshot 3
![image](https://cloud.githubusercontent.com/assets/4823412/11216483/a13d2a16-8d08-11e5-87bd-3f06aee0ee6c.png)

**Comment by phenning** [comment]
Thanks for the feedback!

In regards to the deleting of the IIS Express and web profiles, the reason you cannot delete those is because any project with a "web" command gets those two built-in profiles by default and built-in profiles cannot be deleted.

As to the environment issues:

The environment settings in the project property page are stored into launchSettings.json, however if you have the property page window open and edit lauchSettings.json directly, the changes are not reflected in the property page UI until you close and reopen the property page window. This is a known issue.

When launching the process from within VS, the launchSettings/Property environment variables will be passed to the process. If they are not specified, the system/user variables will be used.

When launching directly from the command line, only the system/user variables are used, as launchSettings.json is strictly a VS concept.

While testing your scenarios, I did observe some peculiarities though when setting environment variables through the Windows UI. It appears as though you need to actually click OK on the window after setting your environment variable in order for future processes to have the environment variable applied. I'm suspect this is what happened in your last case, as initially I was able to repro this as you did, but when I clicked OK and launched a new command window, the hosting environment was reported correctly.

**Comment by TJSoftware** [comment]
@phenning Thank you for taking the time to look at what I was not understanding.  Yes you are correct that I needed a second OK button click with the environment variables.  With Visual Studio, if I remove the environment variable from the profile, it does use the OS environment variable.  If I change the OS environment variable I must close Visual Studio and reopen it to see the changes.  My assumption was that stopping and starting the debugger was enough.  The same goes for the console, on change of an environment variable the change is not picked up till the console is closed and reopened.  I think the key to all of this was that second button click though, nothing was being picked up till the environment variable was properly set.
