### ISSUE TITLE
Add contributing.md to the Announcements repository

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Home#1086]
ref: https://github.com/aspnet/Announcements/pull/114#issuecomment-157780022

I think the contributing.md is exactly for this. Every time someone create a new issue GitHub will show a label on top and suggest to read the guideline. This may help prevent some issues being open there.

![image](https://cloud.githubusercontent.com/assets/3386797/11248139/4fe1f98e-8dfe-11e5-9aa9-cd1c46586d35.png)

**Comment by Eilon** [comment]
Good idea, added one: https://github.com/aspnet/Announcements/blob/master/CONTRIBUTING.md

**Comment by mikehaas763** [comment]
@Bartmax I had the same thought but I think a mention is *also* needed in the README and is more important to get the point across than a contributing.md file simply because people who are already in that much of a hurry to open an issue are already the ones who are not going to click that link. Still a good idea to have contributing.md too.
