### ISSUE TITLE
RC1 Update 1 release notes?

### ISSUE THREAD

**Issue by sebrojas14** [aspnet/Home#1151]

**Comment by Eilon** [comment]
@danroth27 ?

**Comment by RehanSaeed** [comment]
I think he means that it would be nice if an announcement was made about RC1-Update 1 and what it fixed.

**Comment by danroth27** [comment]
We did publish a note in the RC1 announcement blog post here: http://blogs.msdn.com/b/webdev/archive/2015/11/18/announcing-asp-net-5-release-candidate-1.aspx

**Comment by joeaudette** [comment]
I think at minimum the https://get.asp.net/ site should indicate rc1 update1 or maybe show a release date because for people like me who updated to rc1 when it first came out, there was no indication anywhere that the update1 was available. I knew it was coming from watching community standup and I found out it was available from someone on jabbr, but even now there is nothing on the get asp site to indicate that anything changed.

**Comment by GuardRex** [comment]
I can sort of second that ... I actually only heard about it b/c @davidfowl told someone in an issue to go get it. It had been out a week at that point.

**Comment by Eilon** [comment]
@DamianEdwards @shirhatti regarding get.asp.net comment: https://github.com/aspnet/Home/issues/1151#issuecomment-162064799
