### ISSUE TITLE
Subdomains 502.3

### ISSUE THREAD

**Issue by jbomhold3** [aspnet/Home#1154]
If this is answered else where I'm sorry I can't fine it.  Running just templated web app from VS2015. produces httpPlatformHandler  0x8007010b error on http://rpgen.xaltech.com/ however same code running on http://xaltech.com/ works just fine. IIS is configured the same way for both sites. One works with zero issues the other does not even try to fire guessing based on no output to the log files. There a work around for this something I forgot to figure maybe?

**Comment by GuardRex** [comment]
@jbomhold3 There are no known issues for subdomain problems with the HttpPlatformHandler and IIS. What do you have in your `web` command in `project.json`?

**Comment by GuardRex** [comment]
@jbomhold3 I'm crashing but back online ~7am-10am PST and after 3pm PST. If you don't get help, I'll see if I can work through it with you. Make sure your `web` command is ...
```
"web":  "Microsoft.AspNet.Server.Kestrel"
```
Since you're seeing a ref to HttpPlatformHandler with the exception (where are you seeing that? Event Viewer - Application?), we can guess that the IIS Basic settings path is correct and that it's finding `web.config` and that the binding you set is ok.

That error code seems to be associated with a bad directory reference. Make sure those two website folder structures are idential. You might try pointing the IIS Basic Settings path for the subdomain app to the folder containing the working non-subdomain app ... if it springs to life on the subdomain at that point, then you know you have a bad project folder/file structure or something like that.

**Comment by jbomhold3** [comment]
I'll try and brake it again it to see exactly what it was. However, thanks Rex. Re-pointed the subdomain to the working folder and worked. Went back to old was broken. Deleted the folder, made a direct copy of the working folder works on both now. About the only thing I can tell different in directory structure was the permissions where inheartered for the approot folder on the working and local for the broken.

**Comment by GuardRex** [comment]
Cool. Glad you got it running. Permissions might make sense in light of
that error code.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
