### ISSUE TITLE
kpm fails to download nuget packages

### ISSUE THREAD

**Issue by makzr** [aspnet/Home#117]
Hi,

I'm on OS X Yosemite, Mono 3.6 and KRE 1.0.0-alpha4-10249 and kpm fails to download the nuget packages of the sample projects.

I searched for the missing packages on nuget.org and I could not find them. Looks like these packages are no longer available?

This is my console output:

~/Workspaces/HelloWeb> kpm restore
Restoring packages for /Users/markus/Workspaces/HelloWeb/project.json
Attempting to resolve dependency HelloWeb >= 1.0.0-SNAPSHOT
Attempting to resolve dependency Kestrel >= 1.0.0
Attempting to resolve dependency Microsoft.AspNet.Diagnostics >= 1.0.0
Attempting to resolve dependency Microsoft.AspNet.Hosting >= 1.0.0
Attempting to resolve dependency Microsoft.AspNet.Server.WebListener >= 1.0.0
Attempting to resolve dependency Microsoft.AspNet.StaticFiles >= 1.0.0
Attempting to resolve dependency mscorlib >= 
Attempting to resolve dependency System >= 
Attempting to resolve dependency System.Core >= 
Attempting to resolve dependency Microsoft.CSharp >= 
Attempting to resolve dependency HelloWeb >= 1.0.0-SNAPSHOT
Attempting to resolve dependency Kestrel >= 1.0.0
Attempting to resolve dependency Microsoft.AspNet.Diagnostics >= 1.0.0
Attempting to resolve dependency Microsoft.AspNet.Hosting >= 1.0.0
Attempting to resolve dependency Microsoft.AspNet.Server.WebListener >= 1.0.0
Attempting to resolve dependency Microsoft.AspNet.StaticFiles >= 1.0.0
Resolving complete, 3314ms elapsed
Unable to locate Microsoft.AspNet.Diagnostics >= 1.0.0
Unable to locate Microsoft.AspNet.Server.WebListener >= 1.0.0
Unable to locate Microsoft.AspNet.StaticFiles >= 1.0.0
Unable to locate Kestrel >= 1.0.0
Unable to locate Microsoft.AspNet.Hosting >= 1.0.0
Restore complete, 3318ms elapsed

**Comment by ozmartian** [comment]
worst documenttion ever.. the missing link is, as has beed discussed, the NuGet.Config file. MAKE SURE THE CASING MATCHES EXACTLY WHAT I TYPED. Naturally, the casing is wrong in the instructions and no one seems to care to update them. C'mon guys! Shouldn't this be mentioned as part of the damn steps? Without being on the repo's dev branch and having NuGet configured you'll end up wasting a day swearing at the top of my lungs because I missed the second paragraph of the intro, having dived straight into the ordered bulletted list of steps.. sheesh! 

In addition, be more clear when saying where said NuGet config file should be placed. It resides in your project's root NOT the web root. Like where your usual solution (.sln) file lives in a standard MVC project relative to your webroot.

**Comment by tenowg** [comment]
@ozmartian First I shall apologize because I know this post is going to be taken the wrong way, and most likely completely out of context. But if you have figured out the problem, and can see a nice fix (as in, documentation) make a PR and attempt to fix it, this is an open source project, open source project appreciate fixes, actually expects them. Worst that can happen, it is rejected, but the discussion will start.
