### ISSUE TITLE
[Question] Why use DropColumn instead of sp_RENAME?

### ISSUE THREAD

**Issue by Eaglef90** [aspnet/Home#1237]
Firstly I am sorry if this should have been posted directly in the Entity Framework repo, the contributions guidelines stated discussions should go here.

When using Entity Framework 7 against a Microsoft SQL 2008 R2 database I noticed that it is calling a DropColumn/AddColumn set when a column is renamed in an Entity instead of invoking sp_RENAME to prevent data loss. I was wondering what the reasoning for this was?

**Comment by joeaudette** [comment]
Do you mean you renamed a property on a model and the migrations dropped the old column and added a new one instead of renaming?
How could EF possibly know your intentions, it just sees a property that was there disappeared and a new property now exists. It has no way to know you intend it as the same property with a new name. From its point of view the model lost a property and added a property, it cannot know anything more than that. Entities don't have columns they only have properties that get mapped to columns.

**Comment by Eaglef90** [comment]
Sorry, had not thought of it that way. What brought the question to me was when I dropped the "s" from the property "Verions" so I thought that such a small change would not need a full drop/create but ok.
