### ISSUE TITLE
You do it bad - rename aspnet

### ISSUE THREAD

**Issue by ggrnd0** [aspnet/Home#1245]
rename "aspnet 5" -> "aspnet core 1.0" is very bad idea.
Why "core"? What will be around? Where are a borders?

If you so want to rename focus for "dnx":

 - .net -> dnx
 - .net Portable Profiles -> dnx core
 - aspnet -> dnx mvc
 - ef -> dnx orm/dnx entity/dnx db/dnx data/dnx persistence (your choise)
 - WinForms/WPF -> dnx desktop

other...

if you will use "aspnet core v*" it will be too hard to found issues in internet.

**Comment by simonmurdock** [comment]
dnx has already been renamed - see the dotnet CLI  http://www.hanselman.com/blog/ExploringTheNewNETDotnetCommandLineInterfaceCLI.aspx

**Comment by jerometerry** [comment]
I disagree. While not perfect, asp.net core indicates a separate product than the flagship asp.net product. I like and agree with the rename.

**Comment by davidroth** [comment]
I fully agree that the brand "aspnet" should be retired. Please give it a new fresh name. "Aspnet core 1.0" is super confusing. "Active server pages" is just really a thing from the past, and has nothing positiv associated with it.

Furthermore, think about google, blogs, stackoverflow etc. With asp.net core thing will get very hard to find/tag the new product.

**Comment by jozefizso** [comment]
ASP.NET is a great brand name. Customers and clients recognize this name. They know they can use existing knowledge, developers and admins with ASP.NET.

ASP.NET Core is a really good name as it is fairly easy to explain to both stakeholders and IT guys the new aspects of a newly build ASP.NET from ground up.

**Comment by ggrnd0** [comment]
@jerometerry, i wait that, but have missed =)
Ok, s/dnx/dotnet/ig

@jerometerry, i see "X core" like a subset of "X".
But "Asp.Net MVC" ideologically too far from "Asp.Net" by . 
And "Asp.Net Core" seemingly too far from "Asp.Net MVC".
There is nothing similar between "Asp.Net Core" original "Asp", is not it?

@jozefizso, I am not marketer and do not use this term.
Originally, "Asp" in "Asp.Net" used to populate ".Net". 
Now it is not necessary. 
".Net" (dotnet) and "MVC" are popular.
They can be used independently, without "Asp" reference.
Children grew up...
Please, leave "Asp" intact.

**Comment by jerometerry** [comment]
As Scott and Damian discussed in [yesterdays standup](https://www.youtube.com/watch?v=FSf83_TU5Yg), naming is incredibly hard. It's just not possible to please everyone with the new name. Microsoft doesn't want to ditch the ASP.NET brand, since they are heavily invested in it and it's widely known. I agree with this decision. It would cost too much for Microsoft to rebrand this under a completely new name. And what would ditching the ASP.NET moniker do to Google searches?

At some point they need to make a decision and go with a name, and that decision was ASP.NET Core. I'm sure this decision wasn't made overnight, and involved a lot of different stakeholders. I kind of like it. 

It used to be called ASP.NET vNext, and I don't recall anyone objecting to that name. ASP.NET 5 is also confusing, since it's not just an incremental version of ASP.NET 4, it's a ground up rebuild. 

At the end of the day, it's just a name. I don't think it will cause much confusion at all. I've been following along with the ASP.NET vNext developments so I know the background of the naming. For those new developers who aren't aware of the history, they can easily find this out with a quick Google search. And I'm sure Microsoft will do a good job describing how ASP.NET core is different from the original ASP.NET product. 

Regardless of what it's called, it's really exciting to see this product take shape.

**Comment by ggrnd0** [comment]
@jerometerry, "dotnet" and "mvc" already popular.
Microsoft had much time from 2014! year for create new easy-usable brand without legacy troubles (search, meaning etc).

For example, we already have hyped brand "Roslyn".
I do not hear it before 2014. But it developed from 2011, Oct.
I do not sure it was hard.
You just say "Roslyn - is future, there is github repo".
And birds will tweet it most every day.
In 2015 JetBrain was filled with "Will Re# use Roslyn?" question.

New brand need great money and few time or few money and great time.
Microsoft has both!
~~They can always take a loan from Bill Gates =) ~~

**Comment by brockallen** [comment]
> In 2015 JetBrain was filled with "Will Re# use Roslyn?" question.

The answer is "No". See here: https://vimeo.com/151644168

**Comment by ggrnd0** [comment]
@brockallen, i know.
And i could answer the first. I could answer it before asking a question. ;-)

**Comment by jerometerry** [comment]
@ggrnd0 If you were in Microsoft's position, what name would you choose?

**Comment by ggrnd0** [comment]
> ASP.NET 5 is also confusing, since it's not just an incremental version of ASP.NET 4, it's a ground up rebuild.

Asp.Net is confusing. It is problem.

> At the end of the day, it's just a name.

No, it is the most popular word in my future coding after the ";"-word =)

**Comment by ggrnd0** [comment]
> @ggrnd0 If you were in Microsoft's position, what name would you choose?

- asp is legacy and confusing.
- dotnet/net/.net are too tiny/transparent. 
    But "dotnet" popular brand and attached to c#.
    "dotnet" can be used.
- "Roslyn" is great example of fresh and popular brand.
    But it is allredy assocated compiler for "dotnet".
    I cannot imagine another link between.
- "??????" - much time lost for populate it.

In retrospective, i will use "Roslyn" as platform brand - compiler do not need brand.
And Roslyn.Web(MVC)/Rolsyn.Entity/.... as target names.
But chance is missed =)

**Comment by DamianEdwards** [comment]
We appreciate feedback as always but the name as announced is what we're going with.
