### ISSUE TITLE
How can I specify latest preview version of a package in project.json?

### ISSUE THREAD

**Issue by wangzq** [aspnet/Home#1322]
Currently it is possible to specify '*' as a package's version in project.json, but it will only resolve to latest stable version; for prerelease version it seems I have to explicitly list it, is there a similar nation to indicate that I want to use latest prerelease version?

Thanks

**Comment by davidfowl** [comment]
2 questions:
- What did you actually specify? Show an example of your `project.json`
- How do you know it isn't the latest?

**Comment by wangzq** [comment]
I am generating project.json to build a console application with dependencies on a few nuget packages:

    {
      "dependencies": {
        "EntityFramework": "*",
        "Microsoft.Azure.Management.Resources": "3.4.0-preview"
      },
      "frameworks": { "net45": { } },
      "runtimes": { "win": { } }
    }

In above example, EntityFramework will be resolved with latest stable version as I used `*` for the version; for the `Microsoft.Azure.Management.Resources` which only has pre-release versions, I cannot use `*` here, I have to specify the specific pre-release version.

**Comment by davidfowl** [comment]
```
{
  "dependencies": {
    "EntityFramework": "6.0.0-*",
    "Microsoft.Azure.Management.Resources": "3.4.0-preview"
  },
  "frameworks": { "net45": { } },
  "runtimes": { "win": { } }
}
```

That should work. In general though I would recommend not using a wildcard `*` unless you owned that dependency. Specifying a * on the pre-release tag is more sane :smile:

**Comment by wangzq** [comment]
Yes I agree normally specifying a `*` on a pre-release package is not a good idea; but for temporarily generated project.json which was only used for building an assembly from other source (such as a LinqPad query), it is actually very handy. From your response I guess there is no support for that. I decided to use `nuget.exe list package-id -pre` to find out the latest pre-release version instead. Thanks

**Comment by chandrasekarkesavan** [comment]
On 2016-02-24 15:42, David Fowler wrote: 

> {
> "dependencies": {
> "EntityFramework": "6.0.0-*",
> "Microsoft.Azure.Management.Resources": "3.4.0-preview"
> },
> "frameworks": { "net45": { } },
> "runtimes": { "win": { } }
> }
> 
> That should work. In general though I would recommend not using a wildcard * unless you owned that dependency. Specifying a * on the pre-release tag is more sane 
> 
> --
> Reply to this email directly or view it on GitHub [1].

Thanks 
 

Links:
------
[1] https://github.com/aspnet/Home/issues/1322#issuecomment-188175914

<hr>
<a href="http://gloriatech.com" target="GloriaTech">http://GloriaTech.com</a> - In Christ, We Trust
<hr>
<p>This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to which they are addressed. If you have received this email in error please notify the system manager at postmaster@gloriatech.com. Please note that any ideas, views or opinions presented in this e-mail are solely those of the author and do not necessarily represent those of the company. Even though the company has put in place an effective security system to protect against viruses, the recipient should check this email and any attachments for the presence of viruses. The company will not accept any liability for damages caused by the contents of this email due to virus or any other means.</p>
<hr>
