### ISSUE TITLE
System.TypeloadException

### ISSUE THREAD

**Issue by prasadoct12** [aspnet/Home#1326]
Hi,

I am new in using dnx commands, i tried execute a command, i am getting a following exception
`
C:\Users\prasad.mallappa\Documents\Visual Studio 2015\Projects\TheWorld\src\TheW
orld>dnx ef migrations  add InitialDatabase
System.TypeLoadException: Could not load type 'Microsoft.Extensions.PlatformAbst
ractions.LibraryTypes' from assembly 'Microsoft.Extensions.PlatformAbstractions,
 Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.Data.Entity.Commands.Program.ValidateProject(String targetProjec
t)
   at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass2_7.<Main>b__15()
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(St
ring[] args)
   at Microsoft.Data.Entity.Commands.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly,
 String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b_
_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()`

my project configuration is as below
`{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
    "EntityFramework.Core": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "EntityFramework.Commands": "7.0.0-rc1-final"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel",
    "ef": "EntityFramework.Commands"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ]
}
`

**Comment by davidfowl** [comment]
What version of DNX are you using?

**Comment by prasadoct12** [comment]
I am using the following version
`dnx --version
Microsoft .NET Execution environment
 Version:      1.0.0-rc2-16357
 Type:         Clr
 Architecture: x86
 OS Name:      Windows
 OS Version:   6.3.9600
 Runtime Id:   win81-x86`

**Comment by apoutney** [comment]
Im having a similar issue when trying to reflect types from an assembly that references Microsoft.ServiceFabric.Services.

It throws {"Could not load file or assembly 'Microsoft.ServiceFabric.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. An attempt was made to load a program with an incorrect format."}

Stack trace "   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)\r\n   at System.Reflection.Assembly.LoadFile(String path)\r\n   at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadFile(String assemblyPath)\r\n   at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext loadContext)\r\n   at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.Load(AssemblyName assemblyName)\r\n   at Microsoft.Dnx.Host.LoaderContainer.Load(AssemblyName assemblyName)\r\n   at Microsoft.Dnx.Host.DefaultLoadContext.LoadAssembly(AssemblyName assemblyName)\r\n   at Microsoft.Dnx.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func`2 factory)\r\n   at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadAssemblyImpl(AssemblyName assemblyName)\r\n   at Microsoft.Dnx.Runtime.Loader.LoadContext.ResolveAssembly(Object sender, ResolveEventArgs args)\r\n   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)"

im using version: 1.0.0-rc1-16231 Type: Clr Architecture: x86 OS Name: Windows OS Version: 6.3 Runtime Id: win81-x86

Im not sure if the cause of the issue is with dnx or service fabric, or if its because im trying to get the types from a library that was built in dnx451 from one that is built in net451

Is this something that is just not yet complete in the framework?

**Comment by prasadoct12** [comment]
Anyone got know the solution ?

**Comment by prasadoct12** [comment]
Even if i try to execute dbcontext listing, I am getting the same typeload exception.

![image](https://cloud.githubusercontent.com/assets/17452017/13453419/f910320e-e075-11e5-8ad5-8dec33703eab.png)

**Comment by moozzyk** [comment]
Don't use rc2 runtime with rc1 packages.

**Comment by prasadoct12** [comment]
Yeah after downgrading to rc1 it is working :).
