### ISSUE TITLE
Getting started is a nightmare for new users.

### ISSUE THREAD

**Issue by replete** [aspnet/Home#1328]
FYI: [Breaking changes from RC1 to RC2](https://github.com/aspnet/Announcements/issues?q=label%3AAnnouncement+milestone%3A1.0.0-rc2)

**I _really_ feel like the wider vnext project needs someone to _own_ a global _'Getting started with RC1'_ manual - perhaps on [docs.aspnet.org], that is directed to from all current documentation areas/packages.**

I know a lot is going on with the move to dotnet, but I have literally spent hours and hours and hours trying to make sense of everything. From what I've seen of the milestones, RC2 is months away and therefore this would probably be worthwhile.

It took far too long to understand (as a brand new vnext user as of a week ago) that:
* RC1-final is best to work with right now 
 * because of huge (good) changes across the board undergoing in RC2
 * because RC2 seems months away (which is fine)
* It's easiest to stick with `dnx451` or `dnx46` native frameworks right now
* `AspNetCore.*` dependencies use a new namespace for RC2+, and I should be using `AspNet.*` packages instead
* Packages are managed most easily in Visual Studio via the context menu 'Manage packages'
* Adding the non-standard URL to the package manager in VS was required to get RC2 packages
* Look at code samples in `master` branches are probably for RC2, better to refer to `release*` or `RC1-*` branches
* RC2 packages need a custom package provider setting up
* `dotnet` replaces `dnx, dnvm` etc
* `dotnet` is essential for RC2+
* `dotnet` is not essential for RC1, can use dnx etc at the time (not clear from package repos)
* `dnx46`,`dnx451` are .NET Native frameworks
* `dnxcore50` is RC1* name for .NET Core
* `project.json` schemas documented had slight differences between RC1, RC2
* The official documentation website shows 'vnext' as the default, which seems to be RC2 related.
* Using `dnxcore50` as a framework doesn't seem to work easily because it needs ".NET Native" libraries - how do I make it use these?

I could go on. Instead of _making stuff_, I've been running around in circles. I know vNext is new, but RC1 should be easier to get going with.

**What would clear this up:**
* **Explain how and why RC1 is what most people should use right now**
* **Getting started with RC1**
* **Explain who should use RC2 _nightlies_** (contributors, dark souls players, etc)
* ~~Getting started with RC2~~

If RC2 was ready tomorrow, I wouldn't bother with this post, but it seems months away. Which is fine because the changes are great and clarify _so much_ with this project.

**Comment by simonmurdock** [comment]
It's a waste of time until RC2 is out. I'm not going near it until then

**Comment by replete** [comment]
@simonmurdock  The point of this issue is that _it took me hours and hours of frustrating research_ to even understand that different errors/terminologies/documentation/syntaxes were all down to big changes in RC2. 

I was very close to giving up completely until I had a small breakthrough.

The current state of affairs is confusing for new users and therefore damaging to the project's goals. I think this issue needs to be escalated.

**Comment by MaximRouiller** [comment]
I agree. Not everything is well documented yet but for me it's ok.

This is just my opinion but... it's still a release candidate. Either they spend a ton of time on documentation for things that are going to change and by the time RC2 comes throw 20-50% of the documentation out anyway.

RC1, as I see it, is for those who want to get the new toys before everybody else. You aren't getting a packaged device. You are essentially getting an IKEA package of your device. Sometimes there is instructions, sometimes there isn't. If you are left a few screw at the end, it might be normal. 

If you are learning RC1 right now, learn it for the concepts that are going to drive the RC2/RTM in the end. Some things in there aren't going to change. 

* Core is hosted Out-Of-Process. It's not going back inside IIS.
* Middleware is the way your pipeline is built and managed.
* Dependency Injection is the way everything should be built. 
* There will be a command line scenario (whether it's call `dnx` or `dotnet`)
* There's not going to be another `web.config`. Everything is in `.json` files now.
* Things that were Windows-only aren't going to find themselves in .NET Core unless there is a cross-platform alternative and even then... if the team has the time. 

So yeah... I know it's frustrating but it's even more hard for those of us who've been looking at this project since they had `k`, `kre`, etc.

This project has basically been renamed twice.

* Runtime:  K to DNX to `dotnet`. 
* Framework: vNext, ASP.NET 5, ASP.NET Core 1

So here's what I might suggest. 

Stay on RC1 for now. Don't get stuck in the RC2 build. Things will get broken often and what work one day might not work the next. To avoid any moniker (`dnxcore50`, `dnx451`, etc.) confusion, just recreate a project with the updated Web Tooling/yeoman once the new bits are released and copy/ paste over your business code over. There is no upgrade scenarios since we are literally in beta-ish software right now.

If you are looking for what broke, add a watch to aspnet/Announcements and you will be aware of all breaking changes. 

I don't know what else to add. We are not 1.0.0 yet. We are still in pre-release.

**Comment by replete** [comment]
@MaximRouiller I don't think they should spend more time documenting at this point - _just a little time updating signposts with more contextual information regarding the huge/breaking changes with RC2_.

If I found such information, it would have saved me hours.

**Comment by MaximRouiller** [comment]
@simonmurdock And that's ok. Especially if you are not of the adventurous kind. 

I would recommend however to look at the core concepts of the framework. 

Install RC1, get to know what makes this release tick and get to make a simple WebAPI. Add a few packages and understand what's going on.

I've been playing with this project since K. Things are light years ahead of what they were 2 years ago. I've been warning people of the changes. Things will have moved. It's time today to get to know what makes this framework what it is. 

It's a fundamental change. Things will break. If you are not ready yet, it's OK. But please try it out.

It got some wonderful ideas and the team need all the feedback we can give them.

**Comment by replete** [comment]
Also, I want to add this post is not really about _my_ wasted time, rather it's about the typical issues new users face.

**Comment by MaximRouiller** [comment]
For those wondering, here are the [Breaking changes between RC1 -> RC2](https://github.com/aspnet/Announcements/issues?q=label%3AAnnouncement+milestone%3A1.0.0-rc2)

You just have to change the milestones to get more info. :smiley:

**Comment by replete** [comment]
@MaximRouiller Yes I did see that, I updated the OP with its inclusion.

**Comment by nnyegaard** [comment]
I think that the ASP.NET Community stand ups have explained this pretty well. Of course you need to know they exist, but that is the same with any documentation.

With this Pre-release stuff you just have to know that you are gonna use some/alot of time reading and tinkering.

**Comment by mikes-gh** [comment]
In you situation it would make sense to wait for rc2
rc1 unfortunately was a bit premature (especially given it had a go live license) and as you pointed out there are too many breaking changes. rc1 -> rc2 to make it a release candidate.
These are however documented on the announcements repo and at least MS is allowing change in order to get it right in the long run.

**Comment by stgeorge** [comment]
Maybe calling them release candidates in the first place is a bad, RC1 should be beta9 and RC2 should be beta10 and the betas need to continue on for a very long time (minimum one year) so that all the nonsense stuff is shaken out... don't even think about release candidate until it's ACTUALLY a release candidate... it's been way too much misleading and potentially harmful political grandstanding with the way these releases have been named and presented as "almost final" when that's the farthest thing from the truth.

**Comment by MaximRouiller** [comment]
@stgeorge I think it as to do with having a "Go Live" and not being in Beta.

I agree that things are changing way too much for a Release Candidate. But we're there.

Personally, I know a client that is already in production with the RC1 on a SaaS product he is building.

**Comment by mikes-gh** [comment]
BTW my experience is things are working well.  I also have a site I will probably go live on rc2.
Its just things are still changing but most of that is tooling (dotnet-cli) .
The breaking changes do not require much coding effort to fix more than a find and replace.  The main concepts are good to go IMHO.

**Comment by replete** [comment]
Nevermind, I'll write a blog post I think. May as well get involved!

**Comment by MaximRouiller** [comment]
:+1:
