### ISSUE TITLE
Alternative for fluent mapping to inner object properties

### ISSUE THREAD

**Issue by cdie** [aspnet/Home#1330]
Hi,

I'm facing an issue in our desing (see this stackoverflow question : http://stackoverflow.com/questions/35632075/ef-core-fluent-mapping-to-inner-object-properties).

The only solutions that I found are :

1) Create a specific entity objet that inherits from my object and only define simple properties. This will however requires more complexe mapping when retrieved from Db and inserted ... Not the best solution imho
2) Create proxy properties that mask my SubEntity properties. That the solution we choose for now, but it might not be the better ...
3) Insert annotation in our domains models. We prefer avoiding to have DAL related thing into models, so we exclude this.

Is there a solution that we haven't figured out ? 
Is the link functionality for fluent mapping will come one day ?

thanks

**Comment by Eilon** [comment]
@divega @rowanmiller

**Comment by divega** [comment]
My guess is that you are referring to complex types or value objects support (https://github.com/aspnet/EntityFramework/issues/246) a feature we are not planning to include in EF Core 1.0.

I am not sure I understand the workarounds you described well enough to answer your question, but it is generally true that until the feature is supported you'll have to adapt your domain model so that all properties are directly owned by some entity type.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
