### ISSUE TITLE
Roadmap: RC2 and 1.0.0 still TBD

### ISSUE THREAD

**Issue by OlegKi** [aspnet/Home#1333]
About one month before we read [the post](https://blogs.msdn.microsoft.com/webdev/2016/02/01/an-update-on-asp-net-core-and-net-core/) about the problems with the time schedule of ASP.NET Core and about setting TBD in [the Roadmap schedule](https://github.com/aspnet/Home/wiki/Roadmap#schedule) of RC2 and 1.0.0 version.

Is it probably the time to share any new information with the community about the current plans of the ASP.NET Core Team? The most developers, who starting migration to ASP.NET Core, required at least *approximate* information about the current plans about RC2 and the final release.

Thank you in advance!

**Comment by Chrissx** [comment]
Hi,

There is no date yet but ASP.NET team working on integration with the new dotnet CLI system.
You can check live.asp.net last two episode Damian Edwards talks about the date and the reasons behing it.

**Comment by GuardRex** [comment]
@Chrissx He talks about it in the last Standup at 7:07 in the video.

**Comment by OlegKi** [comment]
@GuardRex : Thank you! The information that one will probably report the new date of RC2 in 1-2 weeks (the statement said at 23 Feb) is at lease something. I'm looking forward for a new information.

**Comment by GuardRex** [comment]
They'll probably update the roadmap as soon as they know: https://github.com/aspnet/Home/wiki/Roadmap

**Comment by tuespetre** [comment]
Here's hoping they can announce it today with the dev build being in order!

https://github.com/aspnet/Home/issues/1280

**Comment by Boglen** [comment]
Nope, unfortunately( still quiet

**Comment by janhartmann** [comment]
Can we get an update on the RC2? :-)

**Comment by MaximRouiller** [comment]
@janhartmann your best bet would be to follow their weekly stand-up on YouTube.

**Comment by Eilon** [comment]
@DamianEdwards 

As @MaximRouiller mentioned, there's a LIVE video every Tuesday on YouTube with the team, talking about the latest news and developments. Find out more info at https://live.asp.net/.

**Comment by branciat** [comment]
The corefx team announce an rc2 release for april 08, see [here](https://github.com/dotnet/corefx/milestones).
What do the others projects will follow ?

**Comment by Eilon** [comment]
@branciat those are some dates that the .NET/CoreFX team is trying to hit for themselves, but they do not reflect a commitment to a public release at that date.

**Comment by MaximRouiller** [comment]
I'm 100% behind @DamianEdwards when he said "We'll ship when it's ready". 

I'd rather have something that works well rather than bug-ridden framework.

**Comment by allenmoatallen** [comment]
@branciat looks like the date slipped to April 15th. I did hear in one of the Build 2016 streams RC2 is unofficially being targeted for sometime in April. That can change of course. Looking forward to knowing more specifics in order to get my code inline with proper naming and targeting!

**Comment by rhires** [comment]
I have a number of thoughts about this. First, is there any ongoing "this is what we're up to and these are the challenges we're having" kind of blog or other reportage? If so, where is it? If not, why not? This is supposed to be "open source" software, which means that the development is supposed to be happening in the open, and having insight into the development process is key, second only to have actual code to look at. 

I'm perfectly ok with "ship when it's ready", but the community deserves more than what we got in the standup from April 5 - Q: "Any idea when it will be ready?" A: "Nooooo." Really? Some further explanation would be helpful/useful - "We can't say right now because...and these challenges have led to ... We could use some help with ... "  I know we have the nightly builds, not having an official channel that explains concerns is bad practice, in my opinion. I appreciated the delivering of bad news when it was determined that RC2 would be different in some big ways from RC1, and that it would cause slippage in timelines...but keep that coming! Keep us informed. Having to guess and having developers to keep asking doesn't serve anyone...My 2 cents.

**Comment by lclghst** [comment]
@rhires the weekly LIVE standup is mentioned numerous times in this thread https://live.asp.net/

**Comment by Bartmax** [comment]
@rhires I don't see how the ASPNET team can be more open and how to keep us more informed.
I guess you should watch the community standups, @DamianEdwards takes lots of time and energy in explaining all of why things are delayed, what are the roadblocks and why there's no date and when will be one.

Just a brief summary:
ASP.NET was delayed mainly because of dnx -> dotnet cli.

The last weeks the *big* work was in 2 issues: 
 - teams merging efforts, syncing work (vs tools, dotnet cli, aspnet, azure, etc)
 - the update story post RTM. How packages, versions, etc will be updated.

Date will be announced when @DamianEdwards get his hands in an installer than can get a clean machine, install visual studio, and use it for a couple of hours. (he mentioned porting asp.live.net to rc2 as an exercise). He doesn't mind having problems and/or bugs with *that* build. Before that he doesn't feel confident to provide any date.

There are a lot of **details** on the community standup. I really encourage to see the last 2 or 3 to be up to date on status.

To your other concern: Why there is no blog or kind of reportage?
This was also mentioned in one of the community standups, the team doesn't even have a big board full of items to report on. Also, good thing about community standup is that nothing on there is quite official.
Microsoft do blog post when things gets official and i think that's a good thing.

One more thing, the development is happening on github, not only the source code. Issues, blocks, bugs, almost everything. If you watch the github repos you will have a broader idea of what's going on.
Also there's jabbr where you get to talk with key member of the team and long time community members, they are very active, friendly and open.

I don't think ASP.NET is holding any information at all. If you want to know, you surely can. It may not be delivered front door, but that's not how OSS works.

**Comment by rhires** [comment]
Much praise to @shanselman for his [blog post](http://www.hanselman.com/blog/AnUpdateOnASPNETCore10RC2.aspx). I really appreciate it. I wish I had the time to watch the video standup each week, and so I depend on something like this to get a handle on what's up. It's hard to also piece together the little bits and pieces, so having this kind of overview is helpful. There is some griping in the comments about timelines slipping and such, but generally knowing what's going on (in summary form) helps with that frustration. 

Thank you again, Scott and the rest of the team.

**Comment by OlegKi** [comment]
Finally I can see "mid-May 2016" and "late-June 2016" in the [the schedule of the roadmap](https://github.com/aspnet/Home/wiki/Roadmap#schedule) with the reference to [the blog](https://blogs.msdn.microsoft.com/dotnet/2016/05/06/net-core-rc2-improvements-schedule-and-roadmap/) written by Scott Hunter.

Thanks for the info! Now one can start to make plans of migration to ASP.NET Core 1.0.
