### ISSUE TITLE
asp nginx stuck

### ISSUE THREAD

**Issue by afpro** [aspnet/Home#1344]
nginx simple config with http_proxy_pass
asp host with kestrel
nginx will wait asp forever

solution:
nginx config add
proxy_http_version 1.1;
proxy_set_header Connection "";

**Comment by MaximRouiller** [comment]
What is the question?

**Comment by halter73** [comment]
I'm pretty sure @afpro is psoting the workaround to [this issue](https://github.com/aspnet/KestrelHttpServer/issues/341#issuecomment-158231878) which affects Kestrel 1.0.0-rc1 running behind nginx using proxy_pass. This will be fixed in rc2, but this configuration is still worth keeping since HTTP/1.1 is more efficient than 1.0.

**Comment by MaximRouiller** [comment]
@halter73 Is that the issue where `nginx` try to use HTTP 1.0 instead of 1.1?

**Comment by afpro** [comment]
@MaximRouiller kestrel can't handle "Connection: close" correctly
