### ISSUE TITLE
Improving libraries that support both System.Web/MVC 5 and ASP.Net Core, for both authors and users

### ISSUE THREAD

**Issue by NickCraver** [aspnet/Home#1349]
A somewhat unique problem to the MVC 5 and MVC Core move is the classes didn't move, they were rewritten. Especially in the case of big hitters like `HttpContext`, modules, etc. I'm not here to disagree with the rewrites, they were sorely needed and very well done. This discussion is posted with the hope the community can collectively come up with a clever solution that hasn't been heard yet.

The rewrite itself introduces some issues at the MVC library layer. For authors of existing libs, we can't really drop support for the current MVC 5 release any time soon. It will certainly be used for years to come. So how do we support both Core and Full? The TFMs (target framework monikers) are a non-starter due to MVC supporting `net4X` and `netstandard`. That means if a library targets `net4X`, you can't tell which version you need to use in any current _programmatic_ way.

Currently, as far as I'm aware, the options are:
1. Make 1 heavy package that supports both and brings in all of the MVC Core DLL reference chain even when the library is used on Full CLR.
2. Make 2 packages, one for MVC 5 and one for MVC Core (both independent, with shared `.cs` files and such used in both). 
3. Make 3 packages, one for MVC 5, one for MVC Core, and a third library with shared code (likely not intended for public consumption).

Number 1 may remain the best option, but it has also comes with downsides of a user forced to choose APIs internally, rely on extension methods, or some other differentiating approach. Alternatively, consumers simply see a lot of duplication of APIs. The carrying of `System.Web` isn't a problem per se because those references and APIs would only be in the `net4X` TFM build. However, the sudden inclusion of a ton of Core references isn't itself free either. For example, we've suddenly brought along at least the basics of MVC Core abstractions and `HttpContext` now appears twice in intellisense.

Both 2 and 3 would rely on a naming convention that doesn't exist and isn't enforced (currently). Option 3 is further worse if the third package is not intended for consumption by littering a bit on NuGet. Regardless of either, a new line of additional packages (and possibly renamed current packages) for existing libraries would be needed. I'm afraid this will contribute greatly to user confusion when picking packages for their project. **We're talking about hundreds to thousands of packages here**, depending on how many are still maintained and ported. That's why I believe this merits discussion until exhausting all reasonable options. Packages don't go away, this duplication is something we'll be paying for in both maintenance and confusion for years to come.

Let's take `MiniProfiler` as an example. What would the new package scheme look like in the last 2 cases?

Package 1: `MiniProfiler` (TFMs: `net4X`)
Package 2: `MiniProfiler.AspNetCore` (TFMs: `net4X` and `netstandard`)

Are these clear? Is 1 used by 2? Which do I use? I don't think it's obvious. If I'm not crazy and they aren't clear, do we then rename Package 1 that has existed for some time? MiniProfiler has been "MiniProfiler" for 5 years, do we rename it to something else like `MiniProfiler.Full` or `MiniProfiler.SystemWeb`? Maybe there's a more ideal naming scheme that's not obvious here. The naming approach has its own set of issues. For example: is the suffix version available? Do we unlist the non-suffixed originals? Either way, that likely adds even more confusion.

Let's assume naming isn't in the way, then we have a base (current) and some suffixed version. How do users know that they should look for a suffixed version? Other packages like Dapper, JSON.Net, etc. support everything in a single package. The issues with conflicting classes is somewhat unique to MVC, so consumers won't be used to this concept just because they're familiar with .Net Full vs. Core in general.

Can we better support this some way in the tooling? Or in NuGet itself?

I only have ideas here but tossing them out for discussion:  
- A concept of a related package, e.g. `MiniProfiler.AspNetCore` is "related" to `Microsoft.AspNet.Mvc.Core` in some way. Related packages could boost search results and autocomplete to the top since that's very likely the package you want to use. Alternatively, it could be used in a suggestion somehow. This approach somewhat alleviates the need for any specific suffix convention being necessary (which may be an counter argument, not an argument for).
- TFM support for MVC vs. non-MVC in some way. I honestly can't see how application stack TFMs would work and I don't think the .Net team does either, but maybe someone has a really clever idea for how this can be leveraged.
- The tooling could look at package references/dependencies, e.g. if you're depending on old `HttpContext` vs. new `HttpContext`, you've compiled references to one (or both) and pick (or suggest) the right package based on what the package and the project is referencing (or depending on) in common.
- ...other?

I realize this has likely been discussed many times inside Microsoft, this is run by pretty smart people. Maybe though, the community can come up with a new idea that works. Not doing so will cause us extra package pain for years, on both producer and consumer sides.

Anyone have other options that improve the situation?

**Comment by akamsteeg** [comment]
I thought about this, and your suggestions, but as soon as I started thinking about existing packages with existing installations I just hit a wall. As @NickCraver points out there are countless existing packages with a bazillion installations. I don't think any solution that breaks the upgrade path of those existing installations would acceptable.

So, I would like to see a solution that a) provides a clear upgrade path for existing users and b) is easy to implement so hopefully it becomes a 'standard by convention'. When many packages work in a  certain way, it's likely other maintainers will choose to do the same for their packages. That makes it easier for end users too.

**Comment by MaximRouiller** [comment]
Maybe something like... "if you request a version higher than X, get this package instead"?

I don't know how to verbalise it properly... but it would literally be a link to another package. Maybe you create a nuget of the package that is spec'ed `v2` (major upgrade from `v1`) but rather than installing the package, it *redirects* you to another package.

It might be confusing but it might be a way to upgrade users. You could even spec this *redirect* based on the moniker that they are requesting...

I don't know how everything would work. Just throwing stuff at the wall to see what sticks.

**Comment by davidfowl** [comment]
The problem is that we have completely different products and it's not just MVC, it's EF and ASP.NET Core as a whole. If we didn't call it ASP.NET would you still say that naming is the wrong way to go? To be honest, I don't see any other solution without adding some new features to nuget (which is probably a non starter because the backlog of things is already *huge*).

**Comment by yishaigalatzer** [comment]
I would go with separating the packages completely. These are not the same products, they look alike and named alike, but the code base is indeed different so I would go with the approach of two libs (perhaps with them being just a shim)

**Comment by NickCraver** [comment]
@davidfowl My aversion to naming isn't the approach itself, it's the unlikelyhood of hundreds to thousands of packages all following it correctly and *if they did*...how many end users are saved any confusion? I think some sort of tooling support is the only thing that will improve the situation. I'm not arguing there is time to implement such support, only that it'd be the only improvement of consequence to users and authors.

Hopefully I'm wrong, but I'm betting people referencing `MiniProfiler` for their ASP.Net Core 1.0 MVC application running on `net4X` is going to happen - then they'll scratch their heads and finally find `MiniProfiler.AspNetCore`. This is probably especially true for upgrades. That's just not a good experience. Forget library authors, I'm on that side of the fence and I'd happily accept a little more work here if we can improve the consumer side - that's by far a higher priority, at least in my view.

@yishaigalatzer the question stands: what are their names, and do we have to rename or abandon the old name for one of them? If so, that in itself is a big ask and a confuser in itself. If we *don't* do that though, why would the user even start to look for a core version of any package, until things started breaking on them? That's a bit later in the pipe then we'd all like.

Here's another idea to throw out there: a concept of incompatible packages in NuGet. Where I could take MiniProfiler and say it's incompatible with `<insert base core AspNetCore library here>` with a reason provided. NuGet could present this error (or warning) when trying to install and possibly on restores. For example:
> This MiniProfiler package isn't for ASP.Net Core. Please use MiniProfiler.AspNetCore for ASP.Net Core applications

An approach like this would be generally useful and not application stack or TFM specific. I'm not trying to argue strongly for any of these approaches in particular, just relaying ideas in the hopes maybe they're something new to consider.

**Comment by Bartmax** [comment]
I think we need a recommendation / suggestion on how to approach.
It will be hard for authors to define it's own way, like MiniProfiler.AspNetCore, Humanizer.NetCore, xUnit.SomethingElse ... we can end with a big mess. (we have some already)

As long as there is a guideline authors can follow and consumers can expect, I think we will be *fine*.

Also, I do hope that nuget, some time in the **near** future, doesn't suggest me (or at least tell me) packages for MVC4 when working on net core. (maybe easier to say than done ...)

What are we learning from the early porters? like IdentityServer, xUnit, Glimpse, Humanizer, Azure, Moq, etc ? Are they all currently following a simple/common approach?

If I'm creating a new library (actually I am), should I note it's for aspnet core even it doesn't exist for pre-aspnetcore ?

If I build a collection of taghelpers, or some middleware, may not be necessary, but if it's something else? How does the consumer knows *beforehand* if that library it's the one he's looking for?

I believe strong guidance is key here, and the sooner, the better.

**Comment by onovotny** [comment]
Just to jump in here on behalf of Humanizer, this is a non-issue for us. We support PCL 259 and `dotnet` today. We will update to `netstandard1.x` as appropriate shortly. We do not care about which runtime we run on. This really seems to affect people that specifically have MVC dependencies that go beyond what's in `NETStandard.Library`.

**Comment by aggieben** [comment]
> I believe strong guidance is key here, and the sooner, the better. (@Bartmax)

> a concept of incompatible packages in NuGet (@NickCraver)

I second both of these things.

**Comment by johnbraden** [comment]
@NickCraver @davidfowl 

@onovotny I appreciate your work very much, but it's not constructive to say this is a non-issue because you do not need it. If you rely on an HTTP context in your library it is an issue. 

Our library needs some data from the context and also needs to set some response values. We do not need any fancy stuff, just a simple ASP.NET HTTP context. Ok, we can tell the developer: Provide all data we need as simple types during initialization. And when the library finishes the developer has to create the response himself? Cache, headers, body, HTTP status code, etc.? This is not really developer friendly unless we are developing for Linux. 
How many developers do you think know how Cache-Control work and how to get/set it correctly, what CORS is, what an ORIGIN header means, how authorization headers are used and so on. Our library accepts an HTTP context as input for initialization and creates the response object, that's all. Internally, it is decoupled from the HTTP context. And yes, we also accept simple types.

###### Possible solutions:: 
1. Let the library authors develop an additional package. In my opinion a no-go.
2. Define additional "sub-monikers" (Sub-TFM). Don't know if Asp.NET/NuGet is willing to do this..
3. Let the package author define a custom moniker (maybe based on recommendations).

###### Example:
The following is an example package definition with a custom moniker defined in the package ("CustomWeb"), a pre-defined 'official' sub-moniker ("AspNetCore") and 
a dependency where no additional moniker is defined (default). The custom moniker includes a message for developers which maybe presented to the developer. A nuspec file may look like this:
<pre>
&lt;package&gt;
    [...]
    &lt;-- Define custom moniker --&gt;
    &lt;define symbol="CustomWeb" message="Use this for Custom.Web based apps." /&gt;
    &lt;-- Own dependencies --&gt;
     &lt;group targetFramework=".NETFramework4.5.1"&gt;
	    // Packages with no pre-defined or custom moniker
    &lt;/group&gt;    
    &lt; group targetFramework=".NETFramework4.5.1" symbol="CustomWeb"&gt;
	    // Packages for the "SystemWeb" custom moniker
    &lt;/group&gt;    
    &lt;group targetFramework=".NETFramework4.5.1" symbol="AspNetCore"&gt;
 	    // Packages for the "AspNetCore" pre-defined moniker
   &lt;/group&gt;    
   [...]
   &lt;Files&gt;
       &lt;file src="lib\net451\Backload.dll" target="lib\net451\Backload.dll" /&gt;
       &lt;file src="lib\net451\CustomWeb\Backload.dll" target="lib\net451\CustomWeb\Backload.dll" /&gt;
       &lt;file src="lib\net451\AspNetCore\Backload.dll" target="lib\net451\AspNetCore\Backload.dll" /&gt;
   &lt;/Files&gt;
&lt;packages&gt;
</pre>
If a developer imports this package into a .NET4.5.1 project there are 3 possible cases:
1. Default: The application references the libraries with no additional moniker set
2. Pre-defined moniker: ASP.NET/Nuget provides a sub-moniker. Looking at the package above, if the project is a ASP.NET Core project the library with the pre-defined AspNetCore moniker is used.
3. The package developer has defined a custom moniker. When the application also defines to use this moniker the library in the custom moniker path is used. Since the custom moniker also defines a message, this can be presented to the developer before importing the package or the NuGet package manager provides a list of choices if there are conflicts.

###### Content files:
The content files in the package (additional files like views) also need such a flag. For example, in traditional projects we may have a HTTP handler (ashx) included in a NuGet package in ASP.NET Core projects we do the same with a middleware which can be in the main library and does not need additional files.

**Comment by davidfowl** [comment]
This should be moved to nuget. Our recommendation is to split up your packages (.AspNetCore suffix for e.g.) as there's no way to pivot on anything except for target framework (and that's the wrong pivot here).
