### ISSUE TITLE
Which packages work correctly?

### ISSUE THREAD

**Issue by Radzhab** [aspnet/Home#1362]
I find rc, beta, final packages. Which package have best stability and work with other packages without error?

**Comment by GuardRex** [comment]
@Radzhab The last release under DNX should be the most stable: `rc1-final` packages with `rc1-update1` runtimes. However, keep in mind that that's all DNX-based and a great deal has changed along the way with the in-progress RC2 bits (release TBD).

IMO stability with RC2 has been good all things considered. There have been periods where I needed to freeze my package versions in my apps and hold steady with a `dotnet cli` version, but it's only happened twice recently for about a week each time. Otherwise, I've been productive with RC2 bits on the CI feed ... well ... my laptop had some smoke coming out of it a few times :smile: ... but yeah ... I'm good.

**Comment by Eilon** [comment]
Yeah, pretty much what @GuardRex said :smile: Using rc1-final is certainly the safest, and has good support in Visual Studio. With RC2 it's a bit trickier, and even though the NuGet packages are in decent shape, there isn't yet good public Visual Studio support for it.
