### ISSUE TITLE
Branch strategy dev->release->master

### ISSUE THREAD

**Issue by veccsolutions** [aspnet/Home#1366]
Hi, we're reviewing our branching strategy and attempting to more closely match the way the aspnet process is. I found your branch strategy section in the Engineering guidelines wiki page and it actually looks pretty close as to how we currently do ours.

I have a couple of questions though, would the QA team test what is pushed up to the release branch or the master branch. And if the master branch, how would you handle doing hot fixes for production? In the limited information on the strategy used in aspnet I'm assuming that any QA/testing is done on the release branch and master would always match what is actually finalized and deployed out to production.

**Comment by Eilon** [comment]
The ASP.NET / EF team has what we call a "combined engineering" team, which means we're all "engineers" - there is no developer/QA separation. Every engineer has both dev and QA responsibilities.

For reference, [this is the wiki section about branches](https://github.com/aspnet/Home/wiki/Engineering-guidelines#branch-strategy).

We do testing in the `dev` branch on a daily basis (that is, unit tests and functional tests are run on it).

When a release is stabilizing, we do that same work in the `release` branch. We also do manual end-to-end verification, have people try features out more extensively, etc. Automated tests are added as necessary.

The `master` branch is generally untested, aside from making sure that it builds. The `master` branch generally serves as nothing more than a snapshot of the last release.

If a quick fix after a release has to go out (and it's happened before with the [`rc1-update1` release for DNX](https://www.nuget.org/packages/dnx-coreclr-win-x86/1.0.0-rc1-update1)), we will generally do the fix in `release`, run our tests on it, and then update `master` to point to that.

It's worth noting that as a library/SDK, we don't exactly have the concept of "for production" because it's not a site/service. As such, some processes that work for a library/SDK might not be the best choice for a live site.

**Comment by miguellira** [comment]
@veccsolutions This [post](http://nvie.com/posts/a-successful-git-branching-model/) and it's accompanying image has always been helpful. Your mileage my vary based on team size, skill level, motivation, etc.

**Comment by veccsolutions** [comment]
Thanks @Eilon  and @miguellira. That helps a lot. We have sites, services and NuGet only libraries so both processes apply in our situation. We have been mostly following the diagram that miguellira linked to for a few years but the way we did it hasn't been working very well.

Our current design has backend services and contracts (which are shared with the sites through a NuGet package from a production branch) in one repository and the sites in another. It has become an issue for development, maintenance and release management when those contracts change. I'm thinking our biggest issue is the shared service contracts between the different repositories and the release management pieces. But we learned and now need to revisit our strategy to make it easier to work with and since we are moving things to .net core and WebAPI, and now seems to be an appropriate time.

**Comment by Eilon** [comment]
BTW this would probably also be a great question on StackOverflow, which will certainly reach a very broad audience.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
