### ISSUE TITLE
Discussion for: ASP.NET Core RC2 is no longer compatible with DNX

### ISSUE THREAD

**Issue by Eilon** [aspnet/Home#1426]
Discussion for https://github.com/aspnet/Announcements/issues/176.
# 

Hi all,

ASP.NET Core RC2 is now compatible only with [.NET CLI](https://github.com/dotnet/cli/). ASP.NET Core RC2 is no longer compatible with DNX.

You can read more about the transition from DNX to .NET CLI on these blog posts:
- [ASP.NET 5 is dead – Introducing ASP.NET Core 1.0 and .NET Core 1.0](https://blogs.msdn.microsoft.com/webdev/2016/01/19/asp-net-5-is-dead-introducing-asp-net-core-1-0-and-net-core-1-0/)
- [An Update on ASP.NET Core and .NET Core](https://blogs.msdn.microsoft.com/webdev/2016/02/01/an-update-on-asp-net-core-and-net-core/)

This means that using Visual Studio 2015 with the ASP.NET 5 RC1 tooling will no longer work with the latest _nightly_ builds (i.e. packages coming from https://www.myget.org/gallery/aspnetvnext). The RC1 tooling supports only DNX.

We kept everything compatible with DNX for as long as possible, but eventually we had to separate the two in order to help ship the ASP.NET Core RC2 release.

We are working on finalizing the ASP.NET Core RC2 release, including updated tooling and project templates for Visual Studio.

Visual Studio Code in the meantime works very well with ASP.NET Core RC2 nightly builds.

Thanks,
Eilon

**Comment by 304NotModified** [comment]
Is there an expected date for rc2?

**Comment by smbecker** [comment]
Nothing announced yet. At the last community stand-up, it was mentioned that there would be some announcements at the stand-up next week.

**Comment by Eilon** [comment]
@304NotModified expect announcements very soon!

**Comment by ivaylokenov** [comment]
Hi, is there any way to debug unit tests with .NET CLI? I could not find a way, except run all at once.

**Comment by fogzot** [comment]
Is it possible to run RC2 nightlies on Mono just like we did with RC1/DNX? CoreCLR still has lots of problems on any Linux distribution except the very old Ubunutu 14.04: it just segfaults here on my Debian unstable while RC1/DNX/Mono worked without a hitch.

**Comment by WIMTDib** [comment]
Is it possible for us to just specify the  previous nightlies from before this change was made, so we can avoid having to reconfigure our build server and entire build process. Can we specify a previous version whilst still using the same package feed?

**Comment by Matthew-Bonner** [comment]
Is there a list of what is not compatible?

**Comment by Matthew-Bonner** [comment]
Also, there is so much conflicting information across the board of Microsoft websites now will some time be allocated to removing documentation which is no longer relevant as I think this is going to cause confusion over time and make adopting the new platform a slow and painful process.

**Comment by Tgueth** [comment]
Let's be blunt, we are stepping back to a time when you read the underlying code to understand the structure.  Documentation is way behind.  While interesting that Microsoft is opening documentation process to outside, if Microsoft doesn't have time to write the documentation, unlikely that users will.

Now, I love ASP.NET 5 and MVC 6.  But I almost at the stage to put on back burner a transition to it for a website.  I have survived much of RC1 despite much trouble finding documentation for how to do things.  I have read more underlying code, especially Microsoft's, than I have done since the 80's.  Much of Microsoft's documentation is incorrect and relates mostly to Beta8.  And based on what I see with RC2, I will have a lot of work to do to transition from RC1 to RC2, despite what the standup video claims.

I guess I should have listened when Microsoft suggested to hold off doing live with RC1 (and I assume that will hold with RC2).  ASP.NET 5 is such a moving target.  RC1 should have been called Beta 9.  By RC1, I expected the base structures to have solidified and minor tweaks on out to manufacturing release.  Unfortunately, this is not the case.  Honestly doubt that we will see RC2 before July and cannot see any way that final manufacturing version will be done in 2016.  When you are still changing namespaces in RC2, Microsoft has lost site of the goal - get users using it.

I hate to beat down on ASP.NET 5/MVC 6.  I just love it but time to put this on the shelf and go back to improving my MVC 5 version of the website, and wait to start back up in 2017 with final release.

**Comment by GuardRex** [comment]
@Matthew-Bonner @Tgueth 

> Documentation is way behind.

Well, not really. The docs for RC2 release have been under heavy development, and they are available in the `dev` branch. They will be flipped into `latest` (`master` branch) when RC2 releases. You do have access to them. It's just not widely advertised that you can see them now on the `dev` branch. 

Being under development, the docs coming out soon might not be accurate or complete. I'm working on one today that has real bugs in the text, and I'll be getting those bug-a-boos out this morning. However, you can get to them in the Docs repo in the `dev` branch https://github.com/aspnet/Docs/tree/dev. Also, note that the naming changed to `ASP.NET Core 1.0` and `MVC Core 1.0` in https://github.com/aspnet/Announcements/issues/144.

**Comment by dustinkingen** [comment]
I installed the C# extension in VS Code and it didn't seem to work with an existing .NET CLI project.

**Comment by nicolasr75** [comment]
@dustinkingen  Have you tried the newest VSCode insider version and the newest release candidates of the Omnisharp C# extension? My tests with a .Net Cli Mvc project were actually quite successful:
https://code.visualstudio.com/blogs/2016/02/01/introducing_insiders_build
https://github.com/OmniSharp/omnisharp-vscode/releases

**Comment by dustinkingen** [comment]
Thanks @nicolasr75 I will give the inside build a try.

**Comment by roterdam** [comment]
Will this be the final blow? Or do you expect more churn and API changes for RTM?

**Comment by Eilon** [comment]
@roterdam there will be minimal API surface changes to the runtime NuGet packages (i.e. the stuff that actually runs as part of your app). The key areas of improvement between RC2 and RTM will be: bugs, security, performance, and reliability.

**Comment by Eilon** [comment]
BTW a blog announcement regarding the RC2 plans was posted earlier today: https://blogs.msdn.microsoft.com/dotnet/2016/05/06/net-core-rc2-improvements-schedule-and-roadmap/

**Comment by gdoron** [comment]
> Visual Studio Code in the meantime works very well with ASP.NET Core RC2 nightly builds.

I hope it was a joke...
Visual studio code is decent text editor far from being an IDE... 😭
But maybe it's just me.

**Comment by dustinkingen** [comment]
@gdoron I tried following the instructions to get on nightly but dotnet CLI can't find the packages on nuget or the Microsoft myget feed for dotnet-core/aspnet. I'm just going to wait for RTM.

**Comment by gdoron** [comment]
@dustinkingen you can wait for RC 2(should be mid May), no need to wait for RTM(end of June).
I personally am going to wait for RC2, visual studio code IMHO is somewhere between wordpad and Notepad++ and very not user friendly.

**Comment by GuardRex** [comment]
@dustinkingen Yes, the learning curve is especially rough right on the eve of RC2 and new docs about to hit to cover RC2. You can find new docs on the `dev` branch in the Docs repo, but they're still very WIP right now. The `cli-samples` are kept up-to-date at https://github.com/aspnet/cli-samples. Get the .NET Core SDK Installer from https://github.com/dotnet/cli/tree/rel/1.0.0. It does all work. If you run into any issues or have questions, you can come over to JabbR sometime and talk to the devs there. https://jabbr.net/#/rooms/AspNetCore

**Comment by mikes-gh** [comment]
In my opinion RTM end of June is too soon .
Thats probably not a popular view and just a gut feeling from the commit traffic and recent API churn.
RC2 should keep everyone happy in the meantime.

**Comment by MaximRouiller** [comment]
@gdoron  

>  somewhere between wordpad and Notepad++

Didn't know you could debug C# and have Intellisense in Notepad++.

**Comment by dotnetchris** [comment]
Someone needs to figure out that RC means not setting the entire harbor on fire to unmoor a ship.

**Comment by doc** [comment]
@dotnetchris Have a little respect pal. The team has been busting their butts trying to put out a quality product that works for a vast and varied audience. If you have some constructive criticism then file a bug or better yet, submit a PR; otherwise keep your comments to yourself.

**Comment by dotnetchris** [comment]
@doc anger is the proper response to **being lied to**. To call this RC1 and RC2 yet you break the entire world in the middle? That's me being lied to. That's called alpha level of completion in software. I'm entirely fine with the rug being pulled out from under me on alpha products. 

But for this to happen between beta10 and beta11 shows this project is excruciatingly far away from release ready.

**Comment by gdoron** [comment]
@dotnetchris though I'm not a native English speaker, AFAIK RC stands for Release **Candidate** and thus subject to changes (which by the way Microsoft itself didn't anticipate which made it delay the following releases by quite a significant amount of time).

BTW, I do not feel like the rug was pulled out from under me...

**Comment by 304NotModified** [comment]
I think this is not the right place to discuss / complain about RC1 was not a "real"  RC.

**Comment by ShikiGami** [comment]
Meh, the CLI tooling is broken for RC2 anyway. You cannot even get to compile solutions that call other projects inside the same solution as dependencies, because the tooling won't find their binaries.
This is still like beta stage broken.
I have a lot of respect for all of you working on this, but it really hurts a lot to people that start to move their platform as soon as something hits RC, so that they can have it ready when production hits. DNX was probably not the best choice, but I really think you guys should have waited AFTER RTM to introduce CLI to the platform.
People are pissed because of how much time it is taking from a supposed Release Candidate, and then it feels rushed when the tools are not even ready yet.

**Comment by dustinkingen** [comment]
Release candidates are subject to change. I think of them as "here is what we have, do you like it?" It's better to have many different RCs than to have a broken RTM.

**Comment by MaximRouiller** [comment]
@ShikiGami Is there an issue opened with your steps to reproduce?

**Comment by ShikiGami** [comment]
@dustinkingen RCs are completely subject to change, the problem is the degree of change. It wasn't like DNX was broken, but people just felt "it was not the future", and they wanted to make all the NET Core development environments consistent, which is something I completely support, don't get me wrong. I think CLI is a great idea, what I don't like is the timing this was introduced. Replacing DNX with CLI in the RC phase makes the RC phase really meaningless, because it is a mayor change, and then after that, they just started to change a lot of stuff from RC1. The number of breaking changes makes it really more like a beta than a RC.
I really think releasing with DNX for 1.0, and then changing to CLI in the next version would have been better, because, I think it was way too late to introduce that change.
Now the RTM is going to release with still beta stage CLI tooling (They are calling it "Preview 2"), instead of a fully functional DNX tooling, after waiting half a year since the previous RC.
@MaximRouiller There are already two open issues about this in the CLI issues. There are workarounds, but it is still broken non the less.

**Comment by Pictuel** [comment]
Imo the fact that we can't publish RC2 app to azure websites yet is another trigger to let me think it's not production ready as stated in the announcement. They're saying they are working with team that have shipped their solution to azure, ok but probably an early RC2 build. Still lots to do keep it up guys, don't give up!

**Comment by moozzyk** [comment]
You could publish standalone apps to Azure for some time now and from what I know they rolled out RC2 to their data centers as well so portable apps should work as well should work as well.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
