### ISSUE TITLE
too many things made over-bloated

### ISSUE THREAD

**Issue by johnx7271** [aspnet/Home#1468]
Just a example, let's see its login stuff:
public class IdentityUser : IdentityUser<string, IdentityUserLogin, IdentityUserRole, IdentityUserClaim>, 
    IUser, IUser<string>

public class IdentityUser<TKey, TLogin, TRole, TClaim> : IUser<TKey>
        where TLogin : IdentityUserLogin<TKey>
        where TRole : IdentityUserRole<TKey>
        where TClaim : IdentityUserClaim<TKey>

public class UserStore<TUser, TRole, TKey, TUserLogin, TUserRole, TUserClaim> : 
    IUserLoginStore<TUser, TKey>, 
    IUserClaimStore<TUser, TKey>, 
    IUserRoleStore<TUser, TKey>, 
    IUserPasswordStore<TUser, TKey>, 
    IUserSecurityStampStore<TUser, TKey>, 
    IQueryableUserStore<TUser, TKey>, 
    IUserEmailStore<TUser, TKey>, 
    IUserPhoneNumberStore<TUser, TKey>, 
    IUserTwoFactorStore<TUser, TKey>, 
    IUserLockoutStore<TUser, TKey>, 
    IUserStore<TUser, TKey>, IDisposable
    where TUser : IdentityUser<TKey, TUserLogin, TUserRole, TUserClaim>
    where TRole : IdentityRole<TKey, TUserRole>
    where TKey : IEquatable<TKey>
    where TUserLogin : IdentityUserLogin<TKey>, new()
    where TUserRole : IdentityUserRole<TKey>, new()
    where TUserClaim : IdentityUserClaim<TKey>, new()

How does the above look like to you?

In principle, the login stuff is only a very small portion of an web application, the api framework should be simple, easy to learn, easy to customize, however the above stuff fabricated by MS looks so unwieldy, so complex, and it takes a lot just to get a basic grasp of it, not to mention how to customize it. Besides, the performance of this stuff is reportedly extremely bad, it's said that a simple login will take 7 round-trips to database server.

Over the years,  asp.net has been made over-bloated, too many alternatives, too many options, too much configurations, too complex, too much to learn, this is my point of view.

**Comment by Pictuel** [comment]
you're probably right but I mean this is why open source is great because you can learn from this class, which is good enough for many scenarios, and do your own implementation from it.

**Comment by rdefreitas** [comment]
All that is though is an example of a class using multiple contracts so that it can be consumed by more than just one API. Those contracts make the class more usable not less.

Also is there any instance in which you see you need to implement your own completely custom user store from scratch,  or can your goal be accomplished by overriding implementation of the base class?

The case you're exposing there is a single class implementing multiple contracts with the goal of making it easier toinstantiate and inject into your application.

**Comment by rdefreitas** [comment]
What is the things that all of those contracts explode is just how easy it is to change various bits of the application. Don't need 2 Factor Authentication? Don't implement.

**Comment by johnx7271** [comment]
@Pictuel  : The focus here is not about learning, but about practical using by practitioners.

@rdefreitas:  With things as complex as that, 1. Costly even to find out where to go for a customization, and to get a basic understanding about it (Can you dare to proceed customizing sth even before a basic grasping of it?). People want to learn sth quickly, then do their customizing and then complete it and move on to next tasks.
2. How can people feel safe that when they touch one part, other parts will not break? "contracts exploding" mean complexity exploding, and testing jobs exploding, and ...

**Comment by johnx7271** [comment]
Btw, I feel the assemblies, namespaces, classes, ...of asp.net,  all exploded, while the documentations imploded, that's a bad thing. 

It would be really helpful if some Uml diagrammings are included in the docs.

**Comment by reddyBell** [comment]
I agree with @rdefreitas having implemented custom user stores on a number of occasions : this is a very cool design which makes things flexible and easy.

You don't have to implement contracts if you don't need them, I usually stick to IUserStore and IPassword store :)

On the client side, there are cool properties : IsEmailStore etc... In the bootstraper Indicating what has been implemented. Great stuff from Microsoft.

If you use SQL Server you don't even need to bother implementing stores since there's a default implementation using EF (adhoc overrides might be enough if you need some). The only reason I create custom user stores is that I use NoSQL databases.

**Comment by markrendle** [comment]
It's called the [Interface Segregation Principle](http://www.oodesign.com/interface-segregation-principle.html), or ISP, and it's the I in SOLID and a fundamental ideal of good object-oriented design.

**Comment by danieltharris** [comment]
Personally I agree with the general consensus that this is isn't overly complicated. 

I've worked with code that is massively over-engineered and uses interfaces and repositories where they weren't need and they've made the code more difficult to understand - I don't feel this is a problem with what you've highlighted though and it makes sense for this to be flexible.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
