### ISSUE TITLE
Cannot use text/plain on HttpRequestMessage.CreateResponse

### ISSUE THREAD

**Issue by Thaina** [aspnet/Home#1606]
I just create Azure function with just this

``` C#
public static async Task<HttpResponseMessage> Run(HttpRequestMessage req, TraceWriter log)
{
    return req.CreateResponse(HttpStatusCode.OK, "Hello","text/plain");
}
```

And it cause this error

> Microsoft.Azure.WebJobs.Script: One or more errors occurred. System.Web.Http: Could not find a formatter matching the media type 'text/plain' that can write an instance of 'String'.

Also occurred with `text/html`

**Comment by davidfowl** [comment]
This bug should be filed here https://github.com/Azure/azure-webjobs-sdk-script

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by poke** [comment]
@Jon007 That's a problem with the Azure WebJobs SDK. But this is the repository for ASP.NET Core, so we really cannot help here.

I'd suggest you to follow David's advice above and try that Azure repository.

Since this is the top result, feel free to link to the answer once you have resolved the problem.

**Comment by Jon007** [comment]
it's not specifically Azure but I suspect not Core either.

ASP.Net doesn't provide a TextFormatter, only XmlFormatter and JSON, so if a plain text response is needed, instead of:

`return req.CreateResponse(HttpStatusCode.OK, "Hello","text/plain");`

use this to force a plain text response content:
```
                var resp = new HttpResponseMessage(httpStatusCode);
                resp.Content = new StringContent("Hello", System.Text.Encoding.UTF8, "text/plain");
                return resp;
```
simple enough but there's quite a few threads out there with people confused over the inability of the first option to convert a string to text and alternative solutions including custom TextFormatter classes.

in core perhaps:
`                return Ok("Hello");
`
(which does not return a HttpResponseMessage)
