### ISSUE TITLE
strategy for nuget packages for aspnet core and full fw

### ISSUE THREAD

**Issue by rrelyea** [aspnet/Home#1618]
Your team should probably take a first stab at this: https://github.com/NuGet/Home/issues/3059
Please reopen the NuGet issue if I am mistaken.

**Comment by BrennanConroy** [comment]
Take a look at this, might help https://docs.microsoft.com/en-us/dotnet/articles/standard/library

**Comment by 304NotModified** [comment]
I read the docs multiple times but i don't get it. :(

If an user targets net451 it could be asp.net 4.5 or asp.net core right? 
Then how do we support as library maintainers both frameworks in 1 package?

**Comment by BrennanConroy** [comment]
No, if you target net451 you target full framework. If you target netcorapp1.0 you target ASP.NET Core. In your library you should target netstandard1.x which maps in the table that I linked to a specific net4xx target and netcoreapp1.0

**Comment by 304NotModified** [comment]
Then why is https://www.nuget.org/packages/Microsoft.AspNetCore.Http.Extensions/ also targeting net451?

**Comment by 304NotModified** [comment]
For example, in asp.net we use httpcontext and for asp.net core IHttpContextAccessor

If an user uses asp.net on net451, then we need to use httpcontext.  

If an user uses asp.net core on net451, then we need to use IHttpContextAccessor. 

So we need two packages? Full and core?

**Comment by BrennanConroy** [comment]
Ok, so netstandard1.x is a subset of net4xx, so if you want to target all of net451 for example instead of the subset that netstandard1.2 consists of, then you need to add net451 to your library.

**Comment by cwe1ss** [comment]
It's important to consider the differences between the .NET framework and ASP.NET.

If your library is not related to ASP.NET, you can easily target the full framework and the new .NET Core with netstandard because the API basically is the same.

ASP.NET 4 and ASP.NET Core however are two totally different products with different APIs. ASP.NET 4 only runs on the full framework, ASP.NET Core runs on the full framework and on .NET Core.

If you want to support ASP.NET 4 and ASP.NET Core in your product, you more or less have to create separate packages of your product (eg YourProduct.AspNet and YourProduct.AspNetCore) because they need to reference different NuGet packages. The one for ASP.NET 4 could target netstandard, but of course, it will not run on anything else than the full framework, so you can also just target eg net451.
The version for ASP.NET Core should definitely target netstandard to allow your users to use it in apps that target either the full or the core version. 

Easy :)

**Comment by 304NotModified** [comment]
Well maintaining the double amount of packages isn't easy :( . Its taking at least the two times the work (2 projects, 2 build configurations, 2 deployments,  and keeping them in sync) 

Was hoping there was another strategy.

**Comment by 304NotModified** [comment]
Is it possible to force in a net451 (asp.net core) project  that it will use the netplatform (asp.net core)  platform for a library instead of the net451 (asp.net) ?

**Comment by 304NotModified** [comment]
PS it's confusing that asp.net core on the full framework is still called asp.net core while it isn't .net core. At least my question is difficult to understand (or I don't understand it)

**Comment by cwe1ss** [comment]
Yes, you have to think of ASP.NET Core as a totally separate product. For the sake of argument, let's give it a different name and call it "Webby". Of course, some of the APIs are similar, but there's also a huge amount of differences.

Or compare it with Nancy - you wouldn't reference ASP.NET and Nancy in one library, even though they both are web frameworks.

Of course, you could try to do weird stuff in project.json and pull in ASP.NET Core packages in "netstandard" and "ASP.NET 4" packages in "net451", but a) I don't know which packages users of your library targeting net451 will actually end up and b) you now have to use a million compiler directives, because even if some of the class names are the same, EVERY namespace is different.

**Comment by davidfowl** [comment]
Sure it's not easy but you don't really have a choice. The 2 frameworks have the same ASP.NET name but are totally different products.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
