### ISSUE TITLE
Should ASP.NET Core have its own Roslyn Analyzers?

### ISSUE THREAD

**Issue by svick** [aspnet/Home#1629]
It occurred to me that the issue reported at https://github.com/dotnet/core/issues/126, where the user incorrectly attempted to use ASP.NET Core logging format string as if it was a `string.Format` format string (i.e. they expected that `logger.LogInformation("{1}{0}", "a", "b");` would log `"ba"`) could be solved by a Roslyn Analyzer: If all placeholders are numbers and they are not ordered, the analyzer would produce a warning.

But I think it doesn't make sense to create an analyzer just for this single issue, so:

Are there other issues that could benefit from having an analyzer (or a code fix)? Is there enough of them so that creating the analyzers would be worth it?

**Comment by Kimberleyrene** [comment]
Stop sending me emails

On July 2, 2016, at 16:44, Petr Onderka <notifications@github.com> wrote:

It occurred to me that the issue reported at https://github.com/dotnet/core/issues/126, where the user incorrectly attempted to use ASP.NET Core logging format string as if it was a `string.Format` format string (i.e. they expected that `logger.LogInformation("{1}{0}", "a", "b");` would log `"ba"`) could be solved by a Roslyn Analyzer: If all placeholders are numbers and they are not ordered, the analyzer would produce a warning.

But I think it doesn't make sense to create an analyzer just for this single issue, so:

Are there other issues that could benefit from having an analyzer (or a code fix)? Is there enough of them so that creating the analyzers would be worth it?

---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/aspnet/Home/issues/1629

**Comment by muratg** [comment]
@Kimberleyrene You'll need to stop following the GitHub repos if you do not want to get notifications.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
