### ISSUE TITLE
Deploy to azure, wwwroot inside wwwroot

### ISSUE THREAD

**Issue by bragma** [aspnet/Home#1636]
I've build and deployed a default template ASP NET Core 1.0 Web API to an azure Web App and added some static html files inside my project's local wwwroot. After updating the online project, I ended up with the home/site/wwwroot folder containing another wwwroot. While this works, isn't it a bit weird? Is it expected?
In the past I've deployed the app executables to a custom "site/approot" folder and static files to "site/wwwroot" but this caused me a lot of pain with VSTS and other tools expecting to work with wwwroot, in particular with WebJobs.
What's the final expected directory layout of an ASP NET Core application when deployed to Azure?

**Comment by GuardRex** [comment]
Yes, it was leftover from the days of `approot` and `wwwroot`. They didn't change the layout in Azure Apps, and I think this was maintained for backwards compat to not break DNX/RC1-era apps. You do have the correct current layout for Azure Apps.

**Comment by bragma** [comment]
@GuardRex thanks for the prompt answer!
Ok, no problems with that. Good to know that it's ok to have static files, webjobs and the app in the same folder. This poses a problem with webjobs, though. Suppose I want to redeploy my web app and I check the "remove additional files at destination" option from VS. I think App_Data will be wiped away with no way to restore the WebJobs aside from redeploying them too (which is a manual operation, now - if I didn't miss anything).

**Comment by GuardRex** [comment]
@bragma Sounds right, but I'm not using WebJobs, so I'll defer on that one. cc/ @moozzyk - sound right to you?

**Comment by vijayrkn** [comment]
First regarding the layout (https://github.com/aspnet/Docs/issues/1305). This is how 'dotnet publish' packages the deployable content. For Azure Web apps, the default webroot folder is called 'wwwroot' (folder containing web.config), that is the reason, you see a 'wwwroot' folder inside a 'wwwroot'. 

+----------------+------------------------------------------------+
| App Type       | Directory Structure                            |
+================+================================================+
| Portable       | - publish*                                     |
|                |   - logs* (if included in publishOptions)      |
|                |   - refs*                                      |
|                |   - runtimes*                                  |
|                |   - Views* (if included in publishOptions)     |
|                |   - wwwroot* (if included in publishOptions)   |
|                |   - .dll files                                 |
|                |   - myapp.deps.json                            |
|                |   - myapp.dll                                  |
|                |   - myapp.pdb                                  |
|                |   - myapp.runtimeconfig.json                   |
|                |   - web.config (if included in publishOptions) |
+----------------+------------------------------------------------+
| Self-contained | - publish*                                     |
|                |   - logs* (if included in publishOptions)      |
|                |   - refs*                                      |
|                |   - Views* (if included in publishOptions)     |
|                |   - wwwroot* (if included in publishOptions)   |
|                |   - .dll files                                 |
|                |   - myapp.deps.json                            |
|                |   - myapp.exe                                  |
|                |   - myapp.pdb                                  |
|                |   - myapp.runtimeconfig.json                   |
|                |   - web.config (if included in publishOptions) |
+----------------+------------------------------------------------+

You can change the name of this from the portal if needed.
![image](https://cloud.githubusercontent.com/assets/3981619/16596259/ecf55280-42a7-11e6-84ff-784ab30ac9d0.png)

If you want to change the name of the folder containing the static files, you can configure that in project.json.

Regarding the second question: As you mentioned, the app_data folder is also in this same folder and when "remove additional files at destination", it removes the app_data folder from server if it is not present in the publish payload. We are working on the tooling support for publishing web jobs also as part of web app publish experience. Once this is available it should solve the issue. Until then, you can have a custom script to copy the required app_data files to the publish directory before publishing to the server and because the app_data files are present in publish payload, app_data files will not be deleted on the server.

**Comment by bragma** [comment]
Thanks a lot, now things are a bit more clear. Regarding the second question, I've not understood the part "can have a custom script to copy the required app_data files to the publish directory before publishing". Do you mean that I should publish to "site/wwwroot" and move my webjob there as part of the deploy zip? In this case, that's what I do.

**Comment by vijayrkn** [comment]
You can add the xcopy logic to the postPublish script section:

Sample:

`    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%", "xcopy E:\\git\\WebApplication1\\src\\WebJob\\bin\\Debug\\netcoreapp1.0 %publish:OutputPath%\\app_data\\jobs\\continuous\\TestWebJob\\  /F /R /Y /I" ]`

**Comment by bragma** [comment]
@vijayrkn thanks all is clear now. Instead of using xcopy I am publishing the webjobs directly into the web app publish output, but the result is the same.

**Comment by Asshiah** [comment]
Using xcopy in the postpublish script works fine in command-line but it seemd nothing happen while publishing with Visual Studio 2015.

Same for postcompile script.

**Comment by vijayrkn** [comment]
it should work from VS as well. Is it possible to share your project.json?

for e.g: the project.json here has dotnet publish-iis tool in post publish section and this gets executed on post publish. https://github.com/aspnet/MusicStore/blob/dev/src/MusicStore/project.json
`
  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-*"
  },
  "scripts": {
    "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
  }
`

Are you having issues with just xcopy in postpublish section or anything in postpublish section?

**Comment by GuardRex** [comment]
I think some devs have had trouble with that splat version (perhaps related to their feeds in use). If `1.0.0-*` doesn't work, try `1.0.0-preview2-final`.

**Comment by moozzyk** [comment]
One of the problems I have seen is that if you upgraded packages from rc2 to rtm using VS NuGet UI it will remove packages from `tools` and will move them to `dependencies` which breaks tools.

**Comment by Asshiah** [comment]
@vijayrkn 

I only have problem with using xcopy in postpublish (or postcompile) scripts.

Here is my project.json:

`{
  "userSecretsId": "CPAS",

  "dependencies": {
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Mvc.Localization": "1.0.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.Session": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Extensions.Configuration.Binder": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "DelegateDecompiler": "0.18.1",
    "EntityFramework": "6.1.3",
    "SimpleInjector": "3.2.0",
    "SimpleInjector.Extensions.ExecutionContextScoping": "3.2.0",
    "SimpleInjector.Integration.AspNetCore.Mvc": "3.2.3",
    "System.Linq.Dynamic.Library": "1.1.14",
    "Serilog.Extensions.Logging": "1.0.0",
    "Serilog.Sinks.RollingFile": "2.1.0",
    "Kendo.Mvc": "2016.2.630-Preview",
    "StackifyMiddleware": "1.4.1",
    "Serilog.Sinks.Stackify": "1.23.1-beta2",
    "CPAS.Data": "1.0.0-*",
    "CPAS.Service": "1.0.0-*",
    "CPAS.Settings": "1.0.0-*"
  },
  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [
        "portable-net45+win8"
      ]
    }
  },
  "frameworks": {
    "net461": {
      "frameworkAssemblies": {
        "System.DirectoryServices": "4.0.0.0",
        "System.DirectoryServices.AccountManagement": "4.0.0.0"
      }
    }
  },
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "compile": {
      "exclude": [ "wwwroot", "node_modules", "bower_components" ]
    }
  },
  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "appsettings.Staging.json",
      "appsettings.Development.json",
      "web.config"
    ]
  },
  "scripts": {
    "postcompile": "xcopy /y %project:Directory%\\..\\CPAS.Service\\bin\\%compile:Configuration%\\%compile:TargetFramework%\\System.IO.compression.dll %compile:RuntimeOutputDir%\\",
    "prepublish": [ "npm install", "bower install", "gulp min", "gulp libs" ],
    "postpublish": [
      "xcopy /y %publish:ProjectPath%\\..\\CPAS.Service\\bin\\%publish:Configuration%\\%publish:TargetFramework%\\System.IO.compression.dll %publish:OutputPath%",
      "xcopy /y %publish:ProjectPath%\\..\\CPAS.Service\\StreamServ\\WinSCP.exe %publish:OutputPath%",
      "xcopy /y /i %publish:ProjectPath%\\..\\CPAS.Service\\StreamServ\\Templates %publish:OutputPath%\\Templates",
      "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
    ]
  }
}
`

**Comment by vijayrkn** [comment]
@Asshiah  When executing from VS, is it skipping just the xcopy portion of postpublish or xcopy and dotnet publish-iis?

When you say, it works from commandline, are you execuring "dotnet publish" command from commandline? When publishing from VS, VS also calls this same commandline (dotnet publish - the command executed and output from the command is displayed on the output window as well). Can you share the output from output window? this should have the details on what got executed and what was skipped.

**Comment by Asshiah** [comment]
@vijayrkn 

When publishing from VS, the dotnet publish-iis is working fine (the web.config file is OK and tokens were replaced as expected). Only the xcopy portion does not seem to execute as no files are copied to the output directory.

When publishing from command-line (dotnet publish command), everything works fine.

I attached VS's publish output to this post.

[publication-VS.txt](https://github.com/aspnet/Home/files/363285/publication-VS.txt)

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
