### ISSUE TITLE
Version numbers, CI builds, and GitVersion

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1659]
I use [Insert Build Server of choice] to build my solution (RTM, Preview 2).

This solution contains many projects, each with their own `project.json` file.

If I want all of those projects to be assigned a particular version number - how do I go about that?

`dotnet pack` let's you pass in a pre-release label only it seems.

The obvious answer would seem to be to update the `version` field in project.json at the start of the build but consider this:

If Project A --> Project B --> Project C

If you update the `version` in Project C's project.json, you also have to update the `dependencies` section in all project.json files that reference that project. 

So multiply that effort across a solution with 20 projects in - it's a royal pain in the ass.

Is there any tooling / plans to fix this scenario in the near future and what are they?

**Comment by davidfowl** [comment]
With the change to msbuild it'll be easier as you can just specify a property. As for a short term solution with the current toolchain you'll need to file an issue on https://github.com/dotnet/cli

**Comment by bragma** [comment]
@dazinator I've had the same problem when I wanted to add my git commit hash to version. I didn't like the idea to change the value in project.json on each build, since it would cause problems with git seeing it as a modified file and obviously I don't want project.json to be "git .ignore"(d).
So this is what I did:

I've added an AssemblyInfo.cs.tpl template file to project's property folder. The template allows me to set copyright, version, etc. Then on each build I use gulp-template to generate the AssemblyInfo.cs (which is git ignored). Then in my app I get the version from there.
I can fill in the details if you need.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
