### ISSUE TITLE
Inconsistent "Migrations" folder path when Re-Scaffold 

### ISSUE THREAD

**Issue by stevesiu** [aspnet/Home#1675]
Re-Scaffold migrations created "Migrations" folder in project root instead of the original path /Data/Migrations.  It still works but a consistent folder path is better.

**Steps to reproduce the issue**
1. Create an "ASP.NET Core Web Application (.NET Core) with "Individual User Accounts" authentication
2. Delete the "/Data/Migrations" folder
3. Run "Add-Migration MyDB" in Package Manager Console
4. The "Migrations" folder is created in the project root instead of "/Data"

**Comment by rdefreitas** [comment]
Migrations will be placed in whatever folder the Model Snapshot file is located in, but the default has always been /Migrations.  Since they included a snapshot file in Data/Migrations in the new templates, it scaffolds additional migrations there.

They should probably change the default to match the templates.

In the meantime, a workaround does exist... one of the parameters for the migration add command includes specifying the path.

From the [ef docs](https://docs.efproject.net/en/latest/miscellaneous/cli/dotnet.html#dotnet-ef-migrations-add):

	Usage: dotnet ef migrations add [arguments] [options]

	Arguments:
	  [name]  The name of the migration

	Options:
	  -o|--output-dir <path>          The directory (and sub-namespace) to use. If omitted, "Migrations" is used. Relative paths are relative the directory in which the command is executed.
	  -c|--context <context>          The DbContext to use. If omitted, the default DbContext is used
	  -e|--environment <environment>  The environment to use. If omitted, "Development" is used.
	  --json                          Use json output. JSON is wrapped by '//BEGIN' and '//END'
	  -h|--help                       Show help information
	  -v|--verbose                    Enable verbose output

To run your intended migration with your output going to the Data/Migrations folder, you'd do the following:

	dotnet ef migrations add InitialMigration -o Data/Migrations

**Comment by stevesiu** [comment]
@rdefreitas, thanks for the explanation and workaround!

**Comment by rdefreitas** [comment]
@stevesiu glad it worked out for you :)

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
