### ISSUE TITLE
WebAPI Core - FromBody values always null after referencing System.Data.SqlClient 4.1.0

### ISSUE THREAD

**Issue by victorvartan** [aspnet/Home#1687]
I'm not sure if this is the right place to post the issue, but on any POST endpoint I receive null values for all FromBody parameters after adding the dependency System.Data.SqlClient 4.1.0 although I don't actually use it... Using FromQuery values works. I attached a sample project.
[TestAspCore.zip](https://github.com/aspnet/Home/files/380465/TestAspCore.zip)

**Comment by rynowak** [comment]
I've seen a similar problem before here: https://github.com/aspnet/Home/issues/1605#issuecomment-229158767

The root cause is likely a mismatch between the `1.0.0-rc2` Kestrel binaries and the `1.0.0` .NET Core libraries. You can check this by looking at the console log or developer exception page - or if you have a debugger, attach the process and break on first chance exceptions.

**Comment by victorvartan** [comment]
You're right, thanks for the link and sorry for the duplicate issue, closing it!

**Comment by rynowak** [comment]
No worries, this was a hard issue to track down!
