### ISSUE TITLE
how to clear cache cached by distributed-cache tag-helper?

### ISSUE THREAD

**Issue by anobaka** [aspnet/Home#1703]
or is it possible to clear cache when application starts?

**Comment by pranavkm** [comment]
@sebastienros might have more insight here. I think the intent here is that you produce new keys which causes the caching server to eventually remove old entries. If you'd like to ensure your application does not use results from a previously run instance, you could use a vary by token for a value that's initialized at Startup:

```C#
ConfigureServices(IServiceCollection collection)
{
   ...
   collection.AddSingleton(new ApplicationIdentityService { Value = Guid.NewGuid().ToString() });
}

@inject ApplicationIdentityService AppId

<distributed-cache vary-by="@AppId.Value" ...>
..
</distributed-cache>
```

**Comment by sebastienros** [comment]
I agree with @pranavkm, that would work, but maybe you are tackling the problem the wrong way, we'd need to know what you exact problem is.

Let's say you are developing you app and you wan't to clear the cache in order to be able to see the results based on your updates. If the view in which the tag helper is used is changed then the tag helper will get a new internal identifier and use new keys for the cache. This is however not the case if you are caching the result of a view component. But still, if you are developing your app then you could not use any other cache provider like redis or sql server, and then it would default to a memory cache implementation, which is cleared at every startup by design.

If you are actually using sql server or redis providers for the distributed cache, then on top of these solutions you can always clear the cache manually. There is a single command to execute on redis to clear the database, and same idea for sql server. This is manual but also more flexible in case you want to clear it while your app is running, even in production.

**Comment by anobaka** [comment]
@pranavkm @sebastienros thanks for your attention and answers! 

@pranavkm , it's a good idea and I'm going to use it, but mayby it likes some kind of hardcode that all of my team members should know and remember that rules without IDE's intelligence: **inject `AppId` and add `vary-by="@AppId"` everytime when using distributed tag-helper**.

@sebastienros , I'm using redis provider and cached the results of some view components so I can skip some data computing or some IO operations by cache, it's something like that:

**in my ViewComponent**
```
public class BannerViewComponent {
    public async Task<IViewComponentResult> InvokeAsync() {
        //invoke and compute data from my data provider(sqlserver, mysql, webservices, etc)
    }
}
```
**in View**
```
<distributed-cache name="banner" expires-after="TimeSpan.FromHours(1)">
    @(await Component.InvokeAsync("Banner"))
</distributed-cache>
```

I tried clearing cache manually but the generated key is not readable, so I couldn't know which key represents the data I want immediately, it's much harder to locate the key I want to remove if there are plenty of cache keys. What am I supposed to deal with that?

Thanks

**Comment by sebastienros** [comment]
It should be very easy (though haven't tried it myself) to use a specific database (http://www.rediscookbook.org/multiple_databases.html) for the distributed cache, then flush all items from this database.

**Comment by anobaka** [comment]
but it's also used for distributed `session`, or is it possible that inject two instances of `RedisDistributedCache` in DI Container which one used for cache tag-helper and another for session?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
