### ISSUE TITLE
Question about Strongly Typed Url (aka t4mvc)

### ISSUE THREAD

**Issue by valeriob** [aspnet/Home#1724]
Is there any plan on this theme ?
I think that having that feature in a framework is foundamental for any non trivial application. At the moment is the number one missing feature to begin a new project o bring the old ones to asp.net core.
As developer i would like to not break any links, and i would like to migrate asp.net application using t4mvc to asp.net core without modifying manually all the places where it was used.

Thanks

**Comment by Tratcher** [comment]
Have you asked https://github.com/T4MVC/T4MVC/issues?

**Comment by pranavkm** [comment]
Have you had a chance to look at https://github.com/ivaylokenov/AspNet.Mvc.TypedRouting?

**Comment by valeriob** [comment]
no @pranavkm i will !
Looking at documentation it seems quite verbose, requiring to configure both routing and route generation, without an easy path to migrate from t4mvc.

**Comment by mcquiggd** [comment]
I started down this route with T4. Its not a full replacement for T4MVC, because I personally found that too heavy. 

https://github.com/Pro-Coded/Pro.MVCMagic

I use it in my own projects, in Visual Studio 2016 with ASP.Net Core 1.0. I also have a proof of concept version that would support VS Code, using Roslyn for meta data, and another Github project that executes T4 and Razor templating via the CLI or a Gulp task. 

It is not released as a NuGet - it was left on the shelf as the whole DNX / .Net Core / lack of stability / lack of direction for a templating strategy simply became too frustrating / time consuming and myself and others moved onto to other things. Might dust it off when I have time or a proper direction emerges from Microsoft regarding T4 or a successor.

**Comment by valeriob** [comment]
Any update on this side ? Are people really using magic string to develop asp.net core apps ?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by valeriob** [comment]
Hi,
just as update, r4mvc is up and running  https://github.com/T4MVC/R4MVC
