### ISSUE TITLE
Concurrent requests fail if using EF UseSqlServer SqlConnection overload

### ISSUE THREAD

**Issue by andradf** [aspnet/Home#1725]
Basically, if one uses the overload with a SqlConnection argument when adding a DbContext to services instead of a connection string, concurrent calls will fail.
### Minimal repro steps

Start with a blank aspnet core project.
Startup should have 

```
        public void ConfigureServices(IServiceCollection services)
        {
            var connStr = "Server=(localdb)\\mssqllocaldb;Database=aspnet-ConcurrencyBug;Trusted_Connection=True;MultipleActiveResultSets=true";

            ////this works
            //services.AddDbContext<ApplicationDbContext>(options =>
            //    options.UseSqlServer(connStr));

            //this does not work
            var conn = new SqlConnection(connStr);
            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(conn));
            services.AddMvc();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseStaticFiles();
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
```

In a controller define an action that uses the dbContext

```
    [Route("api/[controller]")]
    public class TestController : Controller
    {
        private ApplicationDbContext dbContext;
        public TestController(ApplicationDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        [HttpGet("{id}")]
        public async Task GetAction1(string name)
        {
            await dbContext.People.FirstOrDefaultAsync(u => u.Name == name);
        }
    }
```

Make two concurrent requests

```
<script>
            $(document).ready(function(){
                $.get("api/test/john", function(data){
                    console.log(data);
                });
                $.get("api/test/jane", function(data){
                    console.log(data);
                });
            });
</script>
```
### Expected result

No exceptions
### Actual result

A NullReferenceException is thrown in one of the two concurrent requests

**Comment by Alex-Torres** [comment]
+1

**Comment by joeaudette** [comment]
why would you want to do that? Seems like creating a connection object in startup and then trying to use it throughout the app would be less efficient anyway. I think that would be like a singleton connection object rather than scoped per request as it should be.

better to leverage the connection pool and let the connection objects be created and disposed as appropriate. I'm surprised that overload even exists myself. I would use the connection string approach.

**Comment by andradf** [comment]
It really was just a novelty find. I already had a class library made that returned new SqlConnections using SqlCredentials instead of having the userId/password in the connection string. But EF really should provide a way to feed a Func<SqlConnection> to UseSqlServer instead of relying solely on connection strings.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by Crono1981** [comment]
This is a huge deal for us as well. We invested a lot around our own connection factory. We would like very much to move to EF Core but NOT at the cost of losing it.

Our factory wraps a SqlConnection instance
and makes it dead easy to set up settings by default so that any queries operates in a culture-invariant kind of way. We also have lots of extensions to facilitate error handling, nesting transactions, leveraging CONTEXT_INFO for auditing purposes... We can't simply turn our back on all of this because there's no way to inject an existing connection instance into DbContext.

This was something that could be done in EF6...
