### ISSUE TITLE
Using "RequireHttpsAttribute" on a global level in Asp.net 4.5 in Azure

### ISSUE THREAD

**Issue by Biranchirparida** [aspnet/Home#1730]
I want to declare in code that I want to require the use of HTTPS.

In the past, I used this in Global.asax.cs:

GlobalFilters.Filters.Add(new RequireHttpsAttribute());
 it is working in local but in Azure Productions  server it is not working

**Comment by GuardRex** [comment]
Using IIS: https://github.com/aspnet/Home/issues/895
Middleware Examples (and MVC filter approach): https://github.com/aspnet/Docs/issues/135 & https://github.com/Sharpiro/ASP5_Template/blob/master/src/ASP5.Template.Security/Middleware/ForceSsl.cs
Regarding Azure (but this one was fixed in 1.0): https://github.com/aspnet/IISIntegration/issues/140#issuecomment-215135928
Additional discussion: https://github.com/aspnet/BasicMiddleware/issues/31

The most exciting approach by @ZestyBread is Rewrite Middleware (releasing in 1.1). Link and video at https://github.com/aspnet/Docs/issues/1839 with discussion in https://github.com/aspnet/BasicMiddleware/issues/43

**Comment by Ponant** [comment]
@GuardRex , is there any performance and parallel requests penalties in using the middleware for redirecting as compared to using the rewrite module in IIS?

**Comment by Tratcher** [comment]
The IIS rewrite module would be more efficient because it runs much earlier in the pipeline.

**Comment by Biranchirparida** [comment]
Thanks guys..hence i am closing the issue
