### ISSUE TITLE
Uninstall ASP.NET Core completely Mac OS X

### ISSUE THREAD

**Issue by ipinak** [aspnet/Home#1746]
Originally I installed ASP.NET Core RC1 (I think that was before the `dotnet` tool). I wanted to upgrade so I have installed the latest however nothing works. I cannot find `dotnet` so I suppose something happened with my `PATH` and my problem is that I cannot find any reference of `dotnet` in order to add it manually in my `PATH`. Therefore I want to delete everything and re-install everything from the beginning. Can someone tell me where I can find everything installed by the installer?

BTW, I'm running on Mac OS X 10.11 with zsh.

I found many references to https://github.com/aspnet/Home/issues/1449 which refers to windows.

**Comment by ipinak** [comment]
I found this which helped https://github.com/dotnet/core/blob/master/cli/known-issues.md

**Comment by goforgold** [comment]
@ipinak the link you shared doesn't exist anymore.

**Comment by mruanova** [comment]
Windows

On Windows, simply use the Add/Remove programs in the Control Panel to remove all the previous versions of the .NET Core bits. Please note that we have changed the name that appears in Add/Remove programs from ".NET Core CLI" to ".NET Core SDK"; please use the latter to search for installed versions to remove.

Ubuntu

In order to make life easier, we have created a script for cleaning up all versions of .NET Core from a machine. You can get the script from https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/obtain/uninstall/dotnet-uninstall-debian-packages.sh. Please note that this will remove any and all previous versions, which means the machine will be cleaned completely of any .NET Core bits. The script needs elevated privileges, so it needs to be run under sudo.

OS X

In order to make life easier, we have created a script for cleaning up all versions of .NET Core from a machine. You can get the script from https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/obtain/uninstall/dotnet-uninstall-pkgs.sh. Please note that this will remove any and all previous versions, which means the machine will be cleaned completely of any .NET Core bits. The script needs elevated privileges, so it needs to be run under sudo.
