### ISSUE TITLE
Using DocumentDB nuget package with ASP.NET core doesn't work.

### ISSUE THREAD

**Issue by wattengard** [aspnet/Home#1751]
I just added the Microsoft.Azure.DocumentDB package to my ASP.NET Core project and everything stopped working. I now get a 500-error at boot saying it can't find version 9.0.0 of Newtonsoft.Json. I can understand this, as the binary being copied to the bin-folder is version 6.0.8, which the DocumentDB package has a dependency on. But why does it stop my previously working app from running?

```
System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0,     Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's  manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
```

**Comment by pranavkm** [comment]
Perhaps you're hitting - https://github.com/dotnet/cli/issues/3674? Could you try deleting your bin directory and rebuilding your project?

**Comment by cwattengard** [comment]
I tried that solution. It still copies the 6.0.8 version of the file.

**Comment by cwattengard** [comment]
If I manually copy the Newtonsoft.Json.dll file from C:\Users\Christian\.nuget\packages\Newtonsoft.Json\9.0.1\lib\net45 it works, but ofcourse it replaces it on every build. Even if I explicitly install Newtonsoft.Json version 9.0.1 in my project, the correct package is nowhere to be seen (except for the nuget cache folder above)....

**Comment by davidfowl** [comment]
Can you make a minimal repro project?

**Comment by cwattengard** [comment]
Oh. I forgot all about this.

I solved it, but it wasn't quite straight forward to find out. I had a data repository project that I added the Microsoft.Azure.DocumentDb package to. However, instead of installing the newest Newtonsoft.Json (9.0.1) it installed the minimum requirement (6.0.8). And this version was copied to the output directory and somehow screwed up the web-project.

After I deleted all references to both Microsoft.Azure.DocumentDb and Newtonsoft.Json from both projects, then added Newtonsoft.Json to the repo-project, and then the Microsoft.Azure.DocumentDb package, then everything works again.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
