### ISSUE TITLE
aspnet CDN doesn't serve gzipped content (for most files I checked)

### ISSUE THREAD

**Issue by gdoron** [aspnet/Home#1774]
@davidfowl 
https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js -compressed
https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.1.1.min.js - not compressed
https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.1.0.min.js - not compressed
https://ajax.aspnetcdn.com/ajax/jquery/jquery-1.9.0.min.js - not compressed

This is quite a big penalty, +56% for the same file.

BTW, is this the right place to report such issues?

**Comment by GuardRex** [comment]
If you don't get an answer here, perhaps they'll comment over at http://forums.asp.net/188.aspx/1?Feedback+on+this+website/

**Comment by muratg** [comment]
@madskristensen Do you know the right contact re: aspnetcdn?

**Comment by gdoron** [comment]
@muratg 
Guys if it won't be fixed soon we will port to a different CDN, probably Google's.
I love Microsoft (most of the days 😄) so I prefer using its CDN and supporting it, but not if this is the cost.

**Comment by muratg** [comment]
cc @DamianEdwards @danroth27 @glennc

**Comment by DamianEdwards** [comment]
@gdoron our CDN essentially exists to allow us to point our Visual Studio templates at a CDN without having to take a 3rd party dependency, and is maintained on a best-effort basis. We're looking in to this issue, however you shouldn't feel compelled to keep using the MS CDN at all, by all means, use whichever CDN you see fit.

**Comment by DamianEdwards** [comment]
I tried those files and they're being served with GZIP compression to my browser (outside MS network). Sometimes files drop off the CDN edge-servers for a given region and don't get cached there again until they're requested. This can result in some requests being uncompressed for some users for a period of time. Perhaps try again?

**Comment by gdoron** [comment]
@DamianEdwards sorry, I was AFK for a day.
Still no compression on my end.

> our CDN essentially exists to allow us to point our Visual Studio templates at a CDN without having to take a 3rd party dependency, and is maintained on a best-effort basis.

Which probably means the CDN infrastructure and reliability is not as good as Google's.
Thanks for sharing this, I'll change to Google's CDN.

BTW, Microsoft can use the CDN as an excellent tracking tool cross websites, not sure why it doesn't leverage and prioritize it.

**Comment by OlegKi** [comment]
Sorry, but I'm wunder, that the problem is still not solved since so long time. First of all I confirm the problem from the German location.

To simplify the troubleshooting I include the information about the CDN servers to which I communicate and compare the loading of jQuery 3.1.1 and jQuery 2.0.0 from ajax.aspnetcdn.com with two other well known public CDNs: cdnjs.cloudflare.com and cdn.jsdelivr.net. By ping on the servers one can see
```
ajax.aspnetcdn.com   -> cs3.wpc.v0cdn.net [2606:2800:133:17a3:eb7:d48:22de:1431]
cdnjs.cloudflare.com -> cdnjs.cloudflare.com [2400:cb00:2048:1::c629:d743]
cdn.jsdelivr.net     -> jsdelivr3.dak.netdna-cdn.com [94.31.29.138] 
```
The loading of jQuery 3.1.1 and 2.2.0 from the CDNs:

URL | Protocol | Size
------------ | ------------- | -------------
https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.1.1.min.js | http/1.1 | 85.3 KB
https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js | h2 | 29.9 KB
https://cdn.jsdelivr.net/jquery/3.1.1/jquery.min.js | h2 | 29.7 KB
https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js | http/1.1 | 38.2 KB
https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js | h2 | 29.7 KB
https://cdn.jsdelivr.net/jquery/2.2.0/jquery.min.js | h2 | 29.5 KB

The HTTP Header of the response on https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.1.1.min.js looks as following:
```
Accept-Ranges:bytes
Access-Control-Allow-Origin:*
Cache-Control:public, max-age=31536000
Content-Length:86709
Content-Type:application/x-javascript
Date:Thu, 20 Oct 2016 10:23:12 GMT
Etag:"2045e8feee18d21:0"
Last-Modified:Tue, 27 Sep 2016 18:43:10 GMT
P3P:CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
Server:ECAcc (arn/45BB)
Strict-Transport-Security:max-age=31536000
VTag:27974956300000000
X-Cache:HIT
X-CCC:SE
X-CID:2
X-Powered-By:ASP.NET
X-Powered-By:ASP.NET
X-Powered-By:ARR/2.5
```
The HTTP Header of the response on https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js looks as following:
````
Accept-Ranges:bytes
Cache-Control:public, max-age=31378454
Content-Encoding:gzip
Content-Length:38396
Content-Type:application/x-javascript
Date:Thu, 20 Oct 2016 10:24:53 GMT
Etag:"87e0a331674ad11:0"
Last-Modified:Fri, 08 Jan 2016 22:52:04 GMT
P3P:CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
Server:ECAcc (arn/46C2)
Strict-Transport-Security:max-age=31536000
Strict-Transport-Security:max-age=31536000
Strict-Transport-Security:max-age=31536000
Vary:Accept-Encoding
VTag:27920057700000000
X-Cache:HIT
X-CCC:NL
X-CID:2
X-Powered-By:ASP.NET
X-Powered-By:ARR/2.5
X-Powered-By:ASP.NET
```
One can see that `Content-Encoding: gzip` is missing in the response on https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.1.1.min.js. Moreover some HTTP headers will be set multiple times (see `X-Powered-By:ASP.NET` and `Strict-Transport-Security:max-age=31536000`)

I includes for better comparing the HTTP2 headers from https://cdn.jsdelivr.net/jquery/3.1.1/jquery.min.js:
```
access-control-allow-origin:*
cache-control:public, max-age=31536000
content-encoding:gzip
content-type:application/javascript; charset=utf-8
date:Thu, 20 Oct 2016 10:14:30 GMT
etag:W/"57e463a5-152b5"
last-modified:Thu, 22 Sep 2016 23:05:09 GMT
server:NetDNA-cache/2.2
status:200
timing-allow-origin:*
vary:Accept-Encoding
x-cache:HIT
```
I hope that the above information will help to localize and to fix the problem on ajax.aspnetcdn.com. Moreover I hope that one will use HTTP2 on ajax.aspnetcdn.com. It's well known that loading on multiple files (it's typically in case of usage CDN) over HTTP2 is much more effectively as over HTTP 1.1.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
