### ISSUE TITLE
Calling DbContext method multiple times with multiple requests inside a middleware will fail

### ISSUE THREAD

**Issue by ahmad-moussawi** [aspnet/Home#1792]
My html page call multiple requests through ajax at the same time,

Implementing a middleware doing certain checks throw an exception due to calling the Db multiple times. [MyMiddleware.cs](https://github.com/ahmad-moussawi/aspnet-test/blob/master/App/MyMiddleware.cs)

*Notes: *
 - Executing one HTTP request at a time, everything goes as expected
 - Executing multiple HTTP requests with a **SYNC** db call, will fail `_db.Projects.ToList()`
 - Executing multiple HTTP requests with a **ASYNC** db call will fail 70% of the time  `_db.Projects.ToListAsync()`
 - Exception thrown may vary between Database Provider, tested on SqlServer 2014 Express, SQlite and Postgres on Mac

I have uploaded a sample project on [Github](https://github.com/ahmad-moussawi/aspnet-test)

Dotnet info:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by khellang** [comment]
The issue here is probably that you're resolving the `ApplicationDbContext` and `ProjectRepo` in the middleware constructor.

AFAIK, middleware is created *once* at application startup, using the application-wide provider. `ApplicationDbContext` is registered as a "scoped" service, which means the same instance is supposed to be used only for a single request, and then disposed as soon as possible.

This means that you're effectively reusing the same `ApplicationDbContext` across all requests. Instead, you'd want to use `app.RequestServices` to resolve the `ApplicationDbContext` and have the provider dispose it for you:

```csharp
public class MyMiddleware
{
    private readonly RequestDelegate _next;

    public MyMiddleware(RequestDelegate next)
    {
        _next = next;
    }

    public async Task Invoke(HttpContext ctx)
    {
        var requestServices = ctx.RequestServices;

        var db = requestServices.GetRequiredService<ApplicationDbContext>();
        var repo = requestServices.GetRequiredService<ProjectRepo>();

        await db.Projects.ToListAsync();
        await db.Projects.ToListAsync();
        await db.Projects.ToListAsync();
        await db.Projects.ToListAsync();
        await repo.GetAsync();
        await repo.GetAsync();
        // db.Projects.ToList();

        await _next.Invoke(ctx);
    }
}
```

You should also be able to inject the services you need in the `Invoke` method. These services are resolved automatically from the `ctx.RequestServices` provider:

```csharp
public class MyMiddleware
{
    private readonly RequestDelegate _next;

    public MyMiddleware(RequestDelegate next)
    {
        _next = next;
    }

    public async Task Invoke(HttpContext ctx, ApplicationDbContext db, ProjectRepo repo)
    {
        await db.Projects.ToListAsync();
        await db.Projects.ToListAsync();
        await db.Projects.ToListAsync();
        await db.Projects.ToListAsync();
        await repo.GetAsync();
        await repo.GetAsync();
        // db.Projects.ToList();

        await _next.Invoke(ctx);
    }
}
```

Also, you should just be injecting `ApplicationDbContext` into `ProjectRepo`, instead of setting it as a property :smile:

**Comment by ahmad-moussawi** [comment]
Thanks @khellang, very informative.
didn't expect to be so easy !!. I think this should be mentioned clearly in the docs.

Yes I was doing this (injecting `DbContext` in `ProjectRepo`) but I added this later to test if sharing the same instance may solve the issue, 
knowing that for `Scoped` lifetime, they will share the same instance, but you know in situation like this, you will try everything :D

anyway thanks for the suggestion :)

**Comment by khellang** [comment]
> I think this should be mentioned clearly in the docs.

Yes. Agreed. I had a look in the docs, cause I wasn't 100% sure about the lifetime of middleware. Ended up finding it [in the code](https://github.com/aspnet/HttpAbstractions/blob/cc295b1bd81c3cd54ed71eab87761e6acbf7a73e/src/Microsoft.AspNetCore.Http.Abstractions/Extensions/UseMiddlewareExtensions.cs#L75).
