### ISSUE TITLE
Missing System.Web.HttpBrowserCapabilities

### ISSUE THREAD

**Issue by GianlucaMaggio** [aspnet/Home#1797]
Have you plan a porting of`System.Web.HttpBrowserCapabilities`? 

Thanks

**Comment by Tratcher** [comment]
No. This is an area that changes too frequently to be built into the main framework. You should find a dedicated library for this.

Anyone have suggestions?

**Comment by davidfowl** [comment]
Do it on the client, sever side detection of specific browser is a never ending battle that doesn't really work. The world has shifted to feature detection instead of browser detection.

If you're trying to port code that uses browser caps to ASP.NET Core, you might re-consider not porting that subset...

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
