### ISSUE TITLE
Starter web project.json template has error/typo

### ISSUE THREAD

**Issue by maumar** [aspnet/Home#181]
Upon creating a starter web project I get the following messages:

The value of property "postrestore" must be a string, but was "[ "npm install" ]",
The value of property "prepare" must be a string, but was "[ "grunt bower:install" ]"

This is regarding the following part of the configuration:

```
    "scripts": {
        "postrestore": [ "npm install" ],
        "prepare": [ "grunt bower:install" ]
```

message is gone if configuration is changed to:

```
    "scripts": {
        "postrestore":  "npm install",
        "prepare":  "grunt bower:install" 
```

**Comment by Praburaj** [comment]
@maumar as @MartinJohns mentioned it is probably because VS might have cached an old version of JSON schema. The latest schema I can see here [http://json.schemastore.org/project] seems to have an array for each of the script nodes. 

```
"script": {
			"type": [ "string", "array" ],
			"items": {
				"type": "string"
			},
			"description": "A command line script or scripts.\r\rAvailable variables:\r%project:Directory% - The project directory\r%project:Name% - The project name\r%project:Version% - The project version"
		}
```

Reloading schema should remove the squiggles from the project.json.
