### ISSUE TITLE
Errors in serialising API Controller return objects are being ignored.

### ISSUE THREAD

**Issue by andrewslavin** [aspnet/Home#1834]
Steps to reproduce:

1. In VS 2015, create new ASP.NET Core website -> Web API.
2. Open ValuesController.cs and add the following class to it:
```
	public class TestClass
	{
		public int Prop1 { get; } = 1;
		public int Prop2 { get; } = 2;

		public int Prop3
		{
			get
			{
				throw new Exception("Not serialisable");
			}
		}
	}
````
3. Change the public Get() method to the following:
```
        // GET api/values
        [HttpGet]
        public TestClass Get()
        {
            return new TestClass();
        }
```
4. Run the website in console (NOT IIS Express). A new console window will open, and a new browser window will open with the url http://localhost:5000/api/values.
5. Expected result: an error gets logged in the console, and the browser gets a 500 response.
6. Actual result:
- The console does log an error "Newtonsoft.Json.JsonSerializationException: Error getting value from 'Prop3' on 'TestWebApiApp.Controllers.TestClass'. ---> System.Exception: Not serialisable".
- BUT the browser gets a 200 response with the body `{"prop1":1,"prop2":2}`.

**Comment by Tratcher** [comment]
There's a common misconception about the expected behavior and a known issue here. 

Misconception: Serialization failures will be converted to 500s. This doesn't happen by default because the response body is not buffered. The first two properties are serialized and sent to the client (along with the headers). By the time it gets to the third property and fails all it can do is log the error, and abort the connection, the status code and headers can't be changed. Not all clients report the premature connection termination.

There's a related issue (https://github.com/aspnet/Mvc/issues/5413) where the JSON gets closed gracefully even for an exception before the connection is terminated. Assuming we can get that fixed it should become more evident to the client that the response was truncated.

**Comment by andrewslavin** [comment]
@Tratcher thank you for quick response. When I was investigating this, I did discover that the response is not being buffered. I would disagree though that expecting a serialisation error as a 500 response is a misconception. Runtime errors should be returned as 500 response. Absence of buffering is the reason the issue is hard (or maybe impossible?) to fix, but not an excuse :).

I tested the same scenario in ASP.Net MVC 5 + WebApi 2, and the response is as expected:
- Status code: 500
- Body: {"Message":"An error has occurred.","ExceptionMessage":"The 'ObjectContent`1' type failed to serialize the response body for content type 'application/json; charset=utf-8'.","ExceptionType":"System.InvalidOperationException","StackTrace":null,"InnerException":{"Message":"An error has occurred.","ExceptionMessage":"Error getting value from 'Prop3' on 'TestWepApiSite.Controllers.TestClass'.","ExceptionType":"Newtonsoft.Json.JsonSerializationException","StackTrace":"   at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)\r\n   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)\r\n   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)\r\n   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding)\r\n   at System.Net.Http.Formatting.JsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding)\r\n   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content)\r\n   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at System.Web.Http.WebHost.HttpControllerHandler.<WriteBufferedResponseContentAsync>d__1b.MoveNext()","InnerException":{"Message":"An error has occurred.","ExceptionMessage":"Not serialisable","ExceptionType":"System.Exception","StackTrace":"   at TestWepApiSite.Controllers.TestClass.get_Prop3() in c:\\users\\andrew.slavin\\documents\\visual studio 2015\\Projects\\TestWepApiSite\\Controllers\\ValuesController.cs:line 49\r\n   at GetProp3(Object )\r\n   at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)"}}}

**Comment by davidfowl** [comment]
ASP.NET 4.x buffers the entire response body in memory unless somebody calls flush or the response ends.

**Comment by andrewslavin** [comment]
@davidfowl yes, I understand why things work the way they do in ASP.Net 4 and ASP.Net Core. I agree that's the reason for different behaviours, I just disagree that it can be used as an excuse to leave the ASP.Net Core behaviour as is. Why not add buffering? Is it impacting performance? If yes, maybe make it configurable from Startup.cs.

**Comment by davidfowl** [comment]
> Is it impacting performance?

Yes. It's already configurable. Though we haven't shipped the middleware as yet https://github.com/aspnet/BasicMiddleware/tree/dev/src/Microsoft.AspNetCore.Buffering

**Comment by andrewslavin** [comment]
@davidfowl sounds good! How soon can we expect this?

**Comment by davidfowl** [comment]
I don't have a timeline, we just shipped 1.1 and are planning the next release (whenever that may be). I'll make sure this middleware gets added to the list /cc @DamianEdwards

**Comment by halter73** [comment]
@andrewslavin @davidfowl We haven't shipped a 1.1.0 version of the package, but [Microsoft.AspNetCore.Buffering is available on NuGet.org](https://www.nuget.org/packages/Microsoft.AspNetCore.Buffering/).

**Comment by andrewslavin** [comment]
Thanks @halter73. If it's already available on NuGet.org, does it mean it's ready to be used? On the other hand if it is, why didn't it make the 1.1.0 release? I'm just trying to avoid using something that might significantly change or disappear completely.

**Comment by DamianEdwards** [comment]
The buffering middleware is still at beta level. It needs to go through a round of stress & performance optimization before we bring it up to a 1.x. If you don't care about paid support, I'd encourage you to try it out in your environment to see if works for your scenarios, and provide any feedback you might have.

**Comment by andrewslavin** [comment]
@DamianEdwards sorry I know this question is not related to the above discussion, but posting it on StackOverflow resulted in zero responses. Maybe you know the answer?

At some point ASP.Net Core had an option to deploy as source code. In fact, it was the default. Then it got removed. Do you know whether if it's coming back, and if not - why. I was really looking forward to it.

**Comment by chrisckc** [comment]
@andrewslavin I agree that this should be configurable without relying on adding Response Buffering middleware, i also think the default should setup should us Response Buffering, there are too many different clients out there that behave differently when they encounter a missing chucked transfer terminator

I have just posted in [https://github.com/aspnet/Mvc/issues/5413](https://github.com/aspnet/Mvc/issues/5413) with the results of some testing i have done using various clients. I have also just added an additional test to mirror yours to the repo i created to demo the same issue caused by a reference loop during serialization. I can confirm that i also see the same results as you:

```
{
  "prop1": 1,
  "prop2": 2
}
```
prop3 is missing and i see the exception in the debug log but its not possible to catch it in an exception handler.

When i use Response Buffering by adding:
"Microsoft.AspNetCore.Buffering": "0.2.0-preview1-final"
to project.json and adding app.UseResponseBuffering(); to the Configure method in Startup.cs I get a 500 status code and the developer exception page kicks in:

```
Exception: Not serialisable
GetValue
JsonSerializationException: Error getting value from 'Prop3' on 'TodoApi.Models.NotSerializable'.
```

If i had an exception handler plumbed in then that would be fired
