### ISSUE TITLE
What is the difference between ASP.NET Core for Windows and for Cross Platforms (Win/Mac/Linux)

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#1847]
I'm curious because deciding on the framework, I would like to know what I am giving up if I choose to go for the ASP.NET Core for Linux... I would like to know the gaps. I tried to search on the web but to no avail.

Thanks for all your hard work and for giving us 1.1
Happy Thanksgiving

**Comment by Tratcher** [comment]
At a high level the differences are environmental, like if you're going to proxy behind IIS vs NGinx or Apache. Otherwise all of our major packages and components are supported on all of the listed platforms and frameworks. There may be subtle behavioral differences for OS dependent features (e.g. file watchers).

The biggest gap right now is in ecosystem. The .NET Core / Cross plat echosystem is still fairly new and many .NET 4.x 1st and 3rd party libraries have not yet been ported over. Check your dependencies and see if they're available.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
