### ISSUE TITLE
Configuration File Fatigue

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Home#1887]
As I've been introducing .net Core and ASP.net Core to my team at work, I've had a chance to go through many of the first time learning experiences again.

As a result of this, one thing I thought it might be worthwhile to mention the concern of "config fatigue" which also came to mind briefly in this sub-thread: https://github.com/aspnet/Tooling/issues/629#issuecomment-267832823
_I did a quick search to see if this has been discussed in any way, but I either didn't use good enough terms or it hasn't come up yet._

The move back to msbuild from `project.json` seems like it could be an opportunity to consolidate some of these things into one cascading format.  Specifically, I'm talking about `csproj`, `globals.json` and `Nuget.Config`.  I'm not sure if there are any more, but three is enough at this rate.

While I understand that there's a reason for files to exist at different levels, the trick here is to have them as a single format.  This also helps to avoid formats-per-team/project as well as the cognitive overhead while working in multi-project situations.  Then, any current build context would be built up according to something similar to `.htaccess` or `Web.Config` semantics.

Apologies if this is a redundant topic or covering a ship that's already sailed, feel free to close/move/correct as appropriate. 😄

**Comment by davidfowl** [comment]
- csproj is already in the msbuild format that isn't changing (at least not in the short term)
- `global.json` is a dotnet CLI format, only thing it will determine in the future is the version of the dotnet CLI to use. We could make it the msbuild format but that's just abuse.
- NuGet.config is a nuget configuration file. You'd need to introduce a new format since this file format has existed for > 4 years. I also don't see this going to the msbuild format.

There's no good place to file this bug, you need to file several bugs but the ASP.NET repository isn't the right place for any of them. Try 

- http://github.com/nuget/home
- http://github.com/dotnet/msbuild
- http://github.com/dotnet/sdk
- http://github.com/dotnet/cli

**Comment by Matthew-Bonner** [comment]
You could also easily get msbuild to read JSON files in addition to XML files, I agree that this is an issue and having to explain to a team why you have "settings" and "configuration" files which can be either XML or JSON is pretty annoying, never mind having to work with multiple formats.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
