### ISSUE TITLE
Cannot get IMvcBuilder during service config

### ISSUE THREAD

**Issue by denisz1** [aspnet/Home#1932]
I am trying to [add new customisable config](https://github.com/JeremySkinner/FluentValidation/issues/404) to FluentValidator library.

In `Startup.ConfigureServices()` there is:

    services.AddMvc(cfg  => { /* ... */ });
    // ...
    var mvcBuilder = services.BuildServiceProvider().GetRequiredService<IMvcBuilder>();

*I do not know why, but `mvcBuilder` is null.*

Is this by design? Is there another way to get it?

**Comment by davidfowl** [comment]
IMvcBuilder isn't a service and you can't configure services mvc that late. Why are you building the service provider in configure services? That builds a new service provider that will share nothing with the real one. What are you trying to do?

**Comment by denisz1** [comment]
Usual way in `Startup`:

    public void ConfigureServices(IServiceCollection services)
    {
      // add options, dbcontext, identity, etc.
      services.AddMvc();                                      // returns IMvcBuilder
      // more custom services register now
    }

Most Core libraries are config direct off `IServiceCollection`, like that:

    services.AddFoo();
    services.AddBar(s => /* ...*/);

But the [FluentValidation](http://github.com/JeremySkinner/FluentValidation/) wants `IMvcBuilder`, so must config like that:

    services
        .AddMvc()
        .AddFluentValidation();

So is strong coupled to the MVC, and harder for us to do complex config, where we have config in other classes etc. We want to configure it like all the libraries do:

    services.AddMvc();
    // and later...
    var mvcBuilder = services.BuildServiceProvider().GetRequiredService<IMvcBuilder>();
    // ...and use that to config FluentValidation

But `mvcBuilder` is null.

You say it is not a service. Is there any way to "get" it, or do I lose that info after the `AddMvc()` call?

**Comment by denisz1** [comment]
I am doing this:

    var mvcBuilder = services.AddMvc();
    // and use it later

But I was wondering why is null in above example.

**Comment by davidfowl** [comment]
> You say it is not a service. Is there any way to "get" it, or do I lose that info after the AddMvc() call?

You lose it after `ConfigureServices`.

**Comment by denisz1** [comment]
@davidfowl Yes but I'm still in `Startup.ConfigureServices`.

While I'm in there, is the only way to get it by saving the return of `AddMvc()`?

**Comment by rynowak** [comment]
`IMvcBuilder` is used to configure services. That is it's purpose. 

If you are trying use the builder outside of the scope of configuring services during the `ConfigureServices` method, it won't do what you want.

**Comment by MBODM** [comment]
The concerns here are completely understandable in my oppinion.

I have the same problem when i want to build a simple wrapper library that do setup for localization. In this case i need to write an extension method for IServiceCollection named "AddSimpleLocalization". No problems here. That method do the setup for a shared resource, register a type that wrapps IStringLocalizer etc. No problem. 

But when i now want to also setup "AddDataAnnotationsLocalization()" i have to call this method on IMvcBuilder, because he is the one that offers that method. And obviously this is not possible outside of "AddMvc()" in Startup.cs.

So plz tell us: How will ppl do such stuff in a library when they can not get IMvcBuilder outside of "ConfigureServices" ? 

This is a typical and valid concern and i am shocked that there is no solution for that !?!

**Comment by davidfowl** [comment]
I don’t understand the concern. Can you elaborate?

**Comment by MBODM** [comment]
The concern is: How do you develop and deliver a library, that needs to config mvc, when you have no access to the MvcBuilder outside of ConfigureServices() and AddMvc() ?

Maybe this is already possible with 2.1 and i do not know it. But like it seems we can not either get the MvcBuilder via DI, nor is there a concept or something like i.e. with the HttpContextAccessor, to reach the MvcBuilder.

This means, when we need to bring in some Mvc configuration, included in a lib / NuGet package, we just can not do this.

My example above is a small lib, that takes all the glue code stuff away from users, when they just want to use easy localization with the shared resources approach. Therefore the library offers a service you just can add („services.AddSimpleLocalization()“) in Startup.cs in ConfigureServices(). To achieve this, my lib has also to configure Mvc to use localization for DataAnnotations, via a „services.AddMvc().AddDataAnnotationsLocalization()“ call. But how will i do this in my lib, when i only have access to the MvcBuilder as result of „AddMvc()“ in ConfigureServices() ?

**Comment by davidfowl** [comment]
> The concern is: How do you develop and deliver a library, that needs to config mvc, when you have no access to the MvcBuilder outside of ConfigureServices() and using the AddMvc() result ?

You write an extension method on IMvcBuilder like the other things that extend MVC.

> Maybe this is already possible with 2.1 and i do not know it. But like it seems we can not either get the MvcBuilder via DI, nor is there a concept or something like i.e. with the HttpContextAccessor, to reach the MvcBuilder.

That's because MVC is already configured by the time the container is built. 

> My example above is a small lib, that takes all the glue code stuff away from users, when they just want to use easy localization with the shared resources approach. Therefore the library offers a service you just can add („services.AddSimpleLocalization()“) in Startup.cs in ConfigureServices(). To achieve my goals, my lib has also to configure Mvc to use localization for DataAnnotations, via a „services.AddMvc().AddDataAnnotationsLocalization()“ call. But how will i do this in my lib, when i only have access to the MvcBuilder as result of „AddMvc()“ in ConfigureServices() ?

You write an extension method on top of `IMvcBuilder` which gives you access to the entire service collection if you need to add services https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.imvcbuilder?view=aspnetcore-2.1.

> In short: How can we configure the MVC system outside of Startup.cs (i.e. in libs) ?

Hopefully it's clear now how to do it with the above explanation things are clearer. You're not trying to configure MVC outside of Startup, you're trying to expose an extension method that can be called from  any users's Startup.

**Comment by MBODM** [comment]
Hi,

thx for the quick response! Ofc you can write an extension method for IMvcBuilder. That‘s obvious. But that don‘t solve the problem that you can’t offer the user a configuration outside of Startup.cs file.

Whatever you do, you force the user to call stuff on AddMvc(). You can’t configure the system for him. And imo that‘s not great. Both as from a sw design point of view, as also from a sw principles point of view.

Also it splits stuff that usually shouldn’t be splitted. Since you nearly always have to register a service too (in ConfigureServices(), i.e. a call like „services.AddSimpleLocalization()“ or something along those lines), it sucks that you can not configure Mvc stuff already there too, in this service setup.

Normally a good lib gives the user one entry point, one quick setup, one single step to use your stuff. You don‘t wanna tell the user he have to add stuff here, and there, and there, and so on. Imo a user shouldn‘t have the need to add a configuration explictly to AddMvc(), when he already have added a middleware, or registered a service. If the user would ask me „why i habe to do that, why can‘t you do this for me instead?“ i have to say that this would be a fair question.

Besides my opinion that .NET Core already makes way too much use of extension methods (which are not always the best approach in a well formed architecture), for config purposes like this, it‘s in my opinion even more the wrong tool. Some sort of central entry point, with access to all service and config stuff from the framework, would make more sense to me here.

I.e. look at the HttpContext. It offers a central access point to ModelState, Request and all Request information, authorization, route, etc. in one place. Its automatically reachable in every controller and also everywhere outside via IHttpContextAccessor. Imo that is good library design. It works contextual in controller. It works with DI. And therefore it offers users the possibility to enhance it, by accessing it via DI/IHttpContextAccessor in a library, while the lib could be used by adding to the DI too. All principles of modern sw design achieved.

Long story short: It seems the design philosophy behind .NET Core is „you have to configure stuff in startup.cs. period.“. Imo this is not loose coupled enough and it remembers me somewhat to the MFC templates from the past, where you had to put your own code into it. But when this is the way to go, and we have to put stuff into startup.cs at 3-5 different places, to setup one thing a lib want to offer, well... than that‘s this.

And just for the sake of not missunderstanding me: The real question was „Is there a way to configure Mvc stuff outside of AddMvc() ?“ because i just wasn’t sure if that‘s the philosophy or if i just don‘t know a better way. So, no offense here. Just the missing knowledge that there is no other way than that.

PS: And maybe i could find a better way to achieve my goals via a global tools aproach in 2.1.

So, thx for all your patience and the time you invested! Really glad to see how well the devs and the community on .NET Core evolved and how all works in this open source fields. I really have to say that you guys do a damn great job! As developers as well as „supporters and speakers“ in front of the community. The way that MS started to go is definitely the right way! Imo, all what you guys achieved in the last 2 years is absolutelly industry leading! Without any doubt. Great work!

**Comment by davidfowl** [comment]
This is a difference in design opinions so we'll have to agree to a disagree here. The pattern is to add an extension method to either a builder on IServiceCollection or on the IMvcBuilder directly. There's no model for breaking startup into multiple components (order also gets tricky in that case). Thanks for the feedback regardless.

> PS (since i talk to David Fowler here^^): And thx for all the things you make possible and achievable to me as a developer! I started a new job in a startup in late 2016 and we decided to bet on .NET Core, even when it was risky. No disappointment. We reached all goals and it worked out very well. I had 2 fantastic years in my life and appreciated the work with all the new stuff, as a developer with nearly 20 years of exp. As a developer, i really look into the future with a bright smile on my face. :) Thx for that!

Great to hear!

**Comment by tb-mtg** [comment]
@denisz1 @davidfowl @MBODM 
This is an old question I know, but is this how to do it?

`services.AddMvc(cfg  => { /* ... */ });`

and then elsewhere inside Startup.ConfigureServices()

```
services.Configure<IMvcBuilder>(o => {
  o.AddFluentValidation();
});
```

**Comment by rynowak** [comment]
**Hi, it looks like you are posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

Thanks!
