### ISSUE TITLE
Failing to install Visual Studio 2017 component: Microsoft ASP.NET Core Module for IIS Express error

### ISSUE THREAD

**Issue by Anders2020** [aspnet/Home#1974]
Error during 2017 install.
Product: Microsoft ASP.NET Core Module for IIS Express -- IIS Express 8.0 or higher is not installed.
Log file is attached

[dd_setup_20170317200146_002_Microsoft.Ancm.IISExpress.Msi.zip](https://github.com/aspnet/Home/files/851717/dd_setup_20170317200146_002_Microsoft.Ancm.IISExpress.Msi.zip)

**Comment by Tratcher** [comment]
@pan-wang @joeloff

**Comment by joeloff** [comment]
@Anders2020 Can you attach the primary log from the bundle?

IIS Express should be installed prior to ANCM

**Comment by Anders2020** [comment]
Thanks for initial response find attached all logs

[dd_All.zip](https://github.com/aspnet/Home/files/852165/dd_All.zip)

**Comment by mmmcorpsvit** [comment]
have same problem on Window 7 x64(
problem fix if install clear Window 7 x64 and do all updates and then install VS, but this way not for me...
please very need fix

**Comment by joeloff** [comment]
@Anders2020 ANCM is detecting that 10.0.1737 is installed. I'm looping in the owners of ANCM

MSI (s) (A8:24) [19:55:50:770]: PROPERTY CHANGE: Adding IISEXPRESS_INSTALL property. Its value is '10.0.1737'.

@pan-wang Can you take a look? I looked at the logs already and here's what I found

1. ANCM (x64) is setting IISEXPRESS_INSTALL_PATH32, but never sets IISEXPRESS_INSTALL_PATH (which I assume is the 64-bit property).
2. The launch condition in the x64 MSI checks for Installed OR IIS_EXPRESS_INSTALL_PATH and so it fails.
3. Other properties like IISEXPRESS_APPHOST_CONFIG and IISEXPRESS_APPHOST_CONFIG32 are both being set correctly. Looks like a problem with the 64-bit search.
4. The AppSearch table in the MSI show both IISEXPRESS_INSTALL_PATH and IISEXPRESS_INSTALL_PATH32.
5. The DrLocator in the MSI seems to have both 32-bit and 64-bit searches, but the 64-bit searches are never executed according to the log.

**Comment by Anders2020** [comment]
thanks man waiting patiently

**Comment by pan-wang** [comment]
Could you please update with OS information?

Per the log, it seems ANCM for IISExpress was installed multiple time even before IISExpress was installed. There must be something wrong here.

Inside dd_setup_20170317195428_003_Microsoft.Ancm.IISExpress.Msi.log, ANCM installer did detect IISExpress 10.0.1737 was installed. However, the file version comparison failed (i.e., 10<8?). Need to dig the root cause of this comparison failure.


Thanks


Pan




________________________________

**Comment by Anders2020** [comment]
Windows 10 x64

**Comment by pan-wang** [comment]
Did you delete C:\Program Files\IIS Express\iisexpress.exe before installation


________________________________

**Comment by Anders2020** [comment]
No just uninstalled from add remove programs and features

**Comment by sujitnayak** [comment]
Hi @Anders2020, can you please tell us the file version of C:\Program Files\IIS Express\IISExpress.exe. To get the file version, right click on the file in Explorer, click Properties and go to the Details tab.

**Comment by Anders2020** [comment]
x86 = 10.0.14358.1000
x64= 10.0.14358.1000
both fileversion and product version match respectively

**Comment by sujitnayak** [comment]
@Anders2020 - Thanks, based on the logs, my theory is that iisexpress.exe in "c:\program files\iis express" folder was in use during the VS install. You likely had an older version installed on your machine before you tried to install VS. This caused the iisexpress.exe binary update to get deferred to post-reboot which caused the following ANCM package install to fail since it checks to make sure iisexpress.exe is the right version before proceeding.

Could you please try the following the confirm this theory:

1. Reboot the machine (not strictly required now but just to be on the safe side).
2. Uninstall you current VS instance.
3. Reinstall VS with the same workload.

Please let us know the results after this. Thanks.

**Comment by Anders2020** [comment]
Fixed by 
1) Rebooting
2)Uninstall
3)Reboot
4)Delete IIS Express folders in program files both x86 and x64
5)Install

Thanks all for help
