### ISSUE TITLE
Feature that enables library authors to include UI on packages.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Home#2030]
I strongly believe that asp.net mvc framework is missing the ability to packing UI assets (Views) on libraries as first class citizen support. I think there's great opportunity to improve quality and enable innovation in multiple libraries.

Now it could be a great timing to implement said feature since IdentityService team can benefit from it, which is a strong indicator of being a missing feature.
https://github.com/aspnet/Identity/issues/1187#issuecomment-300676575

@danroth27:
>We are also looking at ways to package the controllers and views so they don't have to live in the template.

**Comment by sebastienros** [comment]
Watch this video https://channel9.msdn.com/Shows/On-NET/Sbastien-Ros-Modular-ASPNET-apps

Is this what you want?

**Comment by Bartmax** [comment]
@sebastienros as addresses here: https://github.com/aspnet/Identity/issues/1187#issuecomment-300962769

> The need to reference two different packages, inject services, have a middleware running to get the concept of modules on an application may be fine but not to package a library with controller(s) and view(s). 

As this scenario would enable.

**Comment by Bartmax** [comment]
Just to be clear, I don't know what the `IdentityService` team will end up doing and how they will end up solving this problem. I can think of many ways to do it with pros/cons. What I'm asking is whatever effort is put into it, consider enabling it for 3rd party author too so we can all benefit from it and not being specific.

**Comment by sebastienros** [comment]
To mark something as a module we now use a single nuget package. Internally it's just adding a .props file that will handle the local deployment of static assets in the targeted app and also the packaging.

And as a module author you don't add services or middleware if you don't want to. Maybe the team will come with some hard coded magic to handle Identity in a better way, otherwise I don't see how it can be simpler.

The host application needs a middleware because of multitenancy. Probably something you don't care about and would rather not see. Internally we just make it no-op if there is a single tenant, but not as clean as having nothing at all.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
