### ISSUE TITLE
asp.net core ServerGarbageCollection not working

### ISSUE THREAD

**Issue by 1amirjalai** [aspnet/Home#2056]
Asp.net core 1.1.2
windows server 2016

after migrating my project from vs 2015 to 2017 i made a release and published my website but now memory usage constantly grows in production server.

At vs 2015 i had this in my project.json :

```
  "runtimeOptions": {
    "gcServer": true
  },

```

but after migrating to vs 2017 csproj is like this

```
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>xxxxx</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>xxxxx</PackageId>
    <UserSecretsId>xxxxxxx</UserSecretsId>
    <RuntimeFrameworkVersion>1.1.2</RuntimeFrameworkVersion>
    <PackageTargetFallback>$(PackageTargetFallback);dotnet5.6;dnxcore50;portable-net45+win8</PackageTargetFallback>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>
```
i also changed csproj to this in another test:

```
  <PropertyGroup>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
  </PropertyGroup>

```
and runtimeconfig.template.json to this :

```
{
  "gcServer": true,
  "System.GC.Server": true,
  "gcConcurrent": true
}
```

but garbage collection is not working. any idea what is going wrong?

**Comment by davidfowl** [comment]
How do you know it isn't working? 

@Maoni0  @jkotas is there a runtime API to check what GC mode is enabled to see if configuration settings are effective?

**Comment by 1amirjalai** [comment]
I had a similar issue (high and growing memory usage) in vs 2015 so setting   "gcServer" to true solved the problem.
And now the only thing that has changed in my project is migrating from vs 2015 project.json to vs 2017 csproj.

the app was working without high memory usage  from the previous release until now which i migrated to vs 2017 and publish the app again.

before migration the memory usage was around  400 Mb

and now its around 1685904 and growing

also i have an api checking these two vars 

```
        var latencyMode = System.Runtime.GCSettings.LatencyMode;
            var isServerGC = System.Runtime.GCSettings.IsServerGC;
```

>       latencymode is  Interactive isServerGC is True      

is there anything else i can check ?

**Comment by Maoni0** [comment]
Interactive and IsServerGC being true means you are using Concurrent and Server GC. Sounds like there are 2 issues -

1) Locally you are seeing high memory usage again after upgrading from VS2015 to VS2017 (and presumably you were using Concurrent and Server GC when you were using VS2015). Do you happen to have some comparison perf data? eg, process dumps, ETW traces?

2) On production, you'd like to find out if you are using Concurrent and Server GC. If you don't have the option to add these 2 variables, do you have the option to take a process dump?

**Comment by 1amirjalai** [comment]
@Maoni0 
1. locally (on the dev env) i don't see any high memory usage only on production and on the sever. on dev i didn't make any process dump but on production i made a dump after this issue the dump file size is around 2.25 Gb.
2. on production i have added these two vars and  "latencymode   Interactive and isServerGC   True" is on production. yes on production i have made process dump. what to look after?

**Comment by Maoni0** [comment]
ahh, so I totally misunderstood you then. The 2 vars you added are enough to confirm that you are using Concurrent Server GC. Note that the first mode (Interactive) can be changed by some code but the Server GC part is not changeable after the process starts. You can confirm by looking at callstacks in the process dump you took and you should see a few callstacks that have SVR::gc_heap::gc_thread_function on them. if SVR::gc_heap::settings.pause_mode is pause_interactive, it means you are using concurrent.

**Comment by 1amirjalai** [comment]
@Maoni0 
I did stress test on dev env today the memory usage didn't go further than 300Mb but on production memory usage constantly growing

**Comment by 1amirjalai** [comment]
here is a memory dump

![memory](https://user-images.githubusercontent.com/2786675/27079437-e1c9e610-504c-11e7-8c33-c4f3c54a13c8.PNG)

**Comment by 1amirjalai** [comment]
beside installing DotNetCore.1.0.5_1.1.2-WindowsHosting.exe

dotnet sdk is also installed on my server with this version

running dotnet --info on command line shows

```
.NET Command Line Tools (1.0.0-preview2-003156)

Product Information:
 Version:            1.0.0-preview2-003156
 Commit SHA-1 hash:  33dabee5d8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

can it be the reason not functioning well?

**Comment by Maoni0** [comment]
@swgillespie could you please help @1amirjalai with doing some perf investigation here? thanks!

**Comment by swgillespie** [comment]
@1amirjalai 

For troubleshooting GC issues I'd definitely recommend using PerfView: https://github.com/Microsoft/perfview#getting-perfview . With PerfView you can analyze your heap dumps or capture a live trace where you can see why GCs are happening (or not happening). With your scenario running, you can collect a GC trace using the command

```
PerfView.exe /GCCollectOnly /nogui /NoV2Rundown /NoNGENRundown /NoRundown /merge:true /zip:true collect
```

You can then open this trace in PerfView and look at the "GcStats" view (see [here](http://www.philosophicalgeek.com/2012/07/16/how-to-debug-gc-issues-using-perfview/) for an example). If GCs are occuring, you'll see in this view where they occurred and what triggered them. I'd definitely recommend you taking a trace like this; from there we can take a look and see what's going on in your process.

Without any data, though, I *can* say that in general Server GC will favor latency and throughput over heap size. If the GC thinks that the machine has enough memory, it will feel more free to allow the heap to expand in order to avoid compaction. If you want to limit the memory consumption of your application, you can use job objects to do so and the GC will respect the limits that you set, compacting the heap if your memory usage approaches the job object limit.

**Comment by 1amirjalai** [comment]
@Maoni0 @swgillespie  here are the results of :

`PerfView.exe /GCCollectOnly /nogui /NoV2Rundown /NoNGENRundown /NoRundown /merge:true /zip:true collect`

<img width="787" alt="perf1" src="https://user-images.githubusercontent.com/2786675/27181828-8237c69c-51ee-11e7-87ff-0cc7b3e32813.PNG">

<img width="791" alt="perf2" src="https://user-images.githubusercontent.com/2786675/27181729-0eddc610-51ee-11e7-9f94-1ef15a3cdb0c.PNG">
<img width="789" alt="perf3" src="https://user-images.githubusercontent.com/2786675/27181743-15663512-51ee-11e7-8dc3-e361fbb2210b.PNG">
<img width="800" alt="vmmap" src="https://user-images.githubusercontent.com/2786675/27181749-1f46c3d0-51ee-11e7-8f37-13acf7adc12a.PNG">

The app source code hasn't changed from project.json to csproj but memory consumption has changed a lot.
event dot.net version is the same.

has gc behavior changed from project.json to csproj?

**Comment by swgillespie** [comment]
@1amirjalai Apologies for the late response, I just found out that GitHub failed to deliver this notification to me because of some obscure settings I have set... I'm taking a look at this today and I'll write a response this afternoon.

**Comment by swgillespie** [comment]
@1amirjalai 

It looks like there's a period of 40 seconds in which your application allocates 1GB in Gen 0 and doesn't take a GC in that time. I see that you have at least 24 heaps; how many cores does this machine have?

Server GC aggressively parallelizes across all cores that you have and creates a logical heap for every core. Your allocation rate of 28 mb/s is quite low given the number of cores you have on your machine. Since each one of these heaps has a (quite high) gen 0 budget, and you are allocating at only 28 mb/s, it's not surprising that it would take so long for a GC to be triggered - Server GC does not believe one is necessary due to the preponderance of resources available to it (both memory and CPU time).

> has gc behavior changed from project.json to csproj?

No, the GC operates at a lower level of abstraction than the CLI and is not aware of project.json or csproj, or even how the application is run. However, the speed in which Gen 0 collections are triggered is dependent entirely on the gen 0 budget size for each of the various server GC heaps, and this number is very sensitive to your environment.

Can you show a trace of this same process where you see that the memory usage is lower, so we can compare these two traces?

**Comment by 1amirjalai** [comment]
@swgillespie sorry for late response i was doing some reading on the windows internals.

The system i'm using has 24 cores and 256 Gb of ram.

> Can you show a trace of this same process where you see that the memory usage is lower, so we can compare these two traces?

I wasn't able to open previous dump files using perfview for getting gc info.

**Comment by 1amirjalai** [comment]
I made another dump today and i don't know it's related or not but now i'm getting a deadlock

```
OS Thread Id: 0x18e68 (27)
        Child SP               IP Call Site
000000e1b8bfeeb8 00007ffa506f6c24 [GCFrame: 000000e1b8bfeeb8] 
000000e1b8bfef88 00007ffa506f6c24 [HelperMethodFrame_1OBJ: 000000e1b8bfef88] System.Threading.Monitor.ObjWait(Boolean, Int32, System.Object)
000000e1b8bff0b0 00007ff9d51c36c1 StackExchange.Redis.SocketManager.WriteAllQueues()
000000e1b8bff100 00007ff9d51c3407 StackExchange.Redis.SocketManager+c.b__27_0(System.Object)
000000e1b8bff140 00007ffa1c5b16ee System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
000000e1b8bff390 00007ffa3490cb13 [GCFrame: 000000e1b8bff390] 
000000e1b8bff668 00007ffa3490cb13 [DebuggerU2MCatchHandlerFrame: 000000e1b8bff668] 
```

**Comment by swgillespie** [comment]
@1amirjalai 

Unfortunately there's not a whole lot we can be sure of without a trace, but running witih server GC on a machine that powerful results in a GC that is capable of servicing a high (on the order of GB/s) allocation rates, and is tuned to that scenario. If you don't allocate much, you won't GC much. Server GC generally runs under the assumption that it has full control over all cores and memory of the machine and, as such, it won't GC if it doesn't think it needs to (and on a machine that huge, there's hardly any reason to - if there's memory to use, might as well use it).

If you want to limit the amount of memory that your process uses, you can consider using a job object. If you put your process in a job object and limit the job object's memory to something lower than the amount of RAM on the machine, the GC will respect that limit and GC more aggressively. At the moment, there's no way to ask the GC to be more frugal with memory; there have been some issues on the CoreCLR repo discussing this as a possible feature for the future, though.

**Comment by Ettery** [comment]
How does the GC view the machine specs when running in a Docker container?  Does every run-time think it has use of all the host resources?   I ask because I'm running a number of simple APIs (microservices) on Docker on Ubuntu, and each container is consuming 500-900 Mb of memory.  It's not a powerful server - 16Gb/4 cores at the moment.  CPU usage is under 5% but I'm hitting memory limits.  I've not been able to find a solution yet.  I can tell Docker to limit the memory available to each container, but what I see is that they don't seem to use less memory, they just start using swap space, which will hurt their performance.

**Comment by Maoni0** [comment]
https://github.com/dotnet/coreclr/issues/9719 added supported for containers; but there was a bug described in https://github.com/dotnet/coreclr/issues/13489 which was fixed. Perhaps you are hitting #13489?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
