### ISSUE TITLE
Static Code Analysis

### ISSUE THREAD

**Issue by bloudraak** [aspnet/Home#2074]
It would be really beneficial for organizations that work in regulated industries, e.g. defense, healthcare, finance or legal if all aspnet core, or even all of dotnet core were statically scanned and the results were published.  Some may debate the usefulness of such tools, but regardless, it is often a requirement for any code to be deployed to production, nevertheless.  And there have been times when these tools actually discovered defects.

Coverity (https://scan.coverity.com) does this for open source projects. 

(I have no relationship with Coverity)

**Comment by MaximRouiller** [comment]
What is your use case? Is it a requirement before you can deploy .NET Core applications? Did you find some particular code quality issue? How high in terms of priority should this rank compared to existing issues?

The team has a lot of work to do and these kinds of point would help them prioritize these kinds of requests. I'm all for Static Code Analysis, but I also want the team to focus on tasks that bring value to the whole ecosystem.

**Comment by MaximRouiller** [comment]
@bloudraak Statically analyzed code is a requirement before you can use .NET Core (at all) on your end? 

I'm wondering how many like you are blocked from using .NET Core because of this. 

Until a decision is made or a confirmation given that the code is analyzed, here's your option. It's relatively *easy* to either build/analyze yourself or just `git clone` and analyze the repositories on which you depend. It's not a ubiquitous as having it done every build but, it's a workaround for now.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
