### ISSUE TITLE
IIS interaction

### ISSUE THREAD

**Issue by Rovastar** [aspnet/Home#2091]
Finally (/sadly) I have to start using .NET core now to host stuff. Been following it for many years but like many others in the IIS support community have been keeping at arms length and seeing how your little project pans out.

Are there any plans for proper IIS interaction for asp.net core stuff?

GUI stuff, similar information/diagnostic tools, WPI install components, etc. Stuff that over the decades I have been used too.

**Comment by davidfowl** [comment]
> Are there any plans for proper IIS interaction for asp.net core stuff?

There are no plans to bring back an integrated pipeline if that's what you mean.

> GUI stuff, similar information/diagnostic tools, WPI install components, etc. Stuff that over the decades I have been used too.

Can you be more specific here? I'm not exactly sure what you mean.

/cc @shirhatti

**Comment by Rovastar** [comment]
I don't mean the integrated pipeline.
I mean actually using IIS to manage asp.net core/kestral websites. Like you would with other technologies.

I am unclear how much understanding you have with IIS. But there is very little about IIS that says you 
Take asp.net you see a load of icons, etc in the GUI irrespective of the pipeline used.

And example might be have IIS show up in the app pool that a .net CLR version might have a option of reverse proxy to Kestrel or something.
Other none native technologies to IIS like PHP have stuff like PHP manager that help manage PHP. You get a GUI icon and things to interact with. We don't even have that a net core or kestral thing to help.

I am unclear how much thought has been to have these sort of interactions with IIS. I presume you have spoken to people inside Microsoft. *shrug* I can say with confidence that no-one has reached out to the IIS community at https://forums.iis.net/ which I help look after.

WPI = Web Platform installer

As the future of asp.net seems to be core now. I am surprised there hasn't been more movement in this area.

**Comment by davidfowl** [comment]
Ah! You just mean pure management features. This was discussed very early on in the project but nothing ever came of it because we haven't invested the time. Now that 2.0 is coming to a close, it makes sense to revisit Thanks for the reminder.

> I am unclear how much thought has been to have these sort of interactions with IIS. I presume you have spoken to people inside Microsoft that write/support IIS. shrug I can say with confidence that no-one has reached out to the IIS community at https://forums.iis.net/ which I help look after.

The overall team owns both ASP.NET Core, IIS and ASP.NET. 

> WPI = Web Platform installer

You'd like a web pi way to install .NET Core? That could be done but I would say the main difference is that things are *alot* less coupled to IIS (because obviously we need to run on all platforms now). That said, we could do more here to integrate at whatever level makes sense though I'm still unclear how much would actually add value. It would actually be good to get that kind of feedback. Most of the discussion around ASP.NET Core and IIS has been happening on:

- https://github.com/aspnet/IISIntegration
- https://github.com/aspnet/aspnetcoremodule

The team unfortunately hasn't been looking (AFAIK) at the IIS forums for ASP.NET Core feedback. We should make an ASP.NET Core section on the IIS forums to meet the community where they are at.

BTW @shirhatti is the IIS and ASP.NET Core Server PM, so we do have people working on both things 😄

**Comment by Rovastar** [comment]
I suppose I would expect it to be similar if not better support on Windows then previous iterations of  MS languages. 

Although you have this as multi platform it see like Windows is neglected or at least given little love.
I would still expect the majority of hosting asp.net core stuff to be on Windows platforms. And for that there is a natural expectation of more interaction with IIS and Windows.
Even tools that don't exist for other platforms to be there or at least first on Windows.

Perfmon counters (hundreds and hundreds of asp.net non-core ones), detailed failed request tracing integration, etc are areas useful and established for troubleshooting that I would expect see. Probably by default windows event logging too.

WPI just seemed a logical pace for it to be and where some people would go to find it. And with no mention there it made it seem unofficial/incomplete and it just didn't seem ready for prime time for a language I would want to support in production.

tbh I don't know enough about core to know what other useful things will be.

It seems strange not to try and get the same or better experience for a new language than we have had previously. Maybe as you had little dialogue with people that look after the sites and the focus has been solely on the dev and engaging with the other open source community platforms it explains you direction.

> The overall team owns both ASP.NET Core, IIS and ASP.NET.

Nice to see someone is managing the IIS product, All the IIS product team I knew left to join Azure, it seems, a few years ago and didn't actually know who was left.

**Comment by davidfowl** [comment]
Thanks for the feedback. We'll use it in future planning of ASP.NET Core + IIS features.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
