### ISSUE TITLE
Razor Pages support ASP.Net server controls or have server controls?

### ISSUE THREAD

**Issue by ghd258** [aspnet/Home#2142]
Razor Pages support ASP.Net server controls or have server controls?

**Comment by ghd258** [comment]
The MVC programming model to his advantage, but there are also disadvantages, page data and logic processing mainly by JS control, C# is only to the front-end data transfer function, the C# instead of weakening, the enhanced JS and web; from ASPX, aspx.cs aspx.cs played this way with powerful back-end processing capabilities of C#, not only can provide data, but also can process the front interface with C# display or logical processing; hope to use the Razor Pages Cs, play the powerful function of C#

**Comment by hishamco** [comment]
@ghd258 Razor is a template syntax that renders at server-side, Razor doesn't capture DOM for future processing, so something like ASP.NET WebForms server control is not a great choice to be supported by Razor, but you can leverage some of event-driven model in Razor Pages, for more details you can check out my blog post [Razor Pages Commands & Events](http://hishambinateya.com/razor-pages-commands-and-events)

If you have an interest of event-drive model you can contribute to my project [ASP.NET Core Web Forms](http://github.com/hishamco/webforms)

**Comment by frankabbruzzese** [comment]
Difficult for me to understand why insisting on a Web paradigm that is becoming obsolete, and that is not supported anymore in Asp.net core. 

Causing each single event be handled on the server forces a programming paradigm based on ViewState being exchanged between client and server which worsen the interaction with the user. This means each page must have an unique form...and so on. A lot of constraints that lead developers far from the future directions of web development that uses always more client side technologies.

It is possible to have complex "controls" also while taking advantage of mvc paradigm, and/or avoiding the usage of server side events and viewstate. See these [mvc based grid](http://examples.aspnetcore.mvc-controls.com/Food/GridsContainer) for instance:

**Comment by hishamco** [comment]
@frankabbruzzese FYI Razor Pages make this stuff easier via **Page Handlers**

**Comment by frankabbruzzese** [comment]
@hishamco , Razor page handlers are very different from WebForm handlers, since they handle HTTP verbs, that is exactly what a web application should do, not client events. 
Of course one might mimic what WebForms do, that is, transforming client events into HTTP verbs, that causes posts and gets be invoked automatically
However, modern web programming prefer that the developer has complete control on when and why invoking HTTP verbs, in order to optimize user-machine interaction. This way you may decide to invoke an ajax call with the more adequate verb, and the more adequate parameters, or to invoke a get with some "REST" parameters, or to submit ONE OF the forms you have in your page, or also a form you build dynamically with a selection of the parameters you have in the page.

On the contrary "automatic postback" deals with ALL events in the same way: by submitting the unique form you have in the page. This might cause unwanted interactions between page subparts, so often people write spaghetti code to achieve its goals. The result is not modular, and difficult to mantain and modify code.

**Comment by Eilon** [comment]
No plans to add server controls to Razor Pages.
