### ISSUE TITLE
[Feature Requested] Server-Side Validation based on the Tag-Helpers

### ISSUE THREAD

**Issue by A7medRamadan** [aspnet/Home#2153]
What about having a server-side validation without the need to post all the data to the server to check the validation constrains, just by adding a simple Tag-Helper (asp-validate="true") it automatically validate that input in the server that if it matches the validation constrains or not.
`<input type="text" asp-for="UserName" asp-validate="true" />`
Just to make the `RemoteValidationAttribute `  more clear and simple to be used

**Comment by pranavkm** [comment]
@dougbu would TagHelpers + `RemoteValidationAttribute` on the model work in this case?

**Comment by dougbu** [comment]
@pranavkm you meant `RemoteAttribute` and yes, it should work.

Then again, @A7medRamadan you mention both "without the need to post the data to the server" and "automatically validate in the server". Are you distinguishing between sending _all_ the data and sending just the data for one property? If that's the case, `[Remote]` is your man.

**Comment by A7medRamadan** [comment]
No need to post all the data to the server to validate then returning it back, just validate it as the input lost its focus.
And i know the `RemoteValidationAttribute `but i just want more clean and simple way to implement it in the code

**Comment by A7medRamadan** [comment]
To make my point more clear, to implement `RemoteValidationAttributebut ` i have first to write it for a property then making a controller to handle the validation logic then adding the Jquery validation set 

i just only want simple taghelper do all the required things on the fly just asp-validate="true"

**Comment by A7medRamadan** [comment]
@dougbu i edited my request

**Comment by dougbu** [comment]
To be clear, there is no `RemoteValidationAttribute` in MVC, just `RemoteAttribute`.

`[Remote]` does require some setup -- mostly action(s) to verify data and `[Remote]` annotations. It's also a bit fragile due to the `AdditionalFields` feature.

But, please clarify how `<input type="text" asp-for="UserName"/>` with `[Remote]` on the `UserName` property would change the response if `asp-validate="true"` were added?

In particular, are you asking for a feature that generates actions and adds `[Remote]` annotations using those actions? (That sounds like a [Scaffolding](https://github.com/aspnet/Scaffolding) feature but I may be missing something.)

**Comment by A7medRamadan** [comment]
@dougbu  Yeah you are right, that what i really meant Scaffolding feature

**Comment by dougbu** [comment]
This issue was moved to aspnet/Scaffolding#604
