### ISSUE TITLE
on 2008r2 server asp.net core when using sqlConnection fails with 

### ISSUE THREAD

**Issue by foxjazz** [aspnet/Home#2164]
on 2008r2 server asp.net core 2.0 when using sqlConnection fails with 

[ERR] Connection id ""0HL7B69PSCNQ2"", Request id ""0HL7B69PSCNQ2:00000001"": An unhandled exception was thrown by the application. (560e7d32)
System.DllNotFoundException: Unable to load DLL 'sni.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at System.Data.SqlClient.SNINativeMethodWrapper.UnmanagedIsTokenRestricted(IntPtr token, Boolean& isRestricted)
   at System.Data.Win32NativeMethods.IsTokenRestrictedWrapper(IntPtr token)

**Comment by Eilon** [comment]
@ajcvickers @divega @bricelam @natemcmaster - any ideas?

**Comment by divega** [comment]
@foxjazz does the application already reference the Microsoft.AspNetCore.All 2.0 package in its csproj file? Otherwise make sure it references at least version 4.4.0 of System.Data.SqlClient. We have seen problems with previous versions not deploying the right version of the native binary sni.dll.

Please confirm if this helps.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
