### ISSUE TITLE
Metapackage AspNetCore.All doesn't work when targeting Net4X

### ISSUE THREAD

**Issue by McGittyHub** [aspnet/Home#2179]
What is the reason for this? I'm only interested in building for windows anyway. Shouldn't this be possible?

**Comment by davidfowl** [comment]
The reason we blocked it is because it would deploy *everything* to the output folder. .NET Core has an optimization (see the runtime package store https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-store) that allows us to avoid deploying the entire framework to the output, there's no good equivalent for in .NET Framework.

**Comment by snarf95** [comment]
While that is a nice feature shouldn't it in fact be optional? I think a lot of users are highly dependent on packages for NET framework that hasn't been ported yet.

**Comment by davidfowl** [comment]
> While that is a nice feature shouldn't it in fact be optional? I think a lot of users are highly dependent on packages for NET framework that hasn't been ported yet.

People would immediately complain about megabytes of packages being deployed with every single ASP.NET application.

**Comment by Eilon** [comment]
Closing because there are no plans to implement this at this time. We are, however, still considering some options here, but no immediate plans.
