### ISSUE TITLE
Why react and all dependencies are added inside devDependencies section ?

### ISSUE THREAD

**Issue by destromas1** [aspnet/Home#2207]
How npm works , `react` or `redux` these kinda stuffs should go to `dependencies` section inside `package.json` file . But I see those inside `devDependencies` section.
Can anyone share the reason ?
https://github.com/aspnet/templating/blob/95f2b8d375256ca7057cbe88dcbfff644697f183/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/ReactRedux-CSharp/package.json#L29

Packages like `webpack` or `webpack-hot-middleware` should be available inside `devDependencies` section.

I would also like to contribute wherever possible...

Thanks!

**Comment by Eilon** [comment]
@SteveSandersonMS - can you take a look?

**Comment by SteveSandersonMS** [comment]
They are all correctly in `devDependencies` because they are development-time-only dependencies. They are not required when the application is built for production, because the build process produces entirely self-contained bundles. There is no need to have `node_modules` on your server in production.
