### ISSUE TITLE
Controller Json response hang, improper error handling.

### ISSUE THREAD

**Issue by Shadetheartist** [aspnet/Home#2210]
If a controller method returns a JsonResult and the object passed into the Json call self references, it causes a "net::ERR_INCOMPLETE_CHUNKED_ENCODING" error in chrome. (but not firefox).

Using the Microsoft.AspNet.Buffering "UseResponseBuffering" app configure method fixes the chunking issue by disabling chunked responses. Then the actual error, the recursive reference in the json object is revealed.

The error should be handled the same way for the chunked response.

**Comment by jkotalik** [comment]
What server are you using (Kestrel behind IIS, Kestrel stand alone, HttpSysServer)? What verson of dotnet are you using?

**Comment by Tratcher** [comment]
Serialization errors cannot be gracefully handled without buffering. Buffering is not enabled by default due to the delay it introduces and the potentially unbounded size of the entities. Serialization errors tend to only show up in development where you can see them in logs, the debugger, etc., so we do not consider this a functional / production issue.
