### ISSUE TITLE
vs 2017 error Error	NU1202	Package System.Threading.Overlapped 4.0.1 is not compatible with netcoreapp2.0

### ISSUE THREAD

**Issue by kobosh** [aspnet/Home#2253]
To address your issues more quickly, please open the issue in the most appropriate repository. These are some of the most common repos:

Common ASP.NET and Entity Framework repos and projects:

 - Documentation: https://github.com/aspnet/Docs
 - MVC: https://github.com/aspnet/Mvc
 - Entity Framework Core: https://github.com/aspnet/EntityFramework
 - Entity Framework 6: https://github.com/aspnet/EntityFramework6
 - SignalR: https://github.com/aspnet/SignalR
 - ASP.NET Core in Docker: https://github.com/aspnet/aspnet-docker
 - Microsoft.NET.Sdk.Web: https://github.com/aspnet/websdk
 - Kestrel HTTP Server: https://github.com/aspnet/KestrelHttpServer
 - ASP.NET Katana: https://github.com/aspnet/AspNetKatana
 - and more! See a full list here: https://github.com/aspnet

Other common projects:

 - NuGet: https://github.com/NuGet/home
 - .NET Core CLI, SDK, or runtime: https://github.com/dotnet/core
 - Visual Studio: https://developercommunity.visualstudio.com
 - Visual Studio Code: https://github.com/microsoft/vscode
 - Omnisharp (C# support for VS Code): https://github.com/omnisharp/omnisharp-vscode

**Comment by kobosh** [comment]
I installed vs 2017  community on windows 7 and get this error when trying to build angular paroject

**Comment by jkotalik** [comment]
Try updating the version of System.Threading.Overlapped to 4.3.0. That error means that 4.0.1 is not compatible with dotnet core 2.0.

**Comment by kobosh** [comment]
thanks i will try

**Comment by KenCox** [comment]
Me too. It  looks like the Nuget dependency is badly broken.

Just creating a default app as shown here https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?tabs=aspnetcore2x#tabpanel_QpO1Dgob1h_aspnetcore2x

Produces a ton of NU1202 errors.

VisualStudio.15.Release/15.4.3+27004.2008
Microsoft .NET Framework Version 4.7.02556


Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package System.Linq.Parallel 4.0.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Linq.Parallel 4.0.1 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - net45 (.NETFramework,Version=v4.5)
  - netcore50 (.NETCore,Version=v5.0)
  - netstandard1.1 (.NETStandard,Version=v1.1)
  - portable-net45+win8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile111)
  - win8 (Windows,Version=v8.0)
  - wpa81 (WindowsPhoneApp,Version=v8.1)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Error	NU1202	Package System.Threading.Overlapped 4.0.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Threading.Overlapped 4.0.1 supports: netstandard1.3 (.NETStandard,Version=v1.3)				
Error	NU1202	Package System.Runtime.Loader 4.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Runtime.Loader 4.0.0 supports:
  - net462 (.NETFramework,Version=v4.6.2)
  - netstandard1.5 (.NETStandard,Version=v1.5)				
Error	NU1202	Package System.Collections.Concurrent 4.0.12 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Collections.Concurrent 4.0.12 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - net45 (.NETFramework,Version=v4.5)
  - netcore50 (.NETCore,Version=v5.0)
  - netstandard1.1 (.NETStandard,Version=v1.1)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - portable-net45+win8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile111)
  - win8 (Windows,Version=v8.0)
  - wpa81 (WindowsPhoneApp,Version=v8.1)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Error	NU1202	Package System.AppContext 4.1.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.AppContext 4.1.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - netstandard (.NETStandard,Version=v0.0)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - netstandard1.6 (.NETStandard,Version=v1.6)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Error	NU1202	Package Microsoft.Win32.Primitives 4.0.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Win32.Primitives 4.0.1 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Error	NU1202	Package System.IO.Compression 4.1.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.IO.Compression 4.1.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - net45 (.NETFramework,Version=v4.5)
  - netcore50 (.NETCore,Version=v5.0)
  - netstandard1.1 (.NETStandard,Version=v1.1)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - portable-net45+win8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile111)
  - win8 (Windows,Version=v8.0)
  - wpa81 (WindowsPhoneApp,Version=v8.1)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Error	NU1202	Package System.Security.Cryptography.X509Certificates 4.1.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Security.Cryptography.X509Certificates 4.1.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - netstandard1.4 (.NETStandard,Version=v1.4)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Error	NU1202	Package System.Security.Principal 4.0.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Security.Principal 4.0.1 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - net45 (.NETFramework,Version=v4.5)
  - netcore50 (.NETCore,Version=v5.0)
  - netstandard1.0 (.NETStandard,Version=v1.0)
  - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
  - win8 (Windows,Version=v8.0)
  - wp8 (WindowsPhone,Version=v8.0)
  - wpa81 (WindowsPhoneApp,Version=v8.1)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Error	NU1202	Package System.IO.Pipes 4.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.IO.Pipes 4.0.0 supports: netstandard1.3 (.NETStandard,Version=v1.3)				
Error	NU1202	Package System.Diagnostics.Contracts 4.0.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Diagnostics.Contracts 4.0.1 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - net45 (.NETFramework,Version=v4.5)
  - netcore50 (.NETCore,Version=v5.0)
  - netstandard1.0 (.NETStandard,Version=v1.0)
  - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
  - win8 (Windows,Version=v8.0)
  - wp8 (WindowsPhone,Version=v8.0)
  - wpa81 (WindowsPhoneApp,Version=v8.1)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Error	NU1202	Package System.Security.Cryptography.Encoding 4.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Security.Cryptography.Encoding 4.0.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Error	NU1202	Package System.Threading.Timer 4.0.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Threading.Timer 4.0.1 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - net451 (.NETFramework,Version=v4.5.1)
  - netcore50 (.NETCore,Version=v5.0)
  - netstandard1.2 (.NETStandard,Version=v1.2)
  - portable-net451+win81+wpa81 (.NETPortable,Version=v0.0,Profile=Profile151)
  - win81 (Windows,Version=v8.1)
  - wpa81 (WindowsPhoneApp,Version=v8.1)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Error	NU1202	Package System.Runtime.InteropServices.RuntimeInformation 4.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Runtime.InteropServices.RuntimeInformation 4.0.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Error	NU1202	Package System.Console 4.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Console 4.0.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Error	NU1202	Package System.Globalization.Calendars 4.0.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Globalization.Calendars 4.0.1 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Error	NU1202	Package System.Net.Primitives 4.0.11 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Net.Primitives 4.0.11 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - net45 (.NETFramework,Version=v4.5)
  - netcore50 (.NETCore,Version=v5.0)
  - netstandard1.0 (.NETStandard,Version=v1.0)
  - netstandard1.1 (.NETStandard,Version=v1.1)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
  - win8 (Windows,Version=v8.0)
  - wp8 (WindowsPhone,Version=v8.0)
  - wpa81 (WindowsPhoneApp,Version=v8.1)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Error	NU1202	Package System.Security.Cryptography.Csp 4.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Security.Cryptography.Csp 4.0.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Error	NU1202	Package System.Security.Cryptography.Primitives 4.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Security.Cryptography.Primitives 4.0.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Error	NU1202	Package System.Diagnostics.Process 4.1.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Diagnostics.Process 4.1.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - netstandard1.4 (.NETStandard,Version=v1.4)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Error	NU1202	Package System.Net.Sockets 4.1.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Net.Sockets 4.1.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Error	NU1202	Package System.Threading.Tasks.Dataflow 4.6.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Threading.Tasks.Dataflow 4.6.0 supports:
  - netstandard1.0 (.NETStandard,Version=v1.0)
  - netstandard1.1 (.NETStandard,Version=v1.1)				
Error	NU1202	Package System.Collections.Immutable 1.2.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Collections.Immutable 1.2.0 supports:
  - netstandard1.0 (.NETStandard,Version=v1.0)
  - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)				
Error	NU1202	Package System.Reflection.Metadata 1.3.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Reflection.Metadata 1.3.0 supports:
  - netstandard1.1 (.NETStandard,Version=v1.1)
  - portable-net45+win8 (.NETPortable,Version=v0.0,Profile=Profile7)				
Error	NU1202	Package System.Xml.XPath 4.0.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Xml.XPath 4.0.1 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Error	NU1202	Package System.Diagnostics.Tracing 4.1.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Diagnostics.Tracing 4.1.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - net45 (.NETFramework,Version=v4.5)
  - netcore50 (.NETCore,Version=v5.0)
  - netstandard1.1 (.NETStandard,Version=v1.1)
  - netstandard1.2 (.NETStandard,Version=v1.2)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - netstandard1.5 (.NETStandard,Version=v1.5)
  - portable-net45+win8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile111)
  - win8 (Windows,Version=v8.0)
  - wpa81 (WindowsPhoneApp,Version=v8.1)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Error	NU1202	Package System.Diagnostics.FileVersionInfo 4.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Diagnostics.FileVersionInfo 4.0.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Error	NU1202	Package System.Threading.ThreadPool 4.0.10 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Threading.ThreadPool 4.0.10 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - netcore50 (.NETCore,Version=v5.0)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Error	NU1202	Package Microsoft.Win32.Registry 4.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Win32.Registry 4.0.0 supports: netstandard1.3 (.NETStandard,Version=v1.3)				
Error	NU1202	Package System.Threading.Thread 4.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Threading.Thread 4.0.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - netcore50 (.NETCore,Version=v5.0)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Error	NU1202	Package System.Security.Cryptography.Algorithms 4.2.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Security.Cryptography.Algorithms 4.2.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Error	NU1202	Package System.Text.Encoding.CodePages 4.0.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Text.Encoding.CodePages 4.0.1 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)				
Warning	NU1701	Package 'System.Linq.Queryable 4.0.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.	MvcMovie	c:\temp\MvcMovie\MvcMovie\MvcMovie.csproj	1	
Error	NU1202	Package Remotion.Linq 2.1.1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Remotion.Linq 2.1.1 supports:
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - netstandard1.0 (.NETStandard,Version=v1.0)
  - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)	MvcMovie	c:\temp\MvcMovie\MvcMovie\MvcMovie.csproj	1

**Comment by Eilon** [comment]
Closing this issue because it isn't clear to me if there is an issue remaining. If you feel there's still an issue, please re-open this issue or log a new issue with complete details of the problem. Thanks!
