### ISSUE TITLE
Unwanted retry when returning 408

### ISSUE THREAD

**Issue by JanEggers** [aspnet/Home#2289]
i am returning 408 from my webapi controller if a call to the backend times out. i want that code to be returned to the client but what happens is that the action that generated the timeout is called again and again.

Is there any way to disable this behavior?

**Comment by MichaelVincentHubbard** [comment]
Wait...hmmm


Sent from my Samsung Galaxy , an AT&T LTE smartphone
-------- Original message --------From: JanEggers <notifications@github.com> Date: 11/27/17  12:46 AM  (GMT-08:00) To: aspnet/Home <Home@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [aspnet/Home] Unwanted retry when returning 408 (#2289) 
i am returning 408 from my webapi controller if a call to the backend times out. i want that code to be returned to the client but what happens is that the action that generated the timeout is called again and again.
Is there any way to disable this behavior?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/aspnet/Home","title":"aspnet/Home","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/aspnet/Home"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Unwanted retry when returning 408 (#2289)"}],"action":{"name":"View Issue","url":"https://github.com/aspnet/Home/issues/2289"}}}

**Comment by Tratcher** [comment]
There's no retry on the server side, that must be coming from the client.

**Comment by JanEggers** [comment]
that is strange i dont have retry code in place and after i changed returncode to 500 the method was no longer called repeatedly.

**Comment by Tratcher** [comment]
What does a Fiddler trace show?

**Comment by JanEggers** [comment]
hi there @Tratcher thx for pointing me to fiddler, seems chrome does it internally devtools show one request but there are several.

![image](https://user-images.githubusercontent.com/6747376/33307784-1c337c36-d418-11e7-9260-717bf2ef23c3.png)

can you advice on a meaningful http errorcode if a backend service has a timeout, im basicly having some async code in a try catch and dont want to return 500 in case of a TimeoutException or TaskCancellationException..

would 504 be the right thing to return?

**Comment by Tratcher** [comment]
Yes 504 is a good status code for that.

**Comment by JanEggers** [comment]
thx again
