### ISSUE TITLE
Aspnet

### ISSUE THREAD

**Issue by MAGALY956** [aspnet/Home#2295]
To address your issues more quickly, please open the issue in the most appropriate repository. These are some of the most common repos:

Common ASP.NET and Entity Framework repos and projects:

 - Documentation: https://github.com/aspnet/Docs
 - MVC: https://github.com/aspnet/Mvc
 - Entity Framework Core: https://github.com/aspnet/EntityFramework
 - Entity Framework 6: https://github.com/aspnet/EntityFramework6
 - SignalR: https://github.com/aspnet/SignalR
 - ASP.NET Core in Docker: https://github.com/aspnet/aspnet-docker
 - Microsoft.NET.Sdk.Web: https://github.com/aspnet/websdk
 - Kestrel HTTP Server: https://github.com/aspnet/KestrelHttpServer
 - ASP.NET Katana: https://github.com/aspnet/AspNetKatana
 - and more! See a full list here: https://github.com/aspnet

Other common projects:

 - NuGet: https://github.com/NuGet/home
 - .NET Core CLI, SDK, or runtime: https://github.com/dotnet/core
 - Visual Studio: https://developercommunity.visualstudio.com
 - Visual Studio Code: https://github.com/microsoft/vscode
 - Omnisharp (C# support for VS Code): https://github.com/omnisharp/omnisharp-vscode

**Comment by MichaelVincentHubbard** [comment]
Xlcool.maybe in Google cloud or aws or both as well?
Thank you :).
Thank you how are you?


Sent from my Samsung Galaxy , an AT&T LTE smartphone
-------- Original message --------From: MAGALY956 <notifications@github.com> Date: 11/30/17  1:57 AM  (GMT-08:00) To: aspnet/Home <Home@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [aspnet/Home] Aspnet (#2295) 
To address your issues more quickly, please open the issue in the most appropriate repository. These are some of the most common repos:
Common ASP.NET and Entity Framework repos and projects:

Documentation: https://github.com/aspnet/Docs
MVC: https://github.com/aspnet/Mvc
Entity Framework Core: https://github.com/aspnet/EntityFramework
Entity Framework 6: https://github.com/aspnet/EntityFramework6
SignalR: https://github.com/aspnet/SignalR
ASP.NET Core in Docker: https://github.com/aspnet/aspnet-docker
Microsoft.NET.Sdk.Web: https://github.com/aspnet/websdk
Kestrel HTTP Server: https://github.com/aspnet/KestrelHttpServer
ASP.NET Katana: https://github.com/aspnet/AspNetKatana
and more! See a full list here: https://github.com/aspnet

Other common projects:

NuGet: https://github.com/NuGet/home
.NET Core CLI, SDK, or runtime: https://github.com/dotnet/core
Visual Studio: https://developercommunity.visualstudio.com
Visual Studio Code: https://github.com/microsoft/vscode
Omnisharp (C# support for VS Code): https://github.com/omnisharp/omnisharp-vscode


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/aspnet/Home","title":"aspnet/Home","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/aspnet/Home"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Aspnet (#2295)"}],"action":{"name":"View Issue","url":"https://github.com/aspnet/Home/issues/2295"}}}
