### ISSUE TITLE
IOptionsSnapshot is not working with singleton services

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2380]
_From @ductrantb on Thursday, December 14, 2017 12:42:32 AM_

Hi friends,
I have a problem with IOptionsSnapshot. I was tried to use BackgroundServiceManagerConfigsFactory as a transient service to renew configs on change.
```
services.AddTransient<BackgroundServiceManagerConfigsFactory, BackgroundServiceManagerConfigsFactory>();
services.AddSingleton<BackgroundServiceManager, BackgroundServiceManager>();
```

The constructor of my configs factory was called on every request (by singleton service), but configs value was not changed.

```
public BackgroundServiceManagerConfigs Configs { get; protected set; }
public BackgroundServiceManagerConfigsFactory(IOptionsSnapshot<BackgroundServiceManagerConfigs> options)
{
        Configs = options.Value;
}
```
I tried to call this factory in a controller, it worked.
I used netcore 2.0 and Microsoft.Extensions.Options version 2.0.0.0
Thank you.

_Copied from original issue: aspnet/Options#247_

**Comment by onovotny** [comment]
IOptionsSnapshot provides access to the `Get` method to provide access to named options. These should be available from Singleton services.

**Comment by ajcvickers** [comment]
@HaoK Your thoughts on this?

**Comment by HaoK** [comment]
IOptionsFactory's registered as transient, so you will get one every time, perhaps there's an issue with scopes in your app, BackgroundService tends to make it sound like something that lives across requests?  Can you include more code/details about how you've registered all the various pieces of your app?

**Comment by onovotny** [comment]
@HaoK The core issue is that I have a service that needs named config. It should be a singleton since it has no state.

I can get an `IOptions<T>` to get config, but not an `IOptionsSnapshot<T>` since `IOptionsSnapshot<T>` is registered as scoped. 

A singleton cannot get an instance of a scoped service (but it can of a transient one since transient returns a new instance each time).

Right now, both `IOptions<T>` and `IOptionsSnapshot<T>` are implemented by the same type `OptionsManager<T>`. While that could change, it seems like the only real difference is that the `Get` method required to access a named instance is only exposed on `IOptionsSnapshot<T>` despite being available in the implementation class for `IOptions<T>`. 

The hole here is that there's no easy way for a singleton object to get to a named configuration object due to this.

**Comment by HaoK** [comment]
Just use `IOptionsMonitor`, that's what you are looking for.  Closing this issue since IOptionsSnapshot is not intended to be used from singleton services.
