### ISSUE TITLE
Consider implementing IOptionsMonitor in OptionsWrapper

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2391]
_From @pakrym on Wednesday, June 14, 2017 4:47:32 PM_

Possibly IOptionsFactory and IOptionsSnapshot too.
Idea is to be able to pass constant options to any options consumer without requiring to implement proxy class (https://github.com/aspnet/Logging/blob/2b6d34778b013908f6d9208b8a69a8286dceac34/test/Microsoft.Extensions.Logging.AzureAppServices.Test/OptionsWrapperMonitor.cs)

_Copied from original issue: aspnet/Options#200_

**Comment by ajcvickers** [comment]
@HaoK Can you comment on this?

**Comment by HaoK** [comment]
Its not a perfect fit, since the wrapper today only takes 1 specific options instance.  We could have it implement IOptionsMonitor and return that single instance for all named options as well as the default I guess.  But this looks mostly like a test improvement/usage scenario...

A 'real' wrapper for the monitor should take a `Dictionary<string, TOptions>` to use as the map...

**Comment by ajcvickers** [comment]
@HaoK Thanks. So it sounds like to me we should just close this. Agreed?

**Comment by HaoK** [comment]
Yeah sounds fine to just close, done
