### ISSUE TITLE
Allow customization of ClaimUid extraction

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2412]
_From @mattvperry on Tuesday, October 31, 2017 2:52:26 PM_

In the event that the claims which you look for in the current identity (sub, nameid, upn) don't exist you fallback on hashing all claims. All claims most likely includes expiry/issuance dates which change frequently. The end result being that antiforgery tokens which last across token refreshes will be wrongly invalidated.

My suggestion would be to add a setting which describes an alternate claim to use for uniquely identifying a principal.

I ran into this since my service uses an odd set of claims, none of which are the ones you are looking for.

_Copied from original issue: aspnet/Antiforgery#166_

**Comment by aspnet-hello** [comment]
_From @Eilon on Thursday, November 2, 2017 1:34:39 PM_

@blowdart / @Tratcher / @rynowak - thoughts on adding an option for this?

**Comment by aspnet-hello** [comment]
_From @rynowak on Thursday, November 2, 2017 4:40:05 PM_

This is possible to do with pubternal today: https://github.com/aspnet/Antiforgery/blob/dev/src/Microsoft.AspNetCore.Antiforgery/Internal/IClaimUidExtractor.cs

This would be easy to clean up and document if we think it's valuable. I believe this was possible in System.Web

**Comment by aspnet-hello** [comment]
_From @mattvperry on Thursday, November 2, 2017 4:57:20 PM_

Yeah, overriding that was how I worked around the issue. However, IMO, depending on the shape of anything in the `.Internal` namespaces seems like a code smell since you guys probably feel more comfortable changing things at will in there.

**Comment by aspnet-hello** [comment]
_From @rynowak on Thursday, November 2, 2017 5:51:58 PM_

> Yeah, overriding that was how I worked around the issue. However, IMO, depending on the shape of anything in the .Internal namespaces seems like a code smell since you guys probably feel more comfortable changing things at will in there.

Yeah this is exactly correct. We want you to be able to unblock yourself, but over time APIs will migrate from `.Internal` to the mainline areas as we get requests for improvements.

If you find more cases like this feel free to give us feedback. It's definitely intended that we polish and move `.Internal` code into public areas if there is a good reason for you to use it. 👍

**Comment by javiercn** [comment]
@mkArtakMSFT I'm not sure this is worth doing. I would move it to 3.0 or close it.

**Comment by javiercn** [comment]
@Eilon I think the work here would be to look at an interface that we have on the .Internal namespace and to move it to a regular namespace so that it's "legitimate" to extend it. It might need some cleanup/design, but there hasn't been a lot of requests for this scenario and there is a to work around it (even if it involves replacing the .Internal service).

I don't think we'll be likely to change this interface/service any time soon so this can wait.

The alternative would involve looking into the interface, getting agreement on its shape and doing the work to change the code to consume the new interface (potentially breaking people using the current workaround).

**Comment by mkArtakMSFT** [comment]
Closing as there is no much community interest in this. Agreed with @javiercn.
