### ISSUE TITLE
.net core :Missing option SuppressIdentityHeuristicChecks / How to generate token without consider user identity

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2413]
_From @chintan3100 on Sunday, August 6, 2017 5:33:04 AM_

I am working with SPA which communicates with .net core web API. UI and API both are on a different domain.
On login API I am generating JWT token + anti-forgery token but this token is not valid due to identity set to "".
There should option like SuppressIdentityHeuristicChecks = false.

Is there any other way?
For temporary soluton.
I created separate API which generates anti-forgery token. So after login UI will call getAntiforgery token API with jwt token. So every time there two web call when user try to login.

_Copied from original issue: aspnet/Antiforgery#157_

**Comment by alexvy86** [comment]
I think I'm running into the same thing... in my case everything is under the same URL, and the identity is not blank. This is my scenario:
1. The SPA calls a method in the API, gets authenticated with a Cookie (regular ASP.NET Core authentication), the method generates the JWT and the anti-forgery token.
2. In Middleware, I'm replacing the HttpContext.User that comes from cookies with the one I manually obtain by authenticating against the "Bearer" authentication scheme.
3. Methods that are have an attribute to validate the anti-forgery token complain with `Antiforgery token validation failed. The provided antiforgery token was meant for a different claims-based user than the current user.`.

I even tried overwriting HttpContext.User with a new ClaimsPrincipal right before passing HttpContext to `IAntiForgery`s `GetAndStoreTokens` method, something like:
```
var myPrincipal = new ClaimsPrincipal(new ClaimsIdentity(claimsForJwt, JwtBearerDefaults.AuthenticationScheme))
HttpContext.User = myPrincipal;
```
But anti-forgery validation still fails...

At first I thought it might be because my manual authentication against the "Bearer" scheme was returning a Principal with a different AuthenticationScheme ("AuthenticationScheme.Federation" if I recall correctly), but I managed to fix that through the `TokenValidationParameters` when setting up JwtBearer authentication.

Any ideas of why anti-forgery validation fails?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, and sorry for our late response on this issue.
It seems what you're trying to accomplish is not the recommended way to do it. Instead, you should consider exposing two different endpoints for authentication using different schemes. Then, you won't need to validate Antiforgery in pure javascript requests.
