### ISSUE TITLE
Add 'www.' to the default NuGet.org feed URL

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Home#255]
Visual Studio configures the available package sources in the options with a non-removable default for nuget.org. This entry uses https://www.nuget.org/api/v2/ (with 'www.'). When the NuGet.Config contains an entry named 'NuGet.org', but has the URL without the 'www.', Visual Studio unchecks the checkbox in the available package sources (but restore still works es expected), which created a lot of confusion for me this morning.

With a 'www.' Visual Studio's options work as expected.

**Comment by Eilon** [comment]
@mayurid @barrytang is this feature on your side, or is it part of NuGet itself (and I can forward to Jeff^2)?

**Comment by barrytang** [comment]
@Eilon, this is a NuGet issue.

**Comment by Eilon** [comment]
@jeffhandley @csharpfritz you have been summoned.

**Comment by jeffhandley** [comment]
We've seen this reported a couple of times, but we've chosen not to fix it.  There are conflicting scenarios where the current behavior is necessary.

If the user configures their own package source without configuring the default package source (recognized by URL), we cannot resurrect the default package source and make it enabled--it would be a violation of the privacy policy to do so.  However, we will resurrect the default package source as disabled in that case so that it can be easily restored without having to go through docs to find the URL.

When the custom package source happens to have the same "nuget.org" name, that brings in a conflict.  And in this scenario, it's almost the same URL.  But nonetheless, we've fallen into the "restore the default source but keep it disabled" behavior.

To work around this, just fix the NuGet.Config to have "www." in the URL.
