### ISSUE TITLE
Better solution for migrations / schema versioning

### ISSUE THREAD

**Issue by djanosik** [aspnet/Home#273]
Hi,

last year I decided to use EF migrations on our CRM-like project. It was really bad idea, it does not work well. Actually, I think migrations are useless for large projects.

It makes several assumptions:

- We need possibility to downgrade database. Well, we don't :) If it is neccessary, we need to downgrade the whole apllication. With migrations, if you downgrade the database first, it might broke your application. If you downgrade the application first, it has no idea how to downgrade the database (as far as I know) :/

- Everybody is perfect, nobody makes mistakes ;) You can't easily fix old migrations. You have to either downgrade your database or create a new migration. You will end up with lots of files that make small changes. They are hard to manage. And you can't delete or merge old ones.

- Every project is on-man-show. When there are many people working on the same project, you must be careful. Otherwise you can find that your migrations were not applied because they are older than migrations applied by your teammate.

- The best language for writing SQL is C# :D Well, I think the best language for writing SQL is... wait for it... SQL.

I think migrations are not good solution. And I don't like to see them in EF7. I hope you will introduce something better. Perhaps something like [Insight.Database.Schema](https://github.com/jonwagner/Insight.Database.Schema).

Regards,
Dusan

**Comment by Eilon** [comment]
@divega @rowanmiller because this is EF-related.

**Comment by rowanmiller** [comment]
@djanosik - Lots of folks prefer a C# based approach over SQL and the concept of code-based migrations isn't new to EF (ruby on rails is just one example of a similar approach). That said, it sounds like you prefer to be closer to the database and may be happier using something like database projects (a.k.a. SQL Server Data Tools) and just having the model generated from the database?

BTW the issues with working in a team are mostly fixed in EF7.

**Comment by djanosik** [comment]
Not exactly, I don't care how close I am to the database. But there are things that are hard to express in C# (triggers, functions, etc.). You can't really avoid mixed C# and SQL code and I don't like it very much. I just want some tool that makes "schema versioning" easier; not more complicated.

I like the model-first approach. But I've found that I can't avoid overhead in maintaining two different model formats. I've tried to generate EF migrations from model and it messed up my database many times. I had to check every generated migration; or write it manually. 

Other issues came up when we tried to extend our application with plugins. We didn't want to use special DbContext for every plugin. We wanted one DbContext extensible by plugins. We weren't able to make it working together with migrations. I believe it was because every migration is tied to hash of the model it was created against. [Insight.Database.Schema](https://github.com/jonwagner/Insight.Database.Schema) does something similar, but it stores hash of every object separately. And it automatically migrates your database when the model changes. The difference is that the model is written in SQL, not C#.

It's good to hear it will be easier to work with migrations in team. But there are still other issues.

BTW: It's possible in RoR to consolidate / merge old migrations.

**Comment by rowanmiller** [comment]
@djanosik  - That makes sense. For the migrations API we only ever planned to support things that can be natively expressed in the EF model (tables, sprocs, fk constraints, indexes, etc.). For the majority of our developers this is all they ever need. But yes, if you want to start adding things that are not part of the EF model (triggers, etc.) then you need to use raw SQL (or use the extensibility points to add APIs for creating them). 

The plugin scenario is interesting... I agree there isn't a great way to handle this although it may be easier now (in EF7) that we don't run all the model compatibility checks we used to. We've also starting using a single model snapshot file (rather than using one from the latest migration) to solve most of the team issues - the snapshot gets merged when you pull another developers changes/migrations. Since the snapshot is code... it may be possible to have plugins augment the model with their schema.

To be completely honest (and I'm not trying to be dismissive, just let you know what I'm thinking)... we haven't really heard this feedback from other developers and I'm wondering if your scenario is more complex than what most folks do. We do want to build a flexible stack that scales well to advanced requirements... but at the same time we want to optimize for the general case.

**Comment by djanosik** [comment]
Well, that sounds interesting. Maybe it will solve our problems and maybe not. I will try when EF7 is more "feature complete". Will you make it possible to dump an acutal DB schema? Something like `db/schema.rb`? See http://stackoverflow.com/a/8934178/3637097/...

**Comment by rowanmiller** [comment]
@djanosik when you say "dump an actual DB schema" do you want to get SQL script that will just create the schema (rather than all the incremental steps from individual migrations)?

**Comment by djanosik** [comment]
Yes, something like that. It doesn't have to be SQL script, it may be some C# code similar to migrations.

**Comment by rowanmiller** [comment]
We have all the components in place to do either. You can do `model => migration operations => C# migration code` or `model => migration operations => SQL` (internally that's what we use for the `DbContext.Database.EnsureCreated` method).

**Comment by rowanmiller** [comment]
BTW the code wouldn't be super simple at the moment, so we may want a top level command/API

**Comment by rowanmiller** [comment]
Closing as there hasn't been any further discussion, feel free to re-open if you have further questions
