### ISSUE TITLE
Ability to force CSRF validation on GET requests

### ISSUE THREAD

**Issue by Swazimodo** [aspnet/Home#2791]
I am trying to write a Anti-forgery wrapper that will cover our API based on a config file. However, one issue I found is there is no way to force a CSRF validation on GET requests. I dug into the source for the IsRequestValidAsync method and there are 4 types of http methods that will be ignored. Is there a way to force the validation to happen?

```
var method = httpContext.Request.Method;
if (string.Equals(method, "GET", StringComparison.OrdinalIgnoreCase) ||
   string.Equals(method, "HEAD", StringComparison.OrdinalIgnoreCase) ||
   string.Equals(method, "OPTIONS", StringComparison.OrdinalIgnoreCase) ||
   string.Equals(method, "TRACE", StringComparison.OrdinalIgnoreCase))
{
   // Validation not needed for these request types.
   return true;
}
```

Maybe I'm just not understanding why this exclusion is in place. Let's say I have banking site and there is some JavaScript that does a cross site get request for the account information. It then take that and post it to their own site. I thought that the antiforgery service was designed to prevent this but it looks like it would not prevent my example.

**Comment by blowdart** [comment]
Anti-forgery is aimed at POST requests to stop an attacker forcing a logged in user on another site initiating an action which changes state they did not start. This is centered around the idea of HTTP idempotence, and doesn't apply to GET requests, as they shouldn't shouldn't be changing state.

Your concern is different. You want to stop an attackers site doing cross site GETs in javascript. That is addressed by [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) and the [Same Origin Policy](https://en.wikipedia.org/wiki/Same-origin_policy), it is not a CSRF concern, because now you're in the realms of Javascript. 

Same Original Policy is a browser protection that stops javascript from calling out to other web sites. This can be weakened using CORS, where a web site operator says "Hey this resource on my machine can be accessed from URLS in these domains". Of course this is specifically opt-in, and is generally limited to resources which do not require authentication, or to resources which require non-persistent authentication and instead require the specific setting of a header, rather than cookie flow.

So no, anti-forgery will not be adding support for GET requests, it's the wrong place to address is.

**Comment by Swazimodo** [comment]
@blowdart I did some more research and I now have a better understanding of what I am doing. Thanks for your help on the last few issues I have opened. If you ever are in Edmonton I would buy you a beer :)

**Comment by blowdart** [comment]
State is specifically part of the OAuth spec and we support it there, but again, for normal gets we don't see a need. so any proposal wouldn't come from me.

As an aside, please don't comment on closed issues, especially ones so old, these don't get looked at in any triage meetings. A new issue is usually better.

**Comment by pinkplus** [comment]
@blowdart Thanks. I'll have a look at the OAuth implementation in asp.net core. I'll open a new issue if the existing implementation is not enough for me.
