### ISSUE TITLE
Add Assembly at Runtime

### ISSUE THREAD

**Issue by AceCoderLaura** [aspnet/Home#2836]
Original Issue:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/580

> 
> When I load an application part with a controller in it, Swashbuckle doesn't add the controller to the Swagger.
> 
> ```
> List<System.Reflection.Assembly> ExtraControllerAssemblies { get; set; }
> 
> public void ConfigureServices(IServiceCollection services)
> {
>   foreach (var assembly in ExtraControllerAssemblies)
>   {
>       services.AddMvc().AddApplicationPart(assembly);
>   }
> }
> ```
> I can invoke actions on the runtime-loaded controller just fine, so it's clearly loaded properly, but Swashbuckle hasn't generated any Swagger for it.

This is apparently and issue with ApiExplorer. How can I add my assembly for API exploration?

**Comment by MelbourneDeveloper** [comment]
This is a major issue for us. I added a controller to a project inside the Visual Studio solution and ran the service. Swashbuckle successfully read the metadata from ApiExplorer and displayed the controller's operation in Swagger. However, I then removed the project from Visual Studio and referenced the DLL manually. When I did this, Swashbuckle did not pick up the controller in the external assembly.

**Comment by MelbourneDeveloper** [comment]
It turns out that this was a kind of false alarm. The reason that the operation was not showing up in Swagger was that the method was not marked with the "public" modifier. This raises the question of how the REST call ever worked in the first place. I'm not convinced that it ever did work. But, if it did work, the ApiExplorer metadata should match the actual result. I.e. if the public modifier is not used, the REST operation should not work, or if it does work, it should also show up in the ApiExplorer metadata.

**Comment by rynowak** [comment]
API Explorer and Swashbuckle are built on top of MVC's action/controller discovery, so basically if MVC doesn't find it then API Explorer and Swashbuckle don't get the chance.

In MVC and most places in ASP.NET - we only don't really ever reflect over non-public types. I expect that the api call wasn't working, or wasn't routed to the intended action.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#7316
