### ISSUE TITLE
DataProtection DPAPI - optional enthropy

### ISSUE THREAD

**Issue by marian-margeta** [aspnet/Home#2843]
Why it isn't possible to change optional entropy when using DPAPI data protection? 
```csharp
...
services.AddDataProtection().ProtectKeysWithDpapi();
...
```
I dug into the code and it turns out it is constantly set to `DPAPI-Protected Secret` in class [DpapiSecretSerializerHelper](https://github.com/aspnet/DataProtection/blob/b706a75e03f93d2f9175a7fc3339baa87ad653f0/src/Microsoft.AspNetCore.DataProtection/Cng/DpapiSecretSerializerHelper.cs#L24). I think it would be nice to make it accessible from ASP's DataProtection API. It may be used as another password given at startup, along with NTLM.

**Comment by blowdart** [comment]
Because Data Protection is meant to be simple. The more switches there are the more can go wrong.

Plus you're misunderstanding Purpose. It is NOT entropy. It's for key isolation and you *can* create data protectors with specific purposes [quite easily](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/using-data-protection).

**Comment by marian-margeta** [comment]
@davidfowl Thank you for your response.

Ok, maybe I am misunderstanding something, I discovered DPAPI just a few days ago. But according to the code at [DpapiSecretSerializerHelper L85](https://github.com/aspnet/DataProtection/blob/b706a75e03f93d2f9175a7fc3339baa87ad653f0/src/Microsoft.AspNetCore.DataProtection/Cng/DpapiSecretSerializerHelper.cs#L85) it calls native DP API `Protect` function with entropy parameter. Doc at [msdn](https://msdn.microsoft.com/en-us/library/ms995355.aspx) says:

> **pOptionalEntropy**
> Pointer to a DATA_BLOB containing additional entropy used to protect the data. The cbData member holds the length of the pbData member's byte string that contains the optional entropy. The DATA_BLOB used in the protection call must also be used in the unprotection call. This is the application specific "secret" mentioned earlier.
> 
> This parameter is optional and can be NULL. 
 
So it is entropy or I am wrong? I have read the concept of `purposes` but it can be use just for key isolation. All keys are derived from the same master key. But I'd like to add additional protection to that master key, to be more complicated to decrypt it.

**Comment by blowdart** [comment]
Oh I see.

OK, so, we use DPAPI to protect the keys themselves, so a fixed entropy is good here, otherwise you're never getting those keys *back*. If we allowed you to make it different each time that'd be rather problematic for things we use it for like CSRF, or TempData.

Now, if you want to use it yourself for secrets, and want a password, then you can use the Purpose when creating a protector for that, err, purpose (pun not intended)

**Comment by marian-margeta** [comment]
So if I create the protector e.g. in this manner:
```csharp
...
Console.WriteLine("Type the password:");
var protector = serviceProvider.GetDataProtector(Console.ReadLine());
...
```
can the protected data be decrypted only with knowing the password? In the [doc describing the Purposes](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/consumer-apis/purpose-strings) there is stated that `The purpose string doesn't have to be secret`. Thus, If I use the `Purpose` with secret would it be secure enough if the password is not known to the attacker?

**Comment by blowdart** [comment]
You still need the keyring obviously. purposes don't _have_ to be secret, for example we have them in our code base, but they way they're used does mean that you could use them from user input and it lock a payload to being only able to be unlocked to someone with the purpose.

Now we don't recommend this, because creating purposes from user input does mean an attacker could, for example, fake a CSRF purpose.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
