### ISSUE TITLE
Session State Question

### ISSUE THREAD

**Issue by keyoke** [aspnet/Home#2861]
Hi,
I would like to understand if there is any technical reason why we store all Session State as a single byte stream? Which has to be Deserialized and finally parsed to extract key value pairs for our objects stored in session state. I may be wrong or missing something here but would it not be more optimal to store our session objects individually in a in-memory cache for example? In most causes we don't need all the state stored in session all at once.

https://github.com/aspnet/Session/blob/0652fbcfa8b4b924ccb74c2c9a921ec8811b772a/src/Microsoft.AspNetCore.Session/DistributedSession.cs#L333

Many Thanks
Gareth

**Comment by Tratcher** [comment]
- Session is designed for distributed scenarios, e.g. across multiple servers, so the serialization is necessary.
- It's all loaded and committed together (we call it a coherent session) because some aspects of the session need to be managed together such as the timeout, refresh, enumeration, as well as the Clear feature. If you used an incoherent session of disassociated keys then the timeouts would be per value rather than for the overall session usage, and enumeration and Clear would not be possible without knowing all of the keys.

**Comment by Eilon** [comment]
I'd like to add more to this:

> * Session is designed for distributed scenarios, e.g. across multiple servers, so the serialization is necessary.

In particular, what we found is that if the local session store used objects, developers would start storing data there that could not be serialized when they eventually switched to non-local session storage. By unifying on an API that was guaranteed to work on local and non-local storage, it makes the design more reliable.

**Comment by keyoke** [comment]
Ok thanks for the clarification
