### ISSUE TITLE
Localization: using resource files when switching CurrentUICulture ignores the translations

### ISSUE THREAD

**Issue by maxmantz** [aspnet/Home#2995]
Hi,

I have an issue while trying to work with `CurrentUICulture`. Based on a Pluralsight course, I have created a console app which should use resource files to translate an enum into both English and German. 

However, even after changing the `CurrentUICulture` to German, the translation is not picked up by my machine. The weird thing is, that the official source files from the course have the same problem - so I guess my machine is at fault here?

I've made a [repo](https://github.com/maxmantz/CurrentUICultureDemo) with the source files.
Using dotnet 2.1.100 on Windows 10.

**Comment by Eilon** [comment]
This issue was moved to dotnet/corefx#28420

**Comment by tarekgh** [comment]
@Eilon please reactivate this issue here as this looks asp.net specific. the simple console app worked fine and there is no problem in picking up the right resources. you may look at the comment https://github.com/dotnet/corefx/issues/28420#issuecomment-375912555 to get the specific asp.net repro. 

@maxmantz please follow up on this issue. Thanks.

**Comment by Eilon** [comment]
Thanks @tarekgh , looks like the issue eventually got resolved: https://github.com/dotnet/corefx/issues/28420#issuecomment-375923366
