### ISSUE TITLE
Default IDistributedCache for session

### ISSUE THREAD

**Issue by shravan2x** [aspnet/Home#3031]
I call `services.AddSession()` in the Configure section of my Startup file. I am able to store and retrieve data even without adding a distributed cache. Does `AddSession()` do this automatically?

**Comment by Tratcher** [comment]
No, but MVC does.
https://github.com/aspnet/Mvc/blob/8e323a8e1e78b520e9a1c2a5a5f64139d5c210d0/src/Microsoft.AspNetCore.Mvc.TagHelpers/DependencyInjection/TagHelperExtensions.cs#L34
Note this is only a local fallback, not a real distributed cache.

**Comment by shravan2x** [comment]
Could the [docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?tabs=aspnetcore2x#cookies) be updated to include this information?

**Comment by Eilon** [comment]
Right, this is "sort of" an implementation detail. MVC just does what it needs to do to make things work out of the box.

For the reason @Tratcher mentioned, this isn't exactly something we would document because it's something that could easily change in the future and shouldn't be relied on in terms of details.
