### ISSUE TITLE
macOS support for 2.1.0-preview1-final?

### ISSUE THREAD

**Issue by mrlife** [aspnet/Home#3035]
Using the latest beta release of Visual Studio for Mac, [which should have support for 2.1](https://blogs.msdn.microsoft.com/visualstudio/2018/03/21/visual-studio-for-mac-version-7-5-preview-1/).

<img width="230" alt="screen shot 2018-04-06 at 7 48 38 pm" src="https://user-images.githubusercontent.com/213164/38448646-c63860c2-39d3-11e8-8827-0dc7399e6469.png">

I installed 2.1 preview using the link on the [announcement blog post](https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-0-preview1-now-available/).

> $ dotnet --version
> 2.1.300-preview1-008174

Followed the steps from the announcement blog post linked above and restarted my computer.

I'm seeing this in the project options:

<img width="524" alt="screen shot 2018-04-06 at 7 37 13 pm" src="https://user-images.githubusercontent.com/213164/38448661-f3056b86-39d3-11e8-9bbc-f1cd44277e79.png">

For step 9 in the announcement blog post, is this checkbox in another location in Visual Studio for Mac?
> 9: Open the “Debug” tab and in the IIS Express profile, check the “Enable SSL” checkbox and save the changes

I attempted to run the project from CLI and it says it's running, but going to localhost:5000 shows it's not really running.

Please let me know if I am missing something or if this should be posted somewhere else.

**Comment by Eilon** [comment]
@vijayrkn / @mlorbetske - any idea about this issue?

**Comment by mrlife** [comment]
@Eilon Any idea how I can proceed?

**Comment by Eilon** [comment]
Also tagging  @seancpeters and @livarcocc in case they know more about how/when/if templates show up in VS for Mac.

**Comment by vijayrkn** [comment]
@mhutch - Can you please help?

**Comment by seancpeters** [comment]
@pierceboggan might be able to help.

**Comment by mrward** [comment]
VS Mac preview 1 does not support .NET Core 2.1 - unfortunately the blog post is incorrect and has not yet been corrected. You can still use .NET Core 2.1 projects and debug them with VS Mac preview 1 but you cannot create a new .NET Core 2.1 project using the IDE.

VS Mac preview 2 has support for .NET Core 2.1 and enables the project templates - https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-mac-preview-relnotes#--april-9-2018--visual-studio-2017-for-mac-version-75-preview-2-7501062

Step 9 in the [ASP.NET Core preview 1 blog post](https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-0-preview1-now-available/) does not apply since there is no IISExpress on the Mac. VS Mac uses the launchSettings.json but will use the profile named after the project not the IISExpress profile. .NET Core preview 1 had the https and http urls in the ASPNETCORE_URLS environment variable. This has changed in .NET Core preview 2 and broke the launch browser support for ASP.NET Core support in VS Mac. VS Mac preview 4 has fixed that particular problem with the .NET Core preview 2 sdk but is not yet released.

**Comment by mrlife** [comment]
@mrward Thanks so much for providing the status of .NET Core 2.1 on Mac. You guys update Visual Studio for Mac a lot, so thank you for that.

Everyone else, thanks for helping get this to the right person.
