### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by sepehr1014** [aspnet/Home#3125]
Using ASP.NET Core 2.1 RC1 the process is killed after an hour or so and we see these logs:

```
Application: dotnet.exe
CoreCLR Version: 4.6.26426.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AggregateException: One or more errors occurred. (An existing connection was forcibly closed by the remote host) ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.Shutdown()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.Abort()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1OutputProducer.Abort(Exception error)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Abort(Exception error)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.Abort(Exception ex)
   at System.IO.Pipelines.PipeCompletionCallbacks.Execute()
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletionCallbacks.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

```
Faulting application name: dotnet.exe, version: 2.1.26426.3, time stamp: 0x5ae1770d
Faulting module name: KERNELBASE.dll, version: 10.0.14393.2189, time stamp: 0x5abdad60
Exception code: 0xe0434352
Fault offset: 0x0000000000033c58
Faulting process id: 0x2e90
Faulting application start time: 0x01d3e6aa48e5f5c6
Faulting application path: C:\Program Files\dotnet\dotnet.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: f10816d3-b0de-49bc-9745-60f9b7dea199
Faulting package full name: 
Faulting package-relative application ID: 
```

BTW we're using web sockets without SignalR.

**Comment by sepehr1014** [comment]
We're having this issue on production and relying on memory cache, it's quite frustrating to have the process killed. Is there any workaround we could use until this is fixed?

**Comment by Ikcelaks** [comment]
I am getting the EXACT same Unhandled Exception trace on my development machine using Core 2.1 rc1 and a freshly created MVC project.  The Exception can be triggered reliably within a minute by rapidly clicking between "Home", "About", and "Contacts" from multiple browsers (Multiple browsers aren't required, but I find that it makes the problem happen quicker).

This development machine formerly ran 2.1 preview2 (without Kestrel crashes).

**Comment by halter73** [comment]
This issue was moved to aspnet/KestrelHttpServer#2554

**Comment by Ikcelaks** [comment]
Troubleshooting Update:
I attempted to recreate this bug with a fresh install of DotNet-2.1-RC1 on a fresh Windows 1709 VM, and I was unable to do so.  All of my projects ran just fine without crashing.

I returned to my original dev machine (also Windows 1709) and attempted to recreate a fresh environment by uninstalling all versions of DotNet Core and manually removing the NuGetFallbackFolder before reinstalling RC1.  This did not resolve the issue.

Then I realized that the fresh VM was on a network that bypasses Web-Filtering.  I put my original dev machine on that same network, and suddenly I was no longer able to trigger the Uncaught Exception error.  Fortunately/Unfortunately, returning the device to the original filtered network did not cause the bug to return.  I'm also unable to correlate the Uncaught Exceptions with any events logged by the Web Filter, but that doesn't mean much, because the kinds of rules that telemetry reporting would trigger don't show up in the log.

Question:
Is there any chance that the development WebHost is attempting to communicate out to the internet and crashing when the communication is cut off (possibly mid-stream) by a web-filter?
