### ISSUE TITLE
Not always building

### ISSUE THREAD

**Issue by jaygriggs** [aspnet/Home#3231]
I'm getting issues when building 
If I retry it will work fine. Its not 100% of the time just every now and then.
This has only occurred since updating to NetCore 2.1.  
The error message is 
Could not copy views.dll because it is being used by another process
The file is locked by: ".NET Core Host (16108)"
I only have one instance of VS 2017 open. Its updated to the latest.
Thanks In Advance

**Comment by pranavkm** [comment]
@BillHiebert this sounds similar to the other report that I looped you in.

**Comment by jaygriggs** [comment]
Problem still remains.... 
i'd go back to 2.0 if it didn't have major security flaws.
Is there any update?

**Comment by pranavkm** [comment]
> Is there any update?

Unfortunately not. Does restarting the IIS Express process fix the issue?

**Comment by jaygriggs** [comment]
Sometimes it does, sometimes it chokes and after 15 seconds I have to try again.

**Comment by BillHiebert** [comment]
@jaygriggs Visual Studio should be stopping the dotnet.exe process when the project that spawns it starts to build. That should be independent of the version of the framework you are targeting. Are you running VS 15.7?

**Comment by Eilon** [comment]
@jaygriggs to report new issues, use the [Report a Problem](https://developercommunity.visualstudio.com/) tool. 

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks. See [here](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us) for more details.
