### ISSUE TITLE
After package upgrade to 2.1.1 server/app fails to start

### ISSUE THREAD

**Issue by brgrz** [aspnet/Home#3281]
So I just upgraded packages for ASP.NET Core (the default ones, that come with the project template) from 2.1.0 to 2.1.1 and suddenly the app did not start again..

Found the following error in event log:
Application 'MACHINE/WEBROOT/APPHOST/TRIP.ADMIN' with physical root 'H:\...\App.Admin\' failed to start process with commandline 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Web Tools\ProjectSystem\VSIISExeLauncher.exe -argFile "C:\Users\Marko\AppData\Local\Temp\tmp4D17.tmp"', ErrorCode = '0x80004005 : 0.

Then tried some Google searches and stumled upon this
https://developercommunity.visualstudio.com/content/problem/24412/dotnetexe-instantly-crashes-when-debugging-aspnet.html

saying that it could be SDK related so I went and installed SDK 2.1.301 on the machine (previously had 2.1.300 running) and now magically the app works.

My question is: whatever happened to saying that ASP.NET Core is self contained and we don't have to worry about updating computers/servers? I guess it's not quite like that, ha..

**Comment by Eilon** [comment]
@natemcmaster - can you help answer this?

**Comment by natemcmaster** [comment]
As you discovered, a PackageReference to Microsoft.AspNetCore.All or Microsoft.AspNetCore.App does not completely download everything you need to run an app on 2.1. We realize this is a problem and are actively working on it. We have some ideas on ways to help users understand that updating your PackageReference to new patch versions of Microsoft.AspNetCore.App requires you update your server or computer. We also are considering removing the PackageReference altogether since this package isn't something you normally need to update to new patch versions. We have a discussion going here #3307. Please take a look, and feel free to jump in to the conversation if you have ideas on how we can make this better for users.
