### ISSUE TITLE
"dotnet publish" with PublishWithAspNetCoreTargetManifest set to false does not publish with third party dependencies

### ISSUE THREAD

**Issue by Botldoiz** [aspnet/Home#3310]
Trying to publish ASP .NET Core app with the dotnet CLI and its third party dependencies does not work, despite "PublishWithAspNetCoreTargetManifest" is set to false in the .csproj. Unfortunately, publishing the app as self contained is no option for us.

**Repro steps:**
* Create .NET core 2.1 application
* add e.g. ASP .NET Core 2.1 nuget package
* publish: **dotnet publish <YOUR .CSPROJ> --configuration Release --framework netcoreapp2.1**

As far as I have seen, "dotnet publish" for .NET Core 2.0 uses the "PublishWithAspNetCoreTargetManifest.targets" file -> there its stated how to handle "PublishWithAspNetCoreTargetManifest=false".
Link: https://github.com/aspnet/MetaPackages/blob/rel/2.0.0/src/Microsoft.AspNetCore.All/build/PublishWithAspNetCoreTargetManifest.targets

In .NET Core 2.1 SDK this file is nonexistent.

**Comment by Eilon** [comment]
@JunTaoLuo / @natemcmaster - any ideas on this?

**Comment by natemcmaster** [comment]
Support for the `PublishWithAspNetCoreTargetManifest` property was removed.  We discussed adding some warnings when you use it to indicate it was obsolete but didn't (cc @glennc). This property was used to disable the ASP.NET Core package runtime store, but in 2.1, we no longer ship ASP.NET Core in a package runtime store.

> Trying to publish ASP .NET Core app with the dotnet CLI and its third party dependencies does not work.... Unfortunately, publishing the app as self contained is no option for us.

Can you elaborate why you are trying to opt-out of the shared runtime?

From my experience, most users started using `PublishWithAspNetCoreTargetManifest=false` to opt-out of the package runtime store in 2.0 because this runtime store caused issues during servicing (typically this error: https://github.com/dotnet/core-setup/issues/3276). In ASP.NET Core 2.1, we no longer ship a package runtime store. Instead, we ship a shared runtime. The shared runtime behaves like a package runtime store, but doesn't suffer from some of the problems that a package store does. We're recommending users either use the shared runtime, or use self-contained.

**Comment by JunTaoLuo** [comment]
@Botldoiz , can you share your project file? Third party dependencies may not be included in the publish output if it's included in the Microsoft.AspNetCore.All shared framework for example. Note that to target netcpreapp2.1, you'll also have to use the 2.1.* version of the aspnet metapackages which, as mentioned previously, are designed to rely on the shared frameworks we ship instead of the runtime stores that were used for 2.0.

**Comment by Botldoiz** [comment]
Thank you for your help. I figured out, how to opt-out the shared runtime.
Setting _AspNetCoreAllSharedFxIsEnabled property to false in the .csproj is leading to the desired result when publishing.

Regarding the opt-out of the shared runtime: as far as I can see, in order to use it, the shared runtime has to be installed on the machine (or am I wrong?). In our case we want to test several testapps with several runtimes and can not be sure that the runtime is correctly (or even at all) installed at the test machines.

**Comment by natemcmaster** [comment]
@Botldoiz just wanted to let you know there is risk in relying on _AspNetCoreAllSharedFxIsEnabled. Just like reflection on internal types, there is nothing I can do to stop you from doing it, but it's really meant for internal use only. This property will go away in the 3.0 release.

The real way to opt-out of shared runtime is to not use the AspNetCore.App/All metapackages. If you directly reference Kestrel, Mvc, EF Core, etc, then you don't have to worry about aspnet shared runtimes/package runtime stores, etc. (of course, you still have to manage the base shared runtime, Microsoft.NETCore.App, but that's a whole different can of worms.)

**Comment by Botldoiz** [comment]
@natemcmaster followed your advice (not using the metapackages) and this seems less "hacky", thanks!
