### ISSUE TITLE
Unable to debug ASP.Net Core 2.0 app running in ISS on .Net Framework

### ISSUE THREAD

**Issue by ggirard07** [aspnet/Home#3339]
**Steps to reproduce**
1. File > New > Project
2. Select ASP.Net Core Web Application
3. In popup window, select "API" and change target framework for ".Net Framework" on top of the window (ASP.Net Core 2.0 should be default)
4. Create the project
5. Add a breakpoint in ValuesController in Get() method then start debug on ISS target

**Expected Result**
Breakpoint is hit then when debug is resumed response from the controller is displayed in the browser

**Actual Result**
Breakpoint is never hit and Visual Studio freeze

**Versions**
- Visual Studio 15.7.5
- Default Nuget package versions from ASP.Net Core WebAPI template
  - Microsoft.AspNetCore 2.0.4
  - Microsoft.AspNetCore.Mvc 2.0.4

**Comment by Eilon** [comment]
To report issues with Visual Studio, use the [Report a Problem](https://developercommunity.visualstudio.com/) tool.

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks. See [here](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us) for more details.

**Comment by ggirard07** [comment]
Thats's why I never use the "Report a Problem" in Visual Studio:

> We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.

Last issue I opened that way took 3 months to have someone actually assigned to the case!

**Comment by Eilon** [comment]
Hi @ggirard07 , sorry it took so long to resolve the other issue you had. The Report a Problem tool is still the best way to get the issue to the team that can help resolve it. We are continuing to make improvements to that tool to help issues get routed more quickly, but also given the volume of issues and the time it takes to evaluate them, unfortunately not every issue can be responded to quickly.
