### ISSUE TITLE
Options Validation: Support DataAnnotations

### ISSUE THREAD

**Issue by HaoK** [aspnet/Home#3385]
From Experience review with @ajcvickers @DamianEdwards @Eilon @davidfowl :

We should support DataAnnotations on the POCO for 2.2:

for example:
```
public class MyOptions 
{
        [Required]
        public string Key { get; set; }
   
        [Range(18,99, ErrorMessage="Age should be between 18 and 99")] 
        public int Age { get; set; } 
 
        [DataType(DataType.PhoneNumber)] 
        [Phone] 
        Public string PhoneNumber { get; set; } 
 
        [DataType(DataType.EmailAddress)] 
        [EmailAddress] 
        Public string Email { get; set; } 
}
```

Need to figure out how to opt in, via new default overload?
`services.AddOptions<MyOptions>.[Auto]Validate()`

**Comment by thiagolunardi** [comment]
The ability to add a binding name will be handy. Like `JsonProperty`.
```
public class MyOptions
{
    [JsonProperty("ASPNETCORE_ENVIRONMENT")]
    public string Environment { get; set; }
}
```

Sometimes the host environment set some values, and I'd like to read it using my app language.

**Comment by gautelo** [comment]
@thiagolunardi I agree. This was suggested in issue [#775](https://github.com/aspnet/Configuration/pull/775). It was decided to implement this sort of thing through the BinderOptions instead as part of [#789](https://github.com/aspnet/Configuration/pull/789).

Personally I feel like implementing yet another way to serialize properties instead of using what's already there is a mistake. I would much rather use data annotations for this.

I believe the counter argument is that sometimes you don't own the options type and can't add annotations to it. In my mind that would be a good argument for implementing 789 as a fallback. But data annotations should be the primary solution.

Especially now that we're adding validation through standardized attributes, I feel like that sets a precedent for also using attributes for serialization/property mapping. After all, the same argument could apply to validation - that rules could be added to BinderOptions or some other structure disconnected from the model in case one does not own the options model.

So, I feel like the decision to scrap #775 Should be reconsidered. Attributes should be the common approach for serialization and validation alike, with BinderOptions as a fallback only.

**Comment by HaoK** [comment]
Options and Configuration are decoupled, we can certainly consider revisiting and unifying the binder with whatever we end up for Options Validation as the binder primarily exists to bind config to options.

**Comment by HaoK** [comment]
It likely would end up similar to how options validation works, it would be a sugar method that generated the appropriate underlying binderoptions, as opposed to a replacement for the binder options.

**Comment by HaoK** [comment]
Fixed in https://github.com/aspnet/Options/pull/272

**Comment by bdominguez** [comment]
@HaoK did you included DataMember attribute so we can change a property binding name as we discussed in this post? I don't see it.

Thanks.

**Comment by HaoK** [comment]
The binder is unrelated to options validation, the binder is something that's solely part of configuration and any future binder work is not really directly related to this

**Comment by HaoK** [comment]
The binder is just one of many different ways you can set options values, options validation is a new lower level feature.

**Comment by bdominguez** [comment]
But it's something that are you going to do? We discussed it above and thought that it would be implemented at some point.

**Comment by HaoK** [comment]
The main difference from the discussion above, is that the binder is not at all targeted for "serialization", which is why going down the path of [DataMember] is not really a good fit as those are serialization attributes and that's not really something the binder is intended for

**Comment by gautelo** [comment]
*sigh* Why can't we have nice things... Would it be better if the request came in its own thread, one dedicated to Serialization through data contracts or something along those lines? Basically it feels like we're being met with the sort of response saying "this does not conform to our narrow definition of what the thing should do, hence the request is not reasonable and thusly rejected". Frustrating!
