### ISSUE TITLE
any ideas for an old developer?

### ISSUE THREAD

**Issue by djg973** [aspnet/Home#3425]
Ive been developing using MS techs for a long time now.  Have seen a lot of "the next big thing" come along, get pushed to the moon,  only to die off.  I was hoping MVC would be on that list.  But, alas, it is not, and with core, you get MVC, along with EF, and thats how its done now.  Screw that.  It still seems like bad tech.  So... should I leave the MS family altogether(I do know other languages).  Go back to databases only?  Stick with ASp.NET 4.X and hope core eventually dies?  What do you guys think?

**Comment by blowdart** [comment]
Hi. It looks like this is a question about how to use (or in your case, not use) ASP.NET Core. While we do our best to look through all the issues filed here, this is an opinion based question, rather than a code based issue, may we suggest posting your questions to  [StackOverflow](https://www.stackoverflow.com)?

Please consider tagging your StackOverflow question with  asp.net-core and/or asp.net-core-mvc.

**Comment by djg973** [comment]
I used this because it was what was recommended on the APS.NET webpage.  It said for product feedback, use this github link.  So I did... and now its closed, and you are tellign me to use stack overflow.    Nice customer service.  Yet another reason to leave MS behind.
________________________________
