### ISSUE TITLE
Consider requiring a higher version of Mono

### ISSUE THREAD

**Issue by borgdylan** [aspnet/Home#344]
Due to many recent changes in APIs that require stuff not in Mono 3.4, I would increase teh minimum Mono version to 4.1 i.e. the current master. Any prior version is incapable of running a decent ASP.NET 5 app from the current dev branches.

**Comment by MattKunze** [comment]
+1 - pretty much every example mentions MVC, which fails with mono 3.x

**Comment by Jarga** [comment]
+1 Here as well. It would be nice to have an updated docker image too. When I tried to use the docker image (microsoft/aspnet) which is currently based off of mono 3.12 and it would not work with the MVC samples or the MVC template projects from Visual Studio (they were both using beta-3). I upgraded everything to the latest (beta-4), used the last nightly build from the aspnet/docker repo, and used a custom docker image that i installed Mono v4.1.0 into and everything seems to work fine. I am assuming this is all because the beta builds are being changed a lot right now.

**Comment by MattKunze** [comment]
Now that [Mono 4.0 has been released](http://www.mono-project.com/docs/about-mono/releases/4.0.0/) it will be a lot easier for people to get a compatible version

**Comment by davidfowl** [comment]
W00p!

**Comment by Jarga** [comment]
Dosen't look to be officially released yet, those release notes are just the draft at the moment. It's a good sign that the release is close though, can't wait!
