### ISSUE TITLE
dnvm not working for users containing space in username

### ISSUE THREAD

**Issue by mike-yan** [aspnet/Home#371]
My user name is 'Mkrtich Mazmanyan' and when I try to use dnvm list it says
'""C:\Users\Mkrtich' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.

**Comment by jchandra74** [comment]
Ran into this problem just now.

**Comment by nvivo** [comment]
Same problem here

**Comment by jchandra74** [comment]
Go to your %USERPROFILE%/.dnx/bin folder and edit dnvm.cmd and replace the last 3 lines with what I typed in my previous comment.  that will remove that error.  It actually works, just the clean up routine is messed up for some reason.  first time you run dnvm list it actually does not return anything since you haven't install anything.  run dnvm install latest which will pull down the latest dnx bits.

**Comment by davidfowl** [comment]
Filed at https://github.com/aspnet/dnvm/issues/190

**Comment by ericis** [comment]
Just had this when down-grading from beta5 to beta4

**Comment by wblackmon** [comment]
I am running VS 2015 Enterprise Update 1 with ASP.NET 5 RC 1 on Windows 10 Pro Build 1151.   I have a user name with a space in it.   I am getting the following error when attempting to run dnvm from the command line:

Get-Help : Get-Help could not find dnvm - Copy.cmd in a help file in this session. To download updated help topics type

: "Update-Help". To get help online, search for the help topic in the TechNet library at http://go.microsoft.com/fwlink

/?LinkID=107116.

At C:\Users\Wayne Blackmon\.dnx\bin\dnvm.ps1:998 char:26

+                     $h = Get-Help $_.Name -ShowWindow:$false
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  + CategoryInfo          : ResourceUnavailable: (:) [Get-Help], HelpNotFoundException
  + FullyQualifiedErrorId : HelpNotFound,Microsoft.PowerShell.Commands.GetHelpCommand
    - Copy.cmd     ForEach-Object : You cannot call a method on a null-valued expression.

At C:\Users\Wayne Blackmon\.dnx\bin\dnvm.ps1:994 char:13

+             ForEach-Object {
+             ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [ForEach-Object], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull,Microsoft.PowerShell.Commands.ForEachObjectCommand

The system cannot find the path specified.
'C:\Users\User' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
C:\Users\User Name>

I just ran dnvm install latest in powershell with no error.  Then I ran dnvm list also without errors.   However, I do get path errors when I run the same commands from a command prompt.   I have confirmed that this does work when run in PowerShell.   Use PowerShell when accessing dnvm.  I have also confirmed that dnx run does work in Powershell.  For now, use PowerShell when accessing dnvm until this issue is fixed.

**Comment by efrainsteinbach** [comment]
Just had this issue again with ".NET Version Manager v1.0.0-rc1-15540"

... I was able to fix it on my machine it by adding some quotes in dnvm.cmd: 

Line 3:
for /f "delims=" %%i in ('PowerShell -NoProfile -NoLogo -ExecutionPolicy unrestricted -Command "[System.IO.Path]::GetTempFileName()"') do set DNVM_CMD_PATH_FILE=**"**%%i.cmd**"**

i.e. add the quotes to this assgnment  `DNVM_CMD_PATH_FILE=%%i.cmd` to `DNVM_CMD_PATH_FILE="%%i.cmd"`
