### ISSUE TITLE
'System.Reflection.TargetInvocationException' being thrown on app initalization through IIS Express

### ISSUE THREAD

**Issue by 0xdeafcafe** [aspnet/Home#397]
I did a fresh install of Windows 10 Technical Preview - the one that came out yesterday - and now none of my ASP vNext applications are debugging when I run them in visual studio using IIS Express.

The exact exception is
```
An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in AspNet.Loader.dll

Additional information: Exception has been thrown by the target of an invocation.
```

My call stack is:
![](http://i.imgur.com/YkzG1VH.png)

Is there anything else I should provide?

edit1:
Upon further investigation, this is only thrown on CLR, if I use CoreCLR, it executes perfectly. Could this be to do with corrupted runtimes? My .k folder looks like this:
![](http://i.imgur.com/GwkiLBs.png)

**Comment by ilushka85** [comment]
We are seeing the same thing after the latest windows 10 technical preview update

**Comment by Henrycobaltech** [comment]
I have the same problem. When running in IISExpress, this exception would be always thrown if Visual Studio  debugger is attached.

**Comment by ilushka85** [comment]
It also happens if trying to debug by running web option which starts klr                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Henry CharlesSent: Friday, March 20, 2015 6:22 PMTo: aspnet/HomeReply To: aspnet/HomeCc: Ilya BeyrakSubject: Re: [Home] 'System.Reflection.TargetInvocationException' being thrown on app initalization through IIS Express (#397)I have the same problem. When running in IISExpress, this exception would be always thrown if Visual Studio  debugger is attached.

—Reply to this email directly or view it on GitHub.

**Comment by 0xdeafcafe** [comment]
Yeah. I just installed Win10 on my new laptop, and this error is reproducing. It worked before the upgrade, so it must be a Windows 10 issue.

**Comment by thejoshcrawford** [comment]
This started happening to me after the latest Windows 10 Update was installed.

**Comment by cwoolum** [comment]
+1

**Comment by Gorniv** [comment]
+1 after update Windows 10 (Technical Preview)

**Comment by shakehar** [comment]
Same with Windows 10 Tech preview

**Comment by Gorniv** [comment]
i can build project from cmd with kestrel, but it work without debug 
kestrel from vs 2015 ctp6 dont work

**Comment by JoshVarty** [comment]
+1

**Comment by oliverguhr** [comment]
+1

**Comment by barld** [comment]
+1

**Comment by Miguel-ezh** [comment]
+1

**Comment by SonicGD** [comment]
Seems to be fixed in new Technical Preview (10049)

**Comment by Gorniv** [comment]
I checked.Technical Preview 10049 - fixed this problem!

**Comment by davidfowl** [comment]
Sweet, everyone update :smile:

**Comment by cwoolum** [comment]
Except for this... http://www.neowin.net/news/if-you-are-a-developer-microsoft-recommends-you-do-not-upgrade-to-windows-10-build-10049

**Comment by 0xdeafcafe** [comment]
I'm installing it now to see if works for me also. thankfully I don't develop any universal stuff so this issue doesn't concern me personally💃

**Comment by thejoshcrawford** [comment]
That fixed it for me.

**Comment by 0xdeafcafe** [comment]
Working for me too. I'm going to go ahead and close this, as it seems to be fixed. Sound good @davidfowl?

**Comment by dynamiclynk** [comment]
I ran into this on Win10 Ent x64 10586. Because the project was trying to launch against a version of dnx that was not installed, after referencing the correct version in my launchSettings.json all is well.

launchSettings.json
---------------------------------
 "web": {
      "commandName": "web",
      "launchBrowser": true,
      "launchUrl": "http://localhost:5060/api/ping",
      "environmentVariables": {
        "ASPNET_ENV": "Development"
      },
      "sdkVersion": "dnx-clr-win-x64.1.0.0-beta8"
    }
