### ISSUE TITLE
Unable to run powershell install for kvm

### ISSUE THREAD

**Issue by KevinBurton** [aspnet/Home#404]
I execute the command below with an error:

@powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object
net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
The splatting operator '@' cannot be used to reference variables in an expression. '@powershell' can be used only as an
 argument to a command. To reference variables in an expression use '$powershell'.
At line:1 char:12
- @powershell <<<<  -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).
  DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
  - CategoryInfo          : ParserError: (powershell:String) [], ParentContainsErrorRecordException
  - FullyQualifiedErrorId : SplattingNotPermitted

This is under a PowerShell Administrative Console on Windows 7. Ideas?

**Comment by 0xdeafcafe** [comment]
If you're already in powershell, you can remove the `@powershell -NoProfile -ExecutionPolicy unrestricted -Command "` (as well as the trailing `"`). That's there for if you're executing in command prompt and it's telling it to execute powershell with the `-NoProfile -ExecutionPolicy unrestricted` flags.

So you're want to be running `&{$Branch='dev';iex ((new-object
 net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}`

**Comment by Jaykul** [comment]
:-1:   The "@" should NOT be there. If you remove that, the command would work in either PowerShell or CMD.  Although frankly, I don't understand why you don't just put a PS3 version on there:

```
$Branch='dev'; iex (irm https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1)
```

**Comment by 0xdeafcafe** [comment]
@Jaykul Oh. I thought that calling `powershell` inside a powershell window was irrelevant as it just initialised itself inside the window. Is it just beneficial as you can pass in the `-NoProfile -ExecutionPolicy` arguments? I'll edit my answer to remove the misinformation regardless.

**Comment by Jaykul** [comment]
You *can* call PowerShell inside a PowerShell window, you just can't use "@" because that's the "ECHO OFF" character from DOS.....

And yes, in that case, the only (dubious) value is those two switches.  The `-NoProfile` script _might_ let you side-step problems (e.g., if my profile script overwrites built-in commands you require), but I don't think that _possibility_ makes it worth requiring a restart to get the environment variable changes (see #413). I don't think it's worth having except as a troubleshooting addendum.

The `-ExecutionPolicy` switch, on the other hand, is **completely irrelevant** since we won't be executing a script: using Invoke-Expression (iex) bypasses the execution policy, and although the install script needs to call `dnvm setup`, it should just `Set-ExecutionPolicy Unrestricted -Scope Process` _within_ the `dnvminstall.ps1` script before it calls the other script.

**Comment by sankar1204** [comment]
https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1 this url its not exist anymore
404 - Not found!!

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
