### ISSUE TITLE
Error with command dnu restore on Linux

### ISSUE THREAD

**Issue by tiagodavi** [aspnet/Home#429]
I downloaded the last version in development of ASP.NET vNext, all ok until appear a error in my terminal on Ubuntu: "Unable to locate EntityFramework >= 7.0.0-beta3"

I typed this command before error: $ dnu restore

Sorry my english, I'm brazilian.

**Comment by encounter12** [comment]
I get the same error like the guy that reported the issue. These are the steps I follow. First I installed Yeoman:

    npm install -g yo

I followed the instructions from https://github.com/aspnet/Home and installed the DNVM Optimistic version:

@powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"

, then installed the latest ASP.NET vNext generator using the command: 

    npm install -g generator-aspnet

created ASP.NET vNext application using: 
    yo aspnet

and selected: Web Application

After trying to restore packages using "dnu restore" I received the following error: 

*'grunt' is not recognized as an internal or external command, operable program or batch file. The 'prepare' script failed with status code 1. Errors in C:\Users\Ivo\Desktop\SampleApp\project.json. Unable to locate EntityFramework >= 7.0.0-beta3. Errors in prepare. The 'prepare' script failed with status code 1.*

I am not sure if the issue is related to the dnu package or the Yeoman generator-aspnet (https://github.com/OmniSharp/generator-aspnet) but decided to report it here. Hope this information helps.

OS Version: Windows 10 Technical Preview (10.0.9926)
NodeJS Version: v0.12.2
Yeoman Version: 1.4.5
.NET Version Manager: v1.0.0-beta5-10365

**Comment by OlivierAlbertini** [comment]
same problem on OSX Yosemite

**Comment by mbgreen** [comment]
I think you may need to update which feed NuGet is restoring packages from. By default it restores from https://www.nuget.org/api/v2 and it looks like the latest stable packages are at https://www.myget.org/F/aspnetmaster/api/v2. You can specify which source to use by running the following.

```
dnu restore -s "https://www.myget.org/F/aspnetmaster/api/v2"
```

Alternatively, you can update which package source is used in your environment specific config file. There is some documentation for how to do that in your environment here: https://github.com/aspnet/Home/wiki/Configuring-the-feed-used-by-dnu-to-restore-packages

With that said, I am able to restore successfully, but building the project fails when running `dnu build`. I haven't looked into it, but I'm fairly certain the yo aspnet generator template was created to work with an older version of the framework. The k runtime provides the correct runtime. You can use `kpm restore` and `kpm build` and everything works.

**Comment by muratg** [comment]
@mbgreen is correct, you'll need to update your package sources.

**Comment by imkheong** [comment]
Hi

I created a web application using yo aspnet on Ubuntu linux. When running 'dnu restore' it says No command 'dnu' found, did you mean:...


Can i know how can i resolve the problem?

**Comment by muratg** [comment]
@imkheong how did you install dnx? Did you try https://github.com/aspnet/Home/blob/1af741519f9841455e231bb686b0723704e039ed/GettingStartedDeb.md?

**Comment by imkheong** [comment]
@muratg I install DNVM with the given link. Other than the last step "Add Sources to NuGet.config" which I am not certain, I followed all other steps correctly.

I am unable to call 'dnu' as a command.

I tried also using 
dnvm exec 1.0.0-beta4 dnu restore and 

Seems it may not have been added correctly.

I tried sudo dnvm, it says sudo: dnvm: command not found.
![image](https://cloud.githubusercontent.com/assets/6950029/7702655/48ba30d8-fe64-11e4-8818-a1eadd5817f7.png)

**Comment by muratg** [comment]
OK, there's no active DNX in your case. Type `dnvm use 1.0.0-beta4` and then try the dnu commands.

**Comment by imkheong** [comment]
@muratg, I tried <code>dnvm use 1.0.0-beta4</code> and it says <code>Cannot find dnx-mono.1.0.0-beta4, do you need to run 'dnvm install 1.0.0-beta4'?</code>

**Comment by muratg** [comment]
Interesting, your `dnvm list` output seems to show `1.0.0-beta4`. Sure you can try the install command. or get the latest with `dnvm upgrade` and `dnvm use` it.

**Comment by imkheong** [comment]
It was indeed due to missing 'unzip' component, when <code>dnvm upgrade -f</code> is issued, it returns <code>unzip is required</code>. After doing <code>apt-get install unzip</code> it works perfectly.
Thanks @muratg for the help.

**Comment by muratg** [comment]
@imkheong glad that you're unblocked :)
