### ISSUE TITLE
Running Gulp (or anything) from the command line on a dnx project.json command execution?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Home#451]
I'm working with Brackets and Gulp prior to CTP7 hitting. I have a command setup to use WebListener:
```
"commands": {
        "test": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5001"
},
```
I would like to have my `gulpfile.js` run whenever I execute my `test` command. Because I'm using Brackets right now, I can't use VS's nice build events feature to run Gulp automatically.

I am aware of the existence of `gulp.task('watch', function () { ... }`, but I would prefer not to have to type `gulp` even once before executing `dnx . test`. I want Gulp to run automatically once each time I issue my `dnx . test` command.

I tried hooking it by way of the `scripts` of `project.json` by simply replacing the `echo xxx` line with the command `gulp`:
```
"scripts": {
        "prepack": "echo before packing",
        "postpack": "echo after packing",
        "prepublish": "echo before publishing",
        "postpublish": "echo after publishing",
        "prerestore": "echo before restoring packages",
        "postrestore": "echo after restoring packages",
        "prepare": "echo prepare"
},
```
... but nothing will trigger Gulp prior to firing up WebListener. `prerestore` and `postrestore` will run Gulp when I use `dnu restore`, but I may as well be typing `gulp` at the command line once (using a gulp watch task) before running `dnx . test` rather than using `dnu restore` every time, since I usually do not need to restore packages to test run my app.

Can it be done?

If not, I'd like to float a feature request for one more `scripts` option for something like `precommand`, which could be a command line statement to be run when any `dnx . {command}` is issued? This could have a variety of uses well beyond just a simple Gulp call. It would be even better if you could attach command line commands to any of your dnx commands (e.g., `"precommand": [{"test": "gulp"}, {"another dnx command": "another command line command"}]`).

**Comment by jasoncavett** [comment]
@GuardRex I see this issue is closed. Did you discover your own answer? I'm hitting up against the same problem myself. (Want watchers to automatically come on, want certain tasks to run when I run DNX, etc.) I attempted to go the other way by using [gulp-dnx](https://www.npmjs.com/package/gulp-dnx) but it only seems to integrate with the Windows side of things due to requiring Powershell.

Would appreciate it if you have any guidance that you can provide.

**Comment by GuardRex** [comment]
@jasoncavett Unfortunately, I never had a solution for this (other than perhaps scripting something in the OS to run the commands for me). As you can see, no ideas came back when I opened the issue for a week, and my idea for a `precommand` feature to run one or more scripts before dnx does its stuff wasn't popular. VS 2015 RC came out about two weeks after I closed this. I went to VS 2015 on April 29, and now I have VS run my Gulp `watch` tasks when the solution loads.

**Comment by jasoncavett** [comment]
@GuardRex Okay, thank you for the follow-up. VS2015 seems good because of the additional integration, such as triggers for running tasks (e.g. on project open). Unfortunately, it's not so good for VSCode when I'm not using Visual Studio. However, I reported the issue to the developer on the gulp-dnx team, and it looks like he is going to get support for a non-Powershell solution so that I can use Gulp directly, which can then trigger off DNX as well. Progress!
