### ISSUE TITLE
RSS feed for announcements

### ISSUE THREAD

**Issue by Daniel15** [aspnet/Home#511]
I just noticed that announcements are being posted as Github "issues" over at https://github.com/aspnet/Announcements/issues. Are they going to be syndicated onto the ASP.NET site? Is there a way to get an RSS feed of these?

**Comment by MikeSchlichting** [comment]
Is this pattern (repository/announcements/issues) used across other dotnet repositories?  It would be great to have consistency between dotnet repos for delivering critical announcements and breaking changes.

**Comment by Daniel15** [comment]
Personally I think that using Github issues for announcements is quite strange. I've never seen any project do that before and it seems like an inefficient use of Github's issues (which are already quite limited in what they can do)

**Comment by Eilon** [comment]
I plan to build something to produce an RSS feed.

I agree using GitHub issues is weird, but we couldn't come up with anything better.

We needed something that was:
* Persistent
* Filterable (e.g. by milestone or category)
* Ideally searchable
* Doesn't require a login for readonly access
* Allows commenting for asking clarifications
* Has a notification system for alerts
* For anything that requires logins (e.g. commenting), ideally use an identity system that likely users would already have
* So easy to use that everyone working on ASP.NET / EF would easily be able to post items (i.e. don't have to learn a completely new system)

GitHub issues is the only thing we found that had all of this (aside from a completely custom solution).

Other systems we considered:
* Discourse (expensive to use hosted version, a hassle to host ourselves)
* Google Groups (requires login even just to read)
* Forums (e.g. ASP.NET Forums)
* Slack (not really what it's meant for)
* JabbR (deliberately not chosen because it's what @davidfowl would want :smile: plus, not fully persistent or searchable)

**Comment by Daniel15** [comment]
Discourse is terrible so I'm glad you didn't go with it :)

Your reasoning definitely make sense, it's just really interesting to see given people usually complain about Github's issues system being very limited compared to pretty much every other bug tracking system. At least it's getting a bit better these days.

Once you have the RSS feed working, it'd be good to show that on the ASP.NET site :+1:

**Comment by Daniel15** [comment]
Why not an announcements board on the ASP.NET forums?

**Comment by Eilon** [comment]
We considered ASP.NET Forums but we felt that by being a discussion forum it would encourage discussions as opposed to focusing on announcements. That's not necessarily bad, but isn't the point of it. Here we want to keep discussions in the specific repos where those specific features are being built.

Also, using GitHub to author and consume these notifications in my view is easier. Using Markdown is nice, the notification system is easier to use (for me at least). Also, having labels and milestones is quite convenient - it's easy to filter down to which items you wish to see.

**Comment by rtpHarry** [comment]
This needs to be linked to from somewhere.

I have been immersing myself in asp.net 5 over the last few days and read all the different places but have only just stumbled accross this because I ran out of stuff to read and started on the Home repo issues.

So far I've been playing spot-the-difference with everything. This would have been handy and is a valuable resource to get in front of developers.

Some places this should be highlighted:

  - http://docs.asp.net/en/latest/
  - http://www.asp.net/vnext
  - https://github.com/aspnet/home#documentation-and-further-learning
  - https://github.com/aspnet/home#repos-and-projects
  - https://github.com/aspnet/home/wiki

**Comment by Daniel15** [comment]
Any updates on this? Watching the announcements repo is extremely noisy as I get an email every time someone comments. I just want emails about changes. If there was an RSS feed, I could just subscribe to that (or get email notifications through IFTTT or something).

**Comment by Eilon** [comment]
@Daniel15 we're starting to lock threads in the Announcements repo as an experiment and creating per-repo threads for the discussions - it seems to be going well so far.

You can always mute a thread by unsubscribing from it or muting it in the notifications page. That certainly helps reduce a lot of the noise.

But anyway, if the experiment continues to go well we'll lock all new threads, and maybe go back and lock some existing chatty threads (after creating new discussion locations for each).

**Comment by Eilon** [comment]
Closing this out because it seems the current Announcements pattern is working alright.
