### ISSUE TITLE
Cannot run starter web application on beta5 

### ISSUE THREAD

**Issue by dopare** [aspnet/Home#531]
![error](https://cloud.githubusercontent.com/assets/4062518/7436719/cf62c4de-f03f-11e4-908d-37f6c11631cd.png)

I have updated dnx and packages to beta5 and can't run web app.

**Comment by davidfowl** [comment]
That happens when you update sometimes :smile: . We made a breaking change, so now you have to pass in the base path to the Configuration constructor:

```
public Startup(IHostingEnvironment env, IApplicationEnvironment appEnv)
        {
            // Setup configuration sources.
            var configuration = new Configuration(appEnv.ApplicationBasePath)
                .AddJsonFile("config.json")
                .AddJsonFile($"config.{env.EnvironmentName}.json", optional: true);
```

**Comment by dopare** [comment]
Fixed, Thank you very much. 

Got another problem 

` MissingMethodException: Method not found: 'Microsoft.Framework.Runtime.Compilation.ILibraryExport Microsoft.Framework.Runtime.ILibraryManager.GetLibraryExport(System.String)'.
Microsoft.AspNet.Mvc.Razor.Compilation.RoslynCompilationService.GetApplicationReferences() `

**Comment by dopare** [comment]
Latest beta5 resolved the issue.

**Comment by evil-shrike** [comment]
I got the same issue (MissingMethodException) on the latest VS2015 RC and beta4. 
@dopare you said, that beta5 resolved the issue but I can't find any beta5 package not on api.nuget.org nor on nuget.org. It's only daily builds on myget feed. 

Just try to understand how it looks: people install RC of VS2015, it will install beta4 of AspNet5 and an app doesn't work.

**Comment by davidfowl** [comment]
We're going to be changing this behavior in the next version of Visual Studio. In the RC here is the behavior:

- File new project, everything is dandy
- You run `dnvm upgrade -u`
- File new project, nothing runs

This happens because Visual Studio respects the upgrade creates new projects with the version of the dnx that you upgraded to (look in `global.json`). The original idea was that VS stays in sync with your command line. The problem that causes is what you're experiencing, breaking changes. We realized that doing that is useless because the templates themselves are still pinned to beta4, so the best thing to do for file new project is to hardcode the known dnx version that works with the in box VS templates.

**Comment by dopare** [comment]
@evil-shrike I'm trying not use VS for build when working with nightly builds. I didn't got MissingMethodException on VS2015 RC and beta4. My issue was when I tried to use VS generated beta4 source for beta5.

**Comment by MikeSchlichting** [comment]
Perhaps we should create a project template that is kept in sync with the latest bits and include it in the setup instructions so that anyone will be able to install the latest DNX and have a matching project template.  It will make it easier for new developers to get up and running and David won't have to keep explaining the latest breaking changes.
