### ISSUE TITLE
Question: Plans for final ASP.NET 5 release and .NET 4.6 interopability

### ISSUE THREAD

**Issue by mkosieradzki** [aspnet/Home#532]
First of all I am sorry if this question is redundant, but I did a lot of searching and digging and I am unable to find answer.

I am researching possibilities of integrating ASP.NET 5 code (dnx451) with .NET 4.6 (net45).

My ultimate goals are:
1. Host ASP.NET 5 application with MVC6 using HttpListener inside net45 application for example in Azure Service Fabric.
2. Host ASP.NET 5 inside a separate appdomain and pass appriopriate services, and marshal web requests from host applications.

I have a working solutions for both (except MVC6 of course :) ) based on Owin and net45 but as far as I understand correctly OWIN is discontinued and the new better IApplicationBuilder interface takes precedence (that's great).

After digging throughout hosts implementation - I understand that net45 are different nuget frameworks but are exactly the same runtime. Many dnx451 beta4 packages are also compatible with net45, but a lot of them are not compatible including Microsoft.AspNet.Mvc.*, Microsoft.AspNet.Hosting.*, Microsoft.Framework.Runtime.*.

Do you ultimately plan to merge net45 with dnx451 and create for example net46? Or do you plan to maintain two separate worlds and provide some ways to connect one to another?

What is the suggested way to deal with two scenarios mentioned above.

I have successfully started a web server with MVC support using .NET 4.5 and raw assemblies from dnx451 manually attached to the project (kinda nasty, but works). But there is a lot of plumbing to do for example implementation of ILibraryManager which is used for attribuite based routes discovery.

Still it all doesn't feel really right.

I understand there are some hosting solutions currently developed (not available in beta4).

For the first scenario it would be great to have a utility class starting a web server using HttpListener  with a possibility to provide some services down to the hosted application that can be started from a folder.

For the second scenario it is necessary to pass a new HttpContext with special marshalled streams underneath. In OWIN it's a trivial task due to the simplicity of entire framework: you are passing OwinContext down to the AppDelegate instantiated in second appdomain. So solution can instantiate an application and return appdelegate to allow manual control on passing HttpContext to this delegate.

**Comment by Eilon** [comment]
There are dnx451 and dnx46 that map to ".NET 4.5.1 + DNX" and ".NET 4.6 + DNX." That is, DNX is an execution environment that can run on various underlying .NET frameworks, including .NET 4.5.1, .NET  4.6, Mono 4.x, and Core CLR. DNX adds concepts such as running directly from source code, blurring the line between referencing a NuGet package or a source project, a slightly different servicing behavior, and many other differences.

It's true that some packages are cross-compiled to both DNX frameworks and to "regular" .NET. For example, EntityFramework, Logging, DependencyInjection, and several others. Those packages can run on any of the frameworks that they target. Cross-compiling other packages to more different frameworks is generally outside the scope of the new system because those packages often have strict dependencies on the new DNX capabilities.

If there are specific packages that you would like to see supported on other frameworks, please log issues in the appropriate repo, including a statement saying why it would be useful.

**Comment by davidfowl** [comment]
@mkosieradzki What you want to do is technically possible (and it looks like you did hacked it up) but we currently don't wish to *support* running on vanilla net45 across the entire stack because it potentially brings too much baggage back into our brand new and shiny stack. We make all kinds of assumptions because we control the entire stack and host from the bottom up.

A compromise might be making all of the lower level .Abstractions packages run on any platform, so that anyone could choose to reimplement it on whatever platform you'd like but we shouldn't be providing each of the implementations because it not something we'd want to take on as a team.

**Comment by mkosieradzki** [comment]
Thanks a lot for both answers.

@Eilon - I have described two scenarios. Both of them require almost all dnx packages inside vanilla .NET 4.5.1, for the same reason you mentioned: "those packages often have strict dependencies on the new DNX capabilities" - and those packages provide implementation for those capabilities on to of vanilla framework. This is how I understand DNX451 package. So it's rather all-or-nothing - and I really like the new way of hosting applications without a temporary folder, with all those abstractions for Filesystem sourcing, Caching dependency resolution etc - it improves a lot and I would like to use those improvements inside my hosting scenarios!

@davidfowl I really understand this position and that's why I am asking about plans not how "to do it today". You told me sometime ago about some managed hosting classed that are under development (this project is not available in the beta4). There are some requirements in scenarios I mentioned above that it would be great to have addressed with the upcoming managed hosting library.

1. Pass some services from the hosting app. Can be MarshalByRef to prevent tainting ASP.NET 5 app domain, but it's also OK to run in the host vanilla AppDomain. But it's performance-critical to have this running inside a single process.
2. It is acceptable to run ASP.NET 5 app from a physical temp directory but it would be way better to utilize all the new great hosting features and configure proper host even with the cost of implementing multiple abstraction interfaces! So if the vanilla host could do all the configuration including filesystem, caching, package resolution, etc it would be really great.
Currently available host implementations do not allow passing nothing more than command line arguments. :)

Does such scenario comply with your development plans or is this something that must be "hacked" into the implementation?
