### ISSUE TITLE
Move AssemblyName property from xproj to project.json

### ISSUE THREAD

**Issue by ggrnd0** [aspnet/Home#541]
Move `AssemblyName` property from `*.xproj` to `project.json` as property `name`.

**Comment by ggrnd0** [comment]
`RootNamespace` too.

**Comment by sayedihashimi** [comment]
Thanks for the note.
I was discussing this last week with @BillHiebert, but haven't had a chance to discuss with anyone else yet. We discussed moving properties like the following out of the .xproj file.
 - ```RootNamespace```
 - ```AssemblyName```
 - ```OutputPath``` / ```BaseIntermediateOutputPath```

The context there was that it would be nice if [ASP.NET 5 yeoman generators](https://github.com/OmniSharp/generator-aspnet) could reuse the values easily. Today they are not shared, and creating new files in Visual Studio could be different than those generated using ```yo aspnet```. Being in an MSBuild file it's possible but I'd rather that they be in a json file.

After discussions with Bill instead of placing this into ```project.json``` we feel that it may be better to place items like this into a new file, let's say ```Properties\tooling.json```. The reasoning here is that we think that the ```project.json``` file should contain values that are needed for the runtime and we should keep it as lean as possible so that it is still easily editable w/o any tooling.

Can you give us more context on your scenario and why you made the suggestion?

What are your thoughts on the proposal above?

cc @davidfowl @glennc

**Comment by glen-84** [comment]
"name" may be confused with "title" which already exists (?)

**Comment by davidfowl** [comment]
@sayedihashimi I've been thinking about this a bit and I think we should look at project.json as an open project format that is completely declarative. I'm not sure that I like OutputPath and BaseIntermediateOutputPath in there though.

**Comment by ggrnd0** [comment]
I think `project.json` must keep any information is needed for build and distribute package.
    RootNamespace needed only for create new class, but it is too important to place in.

i do not think is `Properties/tooling.json` good idea.
1.

**Comment by smbecker** [comment]
@ggrnd0, RootNamespace isn't only used for new classes. Historically, it was also used to determine embedded resource names. Currently it now uses project name as the basis for that, which is a bit confusing at first.

**Comment by ggrnd0** [comment]
@smbecker, i saw there doubles of embedded resources with 
`Project.folder.file.ext` and `folder/file.ext` resource names.
    I think second will only one format of resource name  in near future...

**Comment by glen-84** [comment]
Related, I'm not sure that the "webroot" property should be part of the schema for the project.json file, as this is not relevant to other project types (a console app, for example).

Two possible options:

1. The idea above proposed by @ggrnd0, where you'd have files like:

    ```
    project.json             (the current file, with webroot removed.)
    project.build.json       (build-related properties)
    project.web.json         (or project.asp.json, with webroot, etc.)
    ```

    These would be collapsed by VS. project.json and project.*.json would be loaded and merged.

    See also https://github.com/aspnet/dnx/issues/1817, which would mean file names like dnx.json, dnx.build.json, etc.

2. A feature to import/include other JSON files within project.json, for example:

    ```
    {
        "!include": "properties/build.json",
        "!include": "properties/asp.json"
    }
    ```

    I'm not sure if the JSON schema would apply *before* or *after* inclusion.

    The benefit here is that the developer can choose where to put the config files, and the files could have their own schema.

Actually thinking about this more, I'm not sure why build & asp properties should be in project.json at all. Why not just have separate, unrelated files for this? I think this is basically what @sayedihashimi was suggesting.

So something like:

project.json
Properties/build.json
Properties/launch-settings.json (hyphenated, the current camelCasing seems weird/inconsistent)
Properties/web.json (or asp.json)
etc.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
