### ISSUE TITLE
Please explain how to install and use SecretManager with VS 2015

### ISSUE THREAD

**Issue by freecellwiz** [aspnet/Home#601]
I'm new to VS 2015 and the dnx/dnvm//dnu stuff.  I was trying to follow a tutorial about Facebook auth (http://docs.asp.net/en/latest/security/sociallogins.html) which talked about using SecretManager.  The instructions show say to run 

dnu commands install SecretManager

I finally figured out where dnu lives and manually added it to my path (I don't seem to have a VS2015 command prompt), so I can run dnu, but it errors with "Unable to locate SecretManager".  The next step is to run 

user-secret

again, presumably from a VS command line?  I also am not clear where there "global" tools are getting installed.

Any pointers are appreciated.  I'm having trouble finding any meaningful documentation about how to do this.

John

**Comment by sksbrg** [comment]
Hi, I experienced the same problem which seems to be caused by a unresolved dependency (`Unable to locate SecretManager >= 1.0.0-beta4-10173`). After changing the version in `C:\Users\<username>\.dnx\bin\packages\SecretManager\1.0.0-beta4\app\project.json` from `1.0.0-beta4-10173` to `1.0.0-beta4` running `dnu commands install SecretManager` did succeed on my machine: `The following commands were installed: user-secret`.

Seems we are not the only ones running into this issue: https://github.com/aspnet/UserSecrets/issues/15.

With kind regards,
Stefan

**Comment by freecellwiz** [comment]
Stefan - 

Your steps worked for me.  I manually edited the project.json file and re-ran the install with no problems.  Thank you!

John
