### ISSUE TITLE
page for libraries compatible with core

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Home#602]
Hi, I'm looking to a list of the libraries, microsoft and community, compatible with .net core. It is already available? has been planned? I think may be very useful. How can I plan to move an ecommerce site to core if the pdf library that I use to generate the invoices is compatible with core?

**Comment by Eilon** [comment]
We don't have any such list. I think if we had such a list it would probably be a temporary list until the ecosystem has grown enough where it's not as big a deal. I say temporary because eventually the list will grow huge, plus people might have different views as to what exactly is "compatible." But perhaps having a list of packages such as xUnit.net, Json.NET, Autofac, Serilog, etc. would be useful for people to start checking out...

@danroth27 @DamianEdwards for additional thoughts on this.

**Comment by danroth27** [comment]
@yishaigalatzer It would be nice if there was a way to query nuget.org for this.

**Comment by danroth27** [comment]
@johnataylor

**Comment by DamianEdwards** [comment]
I think we should definitely have a curated list of the most popular packages that people would ask about and their .net core compatibility status. It could be a simple file in this repo (to facilitate pull requests) that we can link to from other places like www.asp.net, docs.asp.net, etc.

**Comment by csharpfritz** [comment]
This feels like a list that could be derived from NuGet.org based on the
submission of packages with dnxcore TFMs.

**Comment by yishaigalatzer** [comment]
Current thoughts are to remove framework filtering from nuget.org. We need to see how far we go with this direction, and then make a call on this ask for nuget.org.

**Comment by Eilon** [comment]
It doesn't really have to be framework filtering. It's more a matter of running a script based on the metadata on nuget.org.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
