### ISSUE TITLE
What are my options for sharing code between DNX / ASP.NET 5 projects (project.json / xproj) and other C# projects (csproj) within a single solution?

### ISSUE THREAD

**Issue by mattbrooks2010** [aspnet/Home#621]
# Scenario

I'm experimenting with Visual Studio 2015 RC, specifically looking at switching to the new ASP.NET 5 framework, project structure and the new DNX that runs ASP.NET 5 applications.

My employer has many existing solutions targeting .NET Framework 4.5.2. In our existing Visual Studio solutions we might have the following projects:

    [Solution] Sample.sln
        [Folder] src
            [Project] ClassLibrary.csproj
            [Project] WindowsService.csproj
            [Project] WebApplication.csproj
        [Folder] test
            [Project] ClassLibrary.UnitTests.csproj
            ...

In this scenario, `ClassLibrary.csproj` is a C# class library containing shared code. It is a dependency of / referenced by both `WindowsService.csproj` and `WebApplication.csproj`.

We aren't specifically trying to target .NET Core, `dnxcore50`. At this stage we are happy targeting .NET Framework, `dnx451`. However we are absolutely trying to leverage the new features of ASP.NET 5 and associated project structure.

Below are some options I've thought of but both have issues.
 

# Option 1

When we replace the `WebApplication.csproj` project above with a new ASP.NET 5 DNX project `WebApplication-dnx` then we can still reference the `ClassLibrary.csproj` from both this new DNX project and the  existing `WindowsService.csproj` project. However some issues arise:

1. This approach means any changes to code in `ClassLibrary.csproj` need a rebuild to be visible in the running `WebApplication-dnx`. This isn't surprising but means we do not get full compile-from-source benefits for `WebApplication-dnx`.

2. We cannot easily target other frameworks, e.g. `dnxcore50`. As above, this isn't specifically a goal at this stage.

# Option 2

If we replace `ClassLibrary.csproj` with a DNX class library project^ `ClassLibrary-dnx` then the problems in option 1 do not apply. This approach would seem to be more in-keeping with the way the .NET runtime and associated technologies such as ASP.NET will be packaged moving forward.

However I cannot find a way to reference `ClassLibrary-dnx` from `WindowsService.csproj`. If this approach is viable I imagine the solution has something to do with the project level-option for `Produce outputs on build` and then referencing the `.nupkg` or perhaps even the `.dll` that is produced during the build. However, I cannot see a clean way of achieving this via the tooling.

^ DNX class library projects are called `Class Library (Package)` in VS 2015 RC. This project type was previously called `ASP.NET Class Library` in the CTPs.

# Summary

Based on the information above I'm looking for:

1. Some feedback to my scenario options and issues.

2. Suggestions for other options I have not thought of.

3. Perhaps an indication of which approach should be used moving forward.

Thanks in advance!

**Comment by mattbrooks2010** [comment]
Based on the feedback for [this Stack Overflow question](http://stackoverflow.com/q/30355208/1464820) I have been able to produce working proof of concept by copying the approach taken by [aspnet/EntityFramework](https://github.com/aspnet/EntityFramework) of having both a .csproj and a .xproj for each project, contained in separate VS solutions. 

Having two separate VS solution files adds a little overhead, although does present some organisational benefits.

Would you recommend anything further or different?

**Comment by Eilon** [comment]
@mattbrooks2010 regarding option (2), you will eventually be able to reference an XPROJ (project.json) from a CSPROJ file. I think @sayedihashimi 's team is working on that so maybe he can shed some light on the status of the feature.

I think in your case you would ideally end up using XPROJ (project.json) for all your class libraries, regardless of their targets, and then have ASP.NET 5 projects of course use XPROJ (project.json), and then have your other .NET 4.x projects (ASP.NET 4x, Windows Forms, WCF, etc.) continue using CSPROJ files.

**Comment by mattbrooks2010** [comment]
@Eilon many thanks, that is very useful information. I agree with your analysis of my ideal case. It would be good to hear from @sayedihashimi on the status of the feature before I close this off.

**Comment by sayedihashimi** [comment]
We have discussed this but haven't actively started working on it. To enable this we will need an engagement between the ASP.NET runtime and VS Project & Build teams. My team can help but most work is outside of our area.

**Comment by mattbrooks2010** [comment]
@sayedihashimi @Eilon many thanks again for this insight. From what you've said, is it safe to assume  this feature will not make it into VS 2015 RTM? If so, could such a feature be added out-of-band, e.g. as a VS extension, or would we have to wait for a VS product update, e.g. VS 2015.1?

**Comment by mattbrooks2010** [comment]
Potentially related:

"The ASP.NET team would like to be able to ship [ASP.NET and Web Tools] in the future out-of-band, similar to how updates are delivered in the extension gallery or in the NuGet gallery."

[ASP.NET Community Standup - June 30, 2015](http://blogs.msdn.com/b/webdev/archive/2015/06/30/asp-net-community-standup-june-30-2015.aspx)

**Comment by mkosieradzki** [comment]
@mattbrooks2010 Thanks for linking.

**Comment by mattbrooks2010** [comment]
Potentially related:

"Beta8 is the last major feature milestone planned before moving into a stabilization phase for RC1. We will work on enabling complete end-to-end experiences in Visual Studio and Visual Studio Code."

[ASP.NET 5 Schedule and Roadmap](https://github.com/aspnet/Home/wiki/Roadmap)

**Comment by HellBrick** [comment]
Is there any update on this? I'm looking into what it would take to migrate some parts of a big solution to .NET Core and I'm having a hard time figuring it out. Imagine the following simplified example:

`Library.Classic` - .NET 4.6 class library;
`App.Classic` - .NET 4.6 console app, references `Library.Classic`
`App.MustStayClassic` - .NET 4.6 console app, references `Library.Classic`

The goal is to replace `App.Classic` with a .NET Core console `App.Package` that can run on DNX without touching the code of `App.MustStayClassic` (the real world representation of `App.MustStayClassic` is 100+ projects that can't all be ported simultaneously).

The obvious things to try were:

**0**: turn `Library.Classic` into .NET Core `Library.Package` and use it throughout the solution. This looked like the most straightforward and logical way to port things: since `project.json` projects can target both .NET Core and full .NET, it seemed intuitive the classic `csproj` projects should be able to consume the output of a `project.json` project if the later provides a full framework build. Unfortunately, like it was mentioned in this issue, it's currently not possible to reference `project.json`-projects from `csproj`-projects. Oh well...

**1**: just reference `Library.Classic` from `App.Package`. `dnu wrap` is called under the covers, `global.json` and `wrap/Library.Classic/project.json` are generated. But this doesn't work with "can't restore `Library.Classic` package" excuse, which actually makes sense: this is a full-fledged .NET 4.6 library, it can use tons of things .NET Core doesn't have, so dnu is looking for `Library.Classic` project that can target .NET Core and doesn't find one. Which leads us to...

**2**: turn `Library.Classic` into a PCL `Library.Portable` and use it throughout a solution. New Windows SDK adds PCL profiles that allow targeting .NET Core + .NET 4.6. Sounds like exactly what we need, right? Nope, doesn't work either.

*Problem 2.0*: `dnu wrap` fails when the reference from `App.Package` to `Library.Portable` is added:

```
Wrapping project 'Library.Portable' for '.NETPortable,Version=v5.0'
  Source F:\Software\DotNetCoreTest\Library.Portable\Library.Portable.csproj
  Target F:\Software\DotNetCoreTest\Library.Portable\project.json
System.ArgumentNullException: Value cannot be null.
Parameter name: profileValue
   at NuGet.NetPortableProfile.Parse(String profileValue)
   at NuGet.VersionUtility.GetShortFrameworkName(FrameworkName frameworkName)
   at Microsoft.Framework.PackageManager.WrapCommand.GetShortFrameworkName(FrameworkName targetFramework)
   at Microsoft.Framework.PackageManager.WrapCommand.AddWrappedProjectPath(JObject projectJson, String relativeCsProjectPath, FrameworkName targetFramework)
   at Microsoft.Framework.PackageManager.WrapCommand.EmitProjectWrapper(XElement projectElement)
   at Microsoft.Framework.PackageManager.WrapCommand.WrapCsProject()
   at Microsoft.Framework.PackageManager.WrapCommand.Execute()
   at Microsoft.Framework.PackageManager.WrapConsoleCommand.<>c__DisplayClass0_0.<Register>b__1()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Framework.PackageManager.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
```

It does *something* though: adds `Library.Portable.xproj`, an empty `global.json` and modifies `App.Package`'s `project.json` and `project.lock.json`. At least VS tries to reference the project now.

*Problem 2.1*: dnx 451 won't build because of things like
```
DNX 4.5.1 error CS0433: The type 'AssemblyFileVersionAttribute' exists in both 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

The error message is very confusing, but it goes away once `dnx451` is replaced with `dnx46` in `project.json`. `App.Package` with an empty `Program.Main()` actually builds now, but it's too early to celebrate...

*Problem 2.3*: classes from `Library.Portable` can't be used in `App.Package`.

```
Error	CS0103	The name 'GreatAnswer' does not exist in the current context	App.Package.DNX 4.6	F:\Software\DotNetCoreTest\App.Package\Program.cs	13	IntelliSense
...
Error	CS0103	The name 'GreatAnswer' does not exist in the current context	App.Package.DNX Core 5.0	F:\Software\DotNetCoreTest\App.Package\Program.cs	13	IntelliSense
```

`Library.Portable` references are properly resolved by both `dnx46` and `dnxcore50`. The namespace and the class class I'm trying to use exists in both the `Library.Portable` code and the binaries that were copied to `\artifacts\bin\App.Package` at the previous step, when `App.Package` could still be built. But they don't exist as far as the compiler is concerned.

And this is where I'm currently stuck =(

**Comment by mattbrooks2010** [comment]
In [ASP.NET Community Standup — Beta 7 Update, Aug 11, 2015](https://www.youtube.com/watch?v=s86wq0aVuIU&list=PL0M0zPgJ3HSftTAAHttA3JQU4vOjXFquF&index=0) at approx. 40m 0s @DamianEdwards confirmed there are plans to allow a DNX based class library to be referenced from a .csproj project by RTM.

**Comment by sayedihashimi** [comment]
Correct, we are hoping we can enable allowing vanilla .net projects to reference a DNX projects by the time asp.net 5 is RTM.

**Comment by mattbrooks2010** [comment]
Thanks for confirming.

**Comment by runxc1** [comment]
Is this now possible

**Comment by totht91** [comment]
In RC1-Update1 still not possible...

**Comment by arankun** [comment]
I confirmed that this still possible as well.

**Comment by HellBrick** [comment]
During the last community stand-up I asked Damien when this feature is estimated to arrive and he [said RC 2 is the current plan](https://youtu.be/hmDEt8YtElE?t=15m22s).

**Comment by rolfik** [comment]
It is being mentioned here:
https://github.com/dotnet/corefx/issues/6124

**Comment by sporty81** [comment]
I was able to get xproj and csproj working together in the same folder. Check out this blog post: [http://stackify.com/using-both-xproj-and-csproj-with-net-core/](http://stackify.com/using-both-xproj-and-csproj-with-net-core/)
