### ISSUE TITLE
Gentoo Documentation

### ISSUE THREAD

**Issue by allenh1** [aspnet/Home#625]
Would it be ok to write some Gentoo Linux documenation?

**Comment by jasonwilliams200OK** [comment]
@allenh1, a pull request is better than an thousand :100: 0 issues. 
:+1:  for Gentoo, CentOS, Mint, Arch and Alpine too (when its support will arrive: https://github.com/dotnet/coreclr/issues/917).
I don't :thought_balloon: anyone would have problem with Gentoo documentation matching OSX, Ubuntu, Windows.

On this note, I think we should have a `Documentation` directory in this repo's root, instead of stuffing up wiki and README, similar to what https://github.com/dotnet/coreclr, https://github.com/dotnet/corefx and https://github.com/torvalds/linux. Why do they prefer docs this way? @sindresorhus explained it here precisely: https://plus.google.com/+sindresorhus/posts/QSS2du26Mg4.

**Comment by jasonwilliams200OK** [comment]
Update: CoreCLR and CoreFX now build on Gentoo (https://github.com/dotnet/corefx/issues/9187) and Alpine (dotnet/coreclr#917).

**Comment by allenh1** [comment]
I don't think this is relevant anymore -- I'm gonna close this.
