### ISSUE TITLE
EF7 context not initializing

### ISSUE THREAD

**Issue by IonRobu** [aspnet/Home#720]
Hello,

I downloaded last runtime version: beta6-12170 and tried to initiate a Context:

```C#
services
.AddEntityFramework()
.AddSqlServer()
.AddDbContext<Context>(o => o.UseSqlServer(contextConnectionString));
```
where services is injected IServiceCollection, and contextConnectionString is a valid sql server connection string. But when I try to use context:

using (var context = new Context())
{
....

I get the error:
Additional information: No database providers are configured. Configure a database provider by overriding OnConfiguring in your DbContext class or in the AddDbContext method when setting up services.
If I call UseSqlServer(contextConnectionString) in OnConfiguring method of context, it works. 
Does anybody have the same issue?

Thanks,
Ion

**Comment by Eilon** [comment]
@divega @rowanmiller

**Comment by rowanmiller** [comment]
Hey,

Because the settings for you context are setup in DI, you need to resolve the context from DI rather than instantiating it inline. If you are using it in an MVC controller then just take the context as a constructor parameter.

```c#
private Context _context;

public MyController(Context context)
{
    _context = context;
}
```

~Rowan

**Comment by IonRobu** [comment]
Hello Rowan,

It's working now, thanks! As you said, I injected the context, instead of initializing with new

Ion

**Comment by Antaris** [comment]
Hi,

I am now receiving this since upgrading to beta6 also. I resolve my context from an `IServiceProvider` as part of my test suites:

        public ServiceTestBase()
        {
            var services = new ServiceCollection();

            services.AddEntityFramework()
                .AddInMemoryDatabase()
                .AddDbContext<C>();

            services.AddSingleton<IWorkContext>(p => CreateWorkContext());
            services.AddSingleton<IClock>(p => new Clock());

            services.AddTransient<T>();

            ConfigureServices(services);

            _provider = services.BuildServiceProvider();

            PopulateData(_provider.GetRequiredService<C>());
        }

This is a base type for some of my test classes. The last line `_provider.GetRequiredService<C>()` is where `C: DbContext`.

**Comment by Antaris** [comment]
Found the issue, for the InMemory database, you now need to explicitly tell it to use it:

    .AddDbContext<MyDbContext>(o => o.UseInMemoryDatabase());

**Comment by rowanmiller** [comment]
@Antaris we used to have some special logic, since in memory doesn't require any configuration (connection string etc.), to just use it if it was the only provider registered in services... but we decided not to special case this since in memory will probably be the only provider that doesn't require config.

**Comment by abelepereira** [comment]
Should the db context be disposed after usage in a controller or service? Or is the DI delivering a singleton db context?

**Comment by rowanmiller** [comment]
@abelepereira DI will take care of disposing the context (it's scoped to the request).

**Comment by marcosph** [comment]
Dear, Rowan Miller. I'm doing some tests used ASP.NET 5. My big problem is the dependency injection configuration. My project is on github: 
https://github.com/marcosph/DependencyInjectionASP.NET5/blob/master/WebApplication1/Startup.cs (Note: The project is divided into: 1- GztNews.Data, 2- GztNews.Service e WebApplication1 ).
It happens when I run the following error: {"No database providers are configured. Configure the database provider by overriding OnConfiguring DbContext in your class or in the AddDbContext method When setting up services."}
The error happens just in class
public abstract class RepositoryBase<T> where T : class
    {
        private GztNewsEntities dataContext;
        private readonly DbSet<T> dbset;
        protected RepositoryBase(IDbFactory databaseFactory)
        {
            DatabaseFactory = databaseFactory;
            dbset = DataContext.Set<T>();
        }

        protected IDbFactory DatabaseFactory
        {
            get;
            private set;
        }

        protected GztNewsEntities DataContext
        {
            get { return dataContext ?? (dataContext = DatabaseFactory.Init()); }
        }
        public virtual void Add(T entity)
        {
            dbset.Add(entity);
        }
        public virtual IEnumerable<T> GetAll()
        {
            return dbset.ToList();
        }
