### ISSUE TITLE
What do mean _._ files in nuget packages?

### ISSUE THREAD

**Issue by ggrnd0** [aspnet/Home#744]
There exists strange files named `_._` in `*.nupkg/lib/net46/`.
So, i cannot use any class from that assemblies...

What does it mean? (packages from nuget.org, but https://www.myget.org/gallery/aspnetvnext and https://www.myget.org/gallery/aspnetmaster have it too)

project.json

```
{
    "version": "0.0.2-apex",
    "authors": [ "ggrnd0@gmail.com" ],


    "frameworks": {
        "dnx50": {
            "dependencies": {
            }
        }
    },
    "dependencies": {
        "System.Xml.XDocument": "4.0.10-beta-23019",

        "System.Runtime.Serialization.Primitives": "4.0.10-beta-23019",
        "System.Runtime": "4.0.20-beta-22816"
    }
}
```

project.lock.json

```
{
  "locked": false,
  "version": 1,
  "targets": {
    "DNX,Version=v5.0": {
      "System.Runtime.Serialization.Primitives/4.0.10-beta-23019": {
        "compile": {
          "ref/net46/_._": {}
        },
        "runtime": {
          "lib/net46/_._": {}
        }
      },
      "System.Xml.XDocument/4.0.10-beta-23019": {
        "compile": {
          "ref/net46/_._": {}
        },
        "runtime": {
          "lib/net46/_._": {}
        }
      }
    }
  },
  "libraries": {
    "System.Runtime.Serialization.Primitives/4.0.10-beta-23019": {
      "sha512": "txtdLZ+b8B5/YIDthLTS4IUkt/pgl/RYIoLwp5ZEJ2dxurzkB99dOOIPFvkWoe3WJF7XWVSgmSZTO/VOvR6UlA==",
      "files": [
        "lib/dotnet/System.Runtime.Serialization.Primitives.dll",
        "lib/net46/_._",
        "ref/dotnet/System.Runtime.Serialization.Primitives.dll",
        "ref/net46/_._",
        "System.Runtime.Serialization.Primitives.4.0.10-beta-23019.nupkg",
        "System.Runtime.Serialization.Primitives.4.0.10-beta-23019.nupkg.sha512",
        "System.Runtime.Serialization.Primitives.nuspec"
      ]
    },
    "System.Xml.XDocument/4.0.10-beta-23019": {
      "sha512": "pyyzY5FFoZziGVDFyO5VLM094cX7jNN+01EsSJEFreje5uzSz6aKwIPgTe/l2CFiXYFoUNr0O6D3GEc8jPmbPg==",
      "files": [
        "lib/dotnet/System.Xml.XDocument.dll",
        "lib/net46/_._",
        "ref/dotnet/System.Xml.XDocument.dll",
        "ref/net46/_._",
        "System.Xml.XDocument.4.0.10-beta-23019.nupkg",
        "System.Xml.XDocument.4.0.10-beta-23019.nupkg.sha512",
        "System.Xml.XDocument.nuspec"
      ]
    }
  },
  "projectFileDependencyGroups": {
    "": [],
    "DNX,Version=v5.0": [
      "System.Xml.XDocument >= 4.0.10-beta-23019",
      "System.Runtime.Serialization.Primitives >= 4.0.10-beta-23019"
    ]
  }
}
```

**Comment by ggrnd0** [comment]
last good versions

                "System.Xml.XDocument": "4.0.10-beta-23008",
                "System.Runtime": "4.0.10-beta-23008",
                "System.Runtime.Serialization.Primitives": "4.0.10-beta-23008"

**Comment by Eilon** [comment]
They are placeholder files to denote an empty directory. Empty directories are often not well-supported in ZIPs so a file with that name is placed in there to ensure the directory is created.

This is important because the existence of an "empty" `net46` folder means that the package supports .NET Framework 4.6, but does not require any assemblies (DLLs) in order to run on that version of .NET. This is most likely because the implementation of the package is in the GAC.

**Comment by ggrnd0** [comment]
> This is most likely because the implementation of the package is in the GAC.

Packages was not in GAC at time.

now all files exists. not sure is it not a bug. =)

**Comment by Eilon** [comment]
@ericstj would you like to comment further on this?

**Comment by ericstj** [comment]
>This is most likely because the implementation of the package is in the GAC.
Not the GAC, in the targeting pack.

A place holder in both `ref` and `lib`, or in `lib` when no ref is present, indicates that the package is supported and both it's reference and implementation come from somewhere else.  Usually the targeting pack for the target framework.  Often times we will also have a "frameworkAssembly" reference in the nuspec to indicate that the reference should be added as a simple name to the targeting pack, and not a file in the nuget package.  For most of the System.Runtime and similar packages (which use Facades on desktop) we don't do this because MSBuild-based CSProj automatically adds all of the facades.

A place holder in only 'lib' when some 'ref' dll is in scope indicates that the package is not supported since it would provide a reference dll without any compile asset.

If you aren't getting the types at compile time in DNX after referencing this package I believe it may be due to a bug in DNX.  DNX should be referencing all of the in-box contract assemblies for NET* (and DNX*) target frameworks in order to match the behavior of MSBuild-based CSProj for the same. At one point we considered special casing DNX* to fix this, but discarded it since that would not fix targeting NET* in DNX.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
