### ISSUE TITLE
System.Web.Helpers.Crypto

### ISSUE THREAD

**Issue by henkmollema** [aspnet/Home#765]
MVC used to have a nice `Crypto` class containing helper methods for hasing + salting and verifying passwords.

It lived in the System.Web.Helpers namespace and was part of WebPages: http://aspnetwebstack.codeplex.com/SourceControl/latest#src/System.Web.Helpers/Crypto.cs

Is this (perhaps in another form) ported to MVC 6 yet? If not, are there any plans to and do you fancy a PR?

**Comment by henkmollema** [comment]
Ported it myself in the meantime: https://github.com/henkmollema/CryptoHelper

**Comment by HaoK** [comment]
It lives on in slightly different form as the Identity Password Hasher

https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNet.Identity/PasswordHasher.cs

**Comment by henkmollema** [comment]
I saw that passing, was just wondering if there is an implementation without a dependency on Identity.

**Comment by HaoK** [comment]
No I don't think so

**Comment by henkmollema** [comment]
Are there any plans to make an independent password hasher, or should I stick with my own port?

**Comment by blowdart** [comment]
Stick with your own port.

**Comment by henkmollema** [comment]
:+1:

**Comment by blowdart** [comment]
We do have a hash generator in the data protection stack - http://docs.asp.net/en/latest/security/data-protection/consumer-apis/password-hashing.html

This is what Identity uses under the hood. You might be better served calling it directly.

**Comment by GrabYourPitchforks** [comment]
It's curious that the identity password hasher is tied to the Identity types. The APIs accept arguments like TUser but don't actually *consume* said arguments. There's no reason this type can't be moved to its own standalone library.

To Barry's point, consider using the logic in PasswordHasher (even if it means you have to copy the type and remove its API dependencies on Identity) rather than the old System.Web.Helpers.Crypto code base. The new password hashing routines are stronger and more future-proof.

**Comment by HaoK** [comment]
Yeah it was a feature ask to provide access to the user so they can do more complicated things in their own password hashers if desired.  It just wasn't a goal for this to be used as a standalone non identity hasher.  We could certainly factor it that way if needed...

**Comment by henkmollema** [comment]
Thanks @blowdart and @GrabYourPitchforks, I'll refactor my implementation to use the new data protection stack.
