### ISSUE TITLE
docker build failed : some packages not downloaded

### ISSUE THREAD

**Issue by lloch** [aspnet/Home#772]
Hello,someone
I tried 
$ docker build -t helloweb .
and some packages can't be downloaded because of bad network(may be permanent).Would you like to help me solve this problem?

**Comment by tlk** [comment]
You need to run dnu restore in order to fix the missing downloads within the container. This Dockerfile does that: https://github.com/aspnet/Home/blob/8fe7a45ccb5b391cea8d0bf23d89bf39e817b355/samples/latest/HelloWeb/Dockerfile

The bleeding edge seems to be flaky right now, so consider changing the first line to `FROM microsoft/aspnet:1.0.0-beta5` and use it with https://github.com/aspnet/Home/tree/dev/samples/1.0.0-beta5/HelloWeb

**Comment by tlk** [comment]
PR #843 could possibly solve the root cause of this issue.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
