### ISSUE TITLE
Is is possible to detect unused dependencies in project.json?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Home#778]
I just now found and finally removed a package, `Microsoft.Framework.ConfigurationModel`, in one of my projects, which was just an oversight on my part. AFAIK, there was no warning or anything obvious in VS that it wasn't being used.

Is there a way to detect unused `project.json` dependencies in a solution?

**Comment by Eilon** [comment]
Not reliably. Some tools such as ReSharper try to do that for unused csproj reference. The problem with doing it reliably is that some types are loaded via reflection, and it is impossible to reliably detect that.

Now, it's certainly possible to detect *extraneous* references. That is, suppose package `A` depends on package `B` and in your `project.json` you reference `A` and `B` directly. The reference to `B` is *extraneous* because `A` will transitively bring in the reference to `B`. That's also unfortunately not *easy* to do because you might have an explicit reference to `B` in order to opt into using a higher version of `B` as compared to what `A` got you.

This is some difficult Comp. Sci. stuff :smile:

**Comment by Eilon** [comment]
BTW if you have some suggestions around a reliable mechanism for doing these please let us know your thoughts. I don't think the *entire* problem is solvable, but as I mentioned, there are likely *subsets* of the problem that are solvable (though the difficulty of implementing solutions to these problems varies greatly).
