### ISSUE TITLE
Helios - Microsoft.AspNet.Server.IIS is missing update for DNX renames

### ISSUE THREAD

**Issue by jhermsen** [aspnet/Home#798]
Apparently the DNX renames change brakes the IIS(Express) from running it.
I guess it misses a change like the followin in Kestrel:
https://github.com/aspnet/KestrelHttpServer/commit/07304640ed911e25fd2bb95112045c0e9b00d3eb

The error page mentions: missing method Microsoft.Dnx.Runtime.ILibraryManager.GetLibraryInformation in the System.Web.HttpRuntime.HostingInit method.

**Comment by Eilon** [comment]
@Tratcher can you take a look?

**Comment by davidfowl** [comment]
@jhermsen What does your project.json look like?

**Comment by dougbu** [comment]
@jhermsen we have been unable to build `Microsoft.AspNet.Server.IIS` since we took new packages for Core CLR. So that package doesn't contain a reaction to the `ILibraryManager` changes (though the sources have been updated). The Beta 7 feed (https://www.myget.org/F/aspnetvnext/api/v2) contains newer versions of everything _except_  `Microsoft.AspNet.Server.IIS`. The problem should be cleared up soon, when we next update the feed.

In the meantime please either use the stable feed (https://www.nuget.org/api/v2) or test using WebListener or Kestrel.

@troydai @Tratcher could you close this when people the unstable feed once again contains usable IIS support?

**Comment by ph1ll** [comment]
IIS/IIS Express is once again working using v1.0.0-beta7-12321 and the latest packages from https://www.myget.org/F/aspnetvnext/api/v2. Many thanks to the team.

**Comment by Eilon** [comment]
Awesome!
